/* papiman.c -- program to create  manpages for papi */
/* file: papiman.c
 * program for
 * 
 * PerfAPI Library          
 * 
 * July 1999. 
 * 
 * Cricket Haygood Deane 
 * Innovative Computing Labs 
 * University of Tennessee, Knoxville 
 * deane@cs.utk.edu 
 * 
 */ 

/*
 * This is a lightweight tool to generate papi_manpages
 * in standard manpage format using nroff and a specialized
 * format file [ papitmac.an ].  
 *
 * This program does not strip out the embedded print 
 * characters generated by nroff.  If you want that service,
 * try the program papiman2HTML.c.
 *
 * To compile this program:  
 *                   unix> make papiman
 *
 * To run this program:
 *                   unix> papiman PAPI_function_name
 * for example:
 *                   unix> papiman PAPI_start 
 */ 

#include <stdlib.h>
#include <stdio.h>
#include <malloc.h>
#include <string.h>

#define NUMBER_OF_FUNCTIONS 100
char *papi_function_list[NUMBER_OF_FUNCTIONS] = {
	"papiTemplate",
	"PAPI_accum",
	"PAPI_add_event",
	"PAPI_add_events",
	"PAPI_add_pevent",
	"PAPI_cleanup",
	"PAPI_describe_event",
	"PAPI_get_opt",
	"PAPI_init",
	"PAPI_help",
	"PAPI_list_events",
	"PAPI_num_events",
	"PAPI_overflow",
	"PAPI_perror",
	"PAPI_profil",
	"PAPI_query_event",
	"PAPI_read",
	"PAPI_read_counters",
	"PAPI_rem_event",
	"PAPI_rem_events",
	"PAPI_reset",
        "PAPI_restore",
	"PAPI_save",
	"PAPI_set_domain",
	"PAPI_set_granularity",
	"PAPI_set_opt",
	"PAPI_shutdown",
	"PAPI_start", 
        "PAPI_start_counters",
	"PAPI_state",
	"PAPI_stop",
	"PAPI_stop_counters",
	"PAPI_write"
	};


char *build_COMMAND(char *str);
	

int main(int argc, char *argv[]) {


int i;
int function_index=-1;
char *errMsg = "No papi manual entry for ";
char *COMMAND;


if (argc< 2) {
	printf("\n usage:  papiman  functionName \n");
	exit(0);
	}



/* command to run "nroff -e  papitmac.an argv[1] | more " */
COMMAND=(char *)malloc(128 * sizeof(char));
COMMAND=build_COMMAND(argv[1]);


/* identify function_index */
i=0;
while(papi_function_list[i]) {
if(!strcmp(argv[1],papi_function_list[i])) {
   function_index=i;
   break;
   }
i++;
}

/* -p option to allow testing of nonPAPIfunction files*/
if(argc==3) {
if(!strcmp(argv[2],"-p")) function_index=0;
}

if(function_index<0) {
	printf("\n %s %s.\n",errMsg,argv[1]);
	exit(0);
	}

/* display the manpage with nroff*/
system("clear");
system(COMMAND);


exit(0);

}/*end main*/




char *build_COMMAND(char *str) 
{
/* nroff -e papitmac.an PAPI_start -- prepend format file, run nroff    */
char *COMMAND;
COMMAND=(char *)malloc(128 * sizeof(char));
strcpy(COMMAND,"nroff -e  papitmac.an ");
strcat(COMMAND,str);
strcat(COMMAND," | more"); 

return(COMMAND);
}


