perl manserver_papi.pl -o html man3/papi.3
perl manserver_papi.pl -o html man3/papi_accum.3
perl manserver_papi.pl -o html man3/papi_accum_counters.3
perl manserver_papi.pl -o html man3/papi_add_event.3
perl manserver_papi.pl -o html man3/papi_add_events.3
perl manserver_papi.pl -o html man3/papi_add_pevent.3
perl manserver_papi.pl -o html man3/papi_cleanup_eventset.3
perl manserver_papi.pl -o html man3/papi_create_eventset.3
perl manserver_papi.pl -o html man3/papi_describe_event.3
perl manserver_papi.pl -o html man3/papi_destroy_eventset.3
perl manserver_papi.pl -o html man3/papi_event_code_to_name.3
perl manserver_papi.pl -o html man3/papi_event_name_to_code.3
perl manserver_papi.pl -o html man3/papi_flops.3
perl manserver_papi.pl -o html man3/papi_get_executable_info.3
perl manserver_papi.pl -o html man3/papi_get_hardware_info.3
perl manserver_papi.pl -o html man3/papi_get_opt.3
perl manserver_papi.pl -o html man3/papi_get_overflow_address.3
perl manserver_papi.pl -o html man3/papi_get_real_cyc.3
perl manserver_papi.pl -o html man3/papi_get_real_usec.3
perl manserver_papi.pl -o html man3/papi_get_virt_cyc.3
perl manserver_papi.pl -o html man3/papi_get_virt_usec.3
perl manserver_papi.pl -o html man3/papi_help.3
perl manserver_papi.pl -o html man3/papi_library_init.3
perl manserver_papi.pl -o html man3/papi_list_events.3
perl manserver_papi.pl -o html man3/papi_lock.3
perl manserver_papi.pl -o html man3/papi_multiplex_init.3
perl manserver_papi.pl -o html man3/papi_num_counters.3
perl manserver_papi.pl -o html man3/papi_overflow.3
perl manserver_papi.pl -o html man3/papi_perror.3
perl manserver_papi.pl -o html man3/papi_presets.3
perl manserver_papi.pl -o html man3/papi_profil.3
perl manserver_papi.pl -o html man3/papi_query_all_events_verbose.3
perl manserver_papi.pl -o html man3/papi_query_event.3
perl manserver_papi.pl -o html man3/papi_query_event_verbose.3
perl manserver_papi.pl -o html man3/papi_read.3
perl manserver_papi.pl -o html man3/papi_read_counters.3
perl manserver_papi.pl -o html man3/papi_rem_event.3
perl manserver_papi.pl -o html man3/papi_rem_events.3
perl manserver_papi.pl -o html man3/papi_rem_pevent.3
perl manserver_papi.pl -o html man3/papi_restore.3
perl manserver_papi.pl -o html man3/papi_reset.3
perl manserver_papi.pl -o html man3/papi_save.3
perl manserver_papi.pl -o html man3/papi_set_debug.3
perl manserver_papi.pl -o html man3/papi_set_domain.3
perl manserver_papi.pl -o html man3/papi_set_granularity.3
perl manserver_papi.pl -o html man3/papi_set_opt.3
perl manserver_papi.pl -o html man3/papi_shutdown.3
perl manserver_papi.pl -o html man3/papi_sprofil.3
perl manserver_papi.pl -o html man3/papi_start.3
perl manserver_papi.pl -o html man3/papi_start_counters.3
perl manserver_papi.pl -o html man3/papi_state.3
perl manserver_papi.pl -o html man3/papi_stop.3
perl manserver_papi.pl -o html man3/papi_stop_counters.3
perl manserver_papi.pl -o html man3/papi_strerror.3
perl manserver_papi.pl -o html man3/papi_thread_id.3
perl manserver_papi.pl -o html man3/papi_thread_init.3
perl manserver_papi.pl -o html man3/papi_unlock.3
perl manserver_papi.pl -o html man3/papi_write.3
perl manserver_papi.pl -o html man3/papif.3
