/*
 * Copyright (c) 2006, 2007 Advanced Micro Devices, Inc.
 * Contributed by Ray Bryant <raybry@mpdtxmail.amd.com>
 * Contributed by Robert Richter <robert.richter@amd.com>
 * Modified for K7 by Vince Weaver <vince _at_ csl.cornell.edu>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * This file is part of libpfm, a performance monitoring support library for
 * applications on Linux.
 */

/*
 * Definitions taken from "AMD Athlon Processor x86 Code Optimization Guide"
 * Table 11 February 2002
 */

static const amd64_entry_t amd64_k7_pe[]={
/*  0 */{.name = "DATA_CACHE_ACCESSES",
	.code  = 0x40,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Data Cache Accesses",
	},
/*  1 */{.name = "DATA_CACHE_MISSES",
	.code  = 0x41,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Data Cache Misses",
	},
/*  2 */{.name = "DATA_CACHE_REFILLS",
	.code  = 0x42,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Data Cache Refills from L2",
	.numasks = 6,
	.umasks  = {
		{ .uname = "L2_INVALID",
		  .udesc = "Invalid line from L2",
		  .ucode = 0x01,
		},
		{ .uname = "L2_SHARED",
		  .udesc = "Shared-state line from L2",
		  .ucode = 0x02,
		},
		{ .uname = "L2_EXCLUSIVE",
		  .udesc = "Exclusive-state line from L2",
		  .ucode = 0x04,
		},
		{ .uname = "L2_OWNED",
		  .udesc = "Owned-state line from L2",
		  .ucode = 0x08,
		},
		{ .uname = "L2_MODIFIED",
		  .udesc = "Modified-state line from L2",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "Shared, Exclusive, Owned, Modified State Refills",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  3 */{.name = "DATA_CACHE_REFILLS_FROM_SYSTEM",
	.code  = 0x43,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Data Cache Refills from System",
	.numasks = 6,
	.umasks  = {
		{ .uname = "INVALID",
		  .udesc = "Invalid",
		  .ucode = 0x01,
		},
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x02,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x04,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x08,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "Invalid, Shared, Exclusive, Owned, Modified",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  4 */{.name = "DATA_CACHE_LINES_EVICTED",
	.code  = 0x44,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Data Cache Lines Evicted",
	.numasks = 6,
	.umasks  = {
		{ .uname = "INVALID",
		  .udesc = "Invalid",
		  .ucode = 0x01,
		},
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x02,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x04,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x08,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "Invalid, Shared, Exclusive, Owned, Modified",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  5 */{.name = "L1_DTLB_MISS_AND_L2_DTLB_HIT",
	.code  = 0x45,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "L1 DTLB Miss and L2 DTLB Hit",
	},
/*  6 */{.name = "L1_DTLB_AND_L2_DTLB_MISS",
	.code  = 0x46,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "L1 DTLB and L2 DTLB Miss",
	},
/*  7 */{.name = "MISALIGNED_ACCESSES",
	.code  = 0x47,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Misaligned Accesses",
       },
        /* CPU_CLK_UNHALTED is undocumented in the Athlon Guide? */
/*  8 */{.name = "CPU_CLK_UNHALTED",
        .code  = 0x76,
        .attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "CPU Clocks not Halted",
        },
/*  9 */{.name = "INSTRUCTION_CACHE_FETCHES",
	.code  = 0x80,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Instruction Cache Fetches",
	},
/* 10 */{.name = "INSTRUCTION_CACHE_MISSES",
	.code  = 0x81,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Instruction Cache Misses",
	},
/* 11 */{.name = "L1_ITLB_MISS_AND_L2_ITLB_HIT",
	.code  = 0x84,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "L1 ITLB Miss and L2 ITLB Hit",
	},
/* 12 */{.name = "L1_ITLB_MISS_AND_L2_ITLB_MISS",
	.code  = 0x85,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "L1 ITLB Miss and L2 ITLB Miss",
	},
/* 13 */{.name = "RETIRED_INSTRUCTIONS",
	.code  = 0xC0,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Instructions (includes exceptions, interrupts, resyncs)",
	},
/* 14 */{.name = "RETIRED_UOPS",
	.code  = 0xC1,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired uops",
	},
/* 15 */{.name = "RETIRED_BRANCH_INSTRUCTIONS",
         .code  = 0xC2,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Branch Instructions",
	},
/* 16 */{.name = "RETIRED_MISPREDICTED_BRANCH_INSTRUCTIONS",
	.code  = 0xC3,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Mispredicted Branch Instructions",
	},
/* 17 */{.name = "RETIRED_TAKEN_BRANCH_INSTRUCTIONS",
	.code  = 0xC4,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Taken Branch Instructions",
	},
/* 18 */{.name = "RETIRED_TAKEN_BRANCH_INSTRUCTIONS_MISPREDICTED",
	.code  = 0xC5,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Taken Branch Instructions Mispredicted",
	},
/* 19 */{.name = "RETIRED_FAR_CONTROL_TRANSFERS",
	.code  = 0xC6,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Far Control Transfers",
	},
/* 20 */{.name = "RETIRED_BRANCH_RESYNCS",
	.code  = 0xC7,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Retired Branch Resyncs (only non-control transfer branches)",
	},
/* 21 */{.name = "INTERRUPTS_MASKED_CYCLES",
	.code  = 0xCD,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Interrupts-Masked Cycles",
	},
/* 22 */{.name = "INTERRUPTS_MASKED_CYCLES_WITH_INTERRUPT_PENDING",
	.code  = 0xCE,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Interrupts-Masked Cycles with Interrupt Pending",
	},
/* 23 */{.name = "INTERRUPTS_TAKEN",
	.code  = 0xCF,
	.attrmsk = AMD64_BASIC_ATTRS,
	.desc  = "Interrupts Taken",
	},
};

#define PME_AMD64_K7_EVENT_COUNT		(sizeof(amd64_k7_pe)/sizeof(amd64_entry_t))
