/*
 * Copyright (c) 2007 Advanced Micro Devices, Inc.
 * Contributed by Robert Richter <robert.richter@amd.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * This file is part of libpfm, a performance monitoring support library for
 * applications on Linux.
 */

/* History
 *
 * May 28 2010 -- Robert Richter, robert.richter@amd.com:
 *
 * Update from: BIOS and Kernel Developer's Guide (BKDG) For AMD
 * Family 10h Processors, 31116 Rev 3.48 - April 22, 2010
 *
 * Feb 06 2009 -- Robert Richter, robert.richter@amd.com:
 *
 * Update for Family 10h RevD (Istanbul) from: BIOS and Kernel
 * Developer's Guide (BKDG) For AMD Family 10h Processors, 31116 Rev
 * 3.20 - February 04, 2009
 *
 * Update for Family 10h RevC (Shanghai) from: BIOS and Kernel
 * Developer's Guide (BKDG) For AMD Family 10h Processors, 31116 Rev
 * 3.20 - February 04, 2009
 *
 *
 * Dec 12 2007 -- Robert Richter, robert.richter@amd.com:
 *
 * Created from: BIOS and Kernel Developer's Guide (BKDG) For AMD
 * Family 10h Processors, 31116 Rev 3.00 - September 07, 2007
 */

static const amd64_entry_t amd64_fam10h_pe[]={

/* Family 10h RevB, Barcelona */

/*  0 */{.name = "DISPATCHED_FPU",
	.code  = 0x00,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatched FPU Operations",
	.ngrp = 1,
	.numasks = 7,
	.umasks  = {
		{ .uname = "OPS_ADD",
		  .udesc = "Add pipe ops excluding load ops and SSE move ops",
		  .ucode = 0x01,
		},
		{ .uname = "OPS_MULTIPLY",
		  .udesc = "Multiply pipe ops excluding load ops and SSE move ops",
		  .ucode = 0x02,
		},
		{ .uname = "OPS_STORE",
		  .udesc = "Store pipe ops excluding load ops and SSE move ops",
		  .ucode = 0x04,
		},
		{ .uname = "OPS_ADD_PIPE_LOAD_OPS",
		  .udesc = "Add pipe load ops and SSE move ops",
		  .ucode = 0x08,
		},
		{ .uname = "OPS_MULTIPLY_PIPE_LOAD_OPS",
		  .udesc = "Multiply pipe load ops and SSE move ops",
		  .ucode = 0x10,
		},
		{ .uname = "OPS_STORE_PIPE_LOAD_OPS",
		  .udesc = "Store pipe load ops and SSE move ops",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  1 */{.name = "CYCLES_NO_FPU_OPS_RETIRED",
	.code  = 0x01,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Cycles in which the FPU is Empty",
	},
/*  2 */{.name = "DISPATCHED_FPU_OPS_FAST_FLAG",
	.code  = 0x02,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatched Fast Flag FPU Operations",
	},
/*  3 */{.name = "RETIRED_SSE_OPERATIONS",
	.code  = 0x03,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired SSE Operations",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "SINGLE_ADD_SUB_OPS",
		  .udesc = "Single precision add/subtract ops",
		  .ucode = 0x01,
		},
		{ .uname = "SINGLE_MUL_OPS",
		  .udesc = "Single precision multiply ops",
		  .ucode = 0x02,
		},
		{ .uname = "SINGLE_DIV_OPS",
		  .udesc = "Single precision divide/square root ops",
		  .ucode = 0x04,
		},
		{ .uname = "DOUBLE_ADD_SUB_OPS",
		  .udesc = "Double precision add/subtract ops",
		  .ucode = 0x08,
		},
		{ .uname = "DOUBLE_MUL_OPS",
		  .udesc = "Double precision multiply ops",
		  .ucode = 0x10,
		},
		{ .uname = "DOUBLE_DIV_OPS",
		  .udesc = "Double precision divide/square root ops",
		  .ucode = 0x20,
		},
		{ .uname = "OP_TYPE",
		  .udesc = "Op type: 0=uops. 1=FLOPS",
		  .ucode = 0x40,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x7F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  4 */{.name = "RETIRED_MOVE_OPS",
	.code  = 0x04,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Move Ops",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "LOW_QW_MOVE_UOPS",
		  .udesc = "Merging low quadword move uops",
		  .ucode = 0x01,
		},
		{ .uname = "HIGH_QW_MOVE_UOPS",
		  .udesc = "Merging high quadword move uops",
		  .ucode = 0x02,
		},
		{ .uname = "ALL_OTHER_MERGING_MOVE_UOPS",
		  .udesc = "All other merging move uops",
		  .ucode = 0x04,
		},
		{ .uname = "ALL_OTHER_MOVE_UOPS",
		  .udesc = "All other move uops",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  5 */{.name = "RETIRED_SERIALIZING_OPS",
	.code  = 0x05,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Serializing Ops",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "SSE_BOTTOM_EXECUTING_UOPS",
		  .udesc = "SSE bottom-executing uops retired",
		  .ucode = 0x01,
		},
		{ .uname = "SSE_BOTTOM_SERIALIZING_UOPS",
		  .udesc = "SSE bottom-serializing uops retired",
		  .ucode = 0x02,
		},
		{ .uname = "X87_BOTTOM_EXECUTING_UOPS",
		  .udesc = "x87 bottom-executing uops retired",
		  .ucode = 0x04,
		},
		{ .uname = "X87_BOTTOM_SERIALIZING_UOPS",
		  .udesc = "x87 bottom-serializing uops retired",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  6 */{.name = "FP_SCHEDULER_CYCLES",
	.code  = 0x06,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Number of Cycles that a Serializing uop is in the FP Scheduler",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "BOTTOM_EXECUTE_CYCLES",
		  .udesc = "Number of cycles a bottom-execute uop is in the FP scheduler",
		  .ucode = 0x01,
		},
		{ .uname = "BOTTOM_SERIALIZING_CYCLES",
		  .udesc = "Number of cycles a bottom-serializing uop is in the FP scheduler",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  7 */{.name = "SEGMENT_REGISTER_LOADS",
	.code  = 0x20,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Segment Register Loads",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "ES",
		  .udesc = "ES",
		  .ucode = 0x01,
		},
		{ .uname = "CS",
		  .udesc = "CS",
		  .ucode = 0x02,
		},
		{ .uname = "SS",
		  .udesc = "SS",
		  .ucode = 0x04,
		},
		{ .uname = "DS",
		  .udesc = "DS",
		  .ucode = 0x08,
		},
		{ .uname = "FS",
		  .udesc = "FS",
		  .ucode = 0x10,
		},
		{ .uname = "GS",
		  .udesc = "GS",
		  .ucode = 0x20,
		},
		{ .uname = "HS",
		  .udesc = "HS",
		  .ucode = 0x40,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x7F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/*  8 */{.name = "PIPELINE_RESTART_DUE_TO_SELF_MODIFYING_CODE",
	.code  = 0x21,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Pipeline Restart Due to Self-Modifying Code",
	},
/*  9 */{.name = "PIPELINE_RESTART_DUE_TO_PROBE_HIT",
	.code  = 0x22,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Pipeline Restart Due to Probe Hit",
	},
/* 10 */{.name = "LS_BUFFER_2_FULL_CYCLES",
	.code  = 0x23,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "LS Buffer 2 Full",
	},
/* 11 */{.name = "LOCKED_OPS",
	.code  = 0x24,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Locked Operations",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "EXECUTED",
		  .udesc = "The number of locked instructions executed",
		  .ucode = 0x01,
		},
		{ .uname = "CYCLES_SPECULATIVE_PHASE",
		  .udesc = "The number of cycles spent in speculative phase",
		  .ucode = 0x02,
		},
		{ .uname = "CYCLES_NON_SPECULATIVE_PHASE",
		  .udesc = "The number of cycles spent in non-speculative phase (including cache miss penalty)",
		  .ucode = 0x04,
		},
		{ .uname = "CYCLES_WAITING",
		  .udesc = "The number of cycles waiting for a cache hit (cache miss penalty).",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 12 */{.name = "RETIRED_CLFLUSH_INSTRUCTIONS",
	.code  = 0x26,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired CLFLUSH Instructions",
	},
/* 13 */{.name = "RETIRED_CPUID_INSTRUCTIONS",
	.code  = 0x27,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired CPUID Instructions",
	},
/* 14 */{.name = "CANCELLED_STORE_TO_LOAD_FORWARD_OPERATIONS",
	.code  = 0x2A,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Cancelled Store to Load Forward Operations",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "ADDRESS_MISMATCHES",
		  .udesc = "Address mismatches (starting byte not the same).",
		  .ucode = 0x01,
		},
		{ .uname = "STORE_IS_SMALLER_THAN_LOAD",
		  .udesc = "Store is smaller than load.",
		  .ucode = 0x02,
		},
		{ .uname = "MISALIGNED",
		  .udesc = "Misaligned.",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 15 */{.name = "SMIS_RECEIVED",
	.code  = 0x2B,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "SMIs Received",
	},
/* 16 */{.name = "DATA_CACHE_ACCESSES",
	.code  = 0x40,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Cache Accesses",
	},
/* 17 */{.name = "DATA_CACHE_MISSES",
	.code  = 0x41,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Cache Misses",
	},
/* 18 */{.name = "DATA_CACHE_REFILLS",
	.code  = 0x42,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Cache Refills from L2 or Northbridge",
	.ngrp = 1,
	.numasks = 6,
	.umasks  = {
		{ .uname = "SYSTEM",
		  .udesc = "Refill from the Northbridge",
		  .ucode = 0x01,
		},
		{ .uname = "L2_SHARED",
		  .udesc = "Shared-state line from L2",
		  .ucode = 0x02,
		},
		{ .uname = "L2_EXCLUSIVE",
		  .udesc = "Exclusive-state line from L2",
		  .ucode = 0x04,
		},
		{ .uname = "L2_OWNED",
		  .udesc = "Owned-state line from L2",
		  .ucode = 0x08,
		},
		{ .uname = "L2_MODIFIED",
		  .udesc = "Modified-state line from L2",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 19 */{.name = "DATA_CACHE_REFILLS_FROM_SYSTEM",
	.code  = 0x43,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Cache Refills from the Northbridge",
	.ngrp = 1,
	.numasks = 6,
	.umasks  = {
		{ .uname = "INVALID",
		  .udesc = "Invalid",
		  .ucode = 0x01,
		},
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x02,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x04,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x08,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 20 */{.name = "DATA_CACHE_LINES_EVICTED",
	.code  = 0x44,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Cache Lines Evicted",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "INVALID",
		  .udesc = "Invalid",
		  .ucode = 0x01,
		},
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x02,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x04,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x08,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x10,
		},
		{ .uname = "BY_PREFETCHNTA",
		  .udesc = "Cache line evicted was brought into the cache with by a PrefetchNTA instruction.",
		  .ucode = 0x20,
		},
		{ .uname = "NOT_BY_PREFETCHNTA",
		  .udesc = "Cache line evicted was not brought into the cache with by a PrefetchNTA instruction.",
		  .ucode = 0x40,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x7F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 21 */{.name = "L1_DTLB_MISS_AND_L2_DTLB_HIT",
	.code  = 0x45,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L1 DTLB Miss and L2 DTLB Hit",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "L2_4K_TLB_HIT",
		  .udesc = "L2 4K TLB hit",
		  .ucode = 0x01,
		},
		{ .uname = "L2_2M_TLB_HIT",
		  .udesc = "L2 2M TLB hit",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_TILL_FAM10H_REV_B|AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
		{ .uname = "L2_1G_TLB_HIT",
		  .udesc = "L2 1G TLB hit",
		  .ucode = 0x04,
		  .uflags = AMD64_FL_FAM10H_REV_C,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_FAM10H_REV_C|AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 22 */{.name = "L1_DTLB_AND_L2_DTLB_MISS",
	.code  = 0x46,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L1 DTLB and L2 DTLB Miss",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "4K_TLB_RELOAD",
		  .udesc = "4K TLB reload",
		  .ucode = 0x01,
		},
		{ .uname = "2M_TLB_RELOAD",
		  .udesc = "2M TLB reload",
		  .ucode = 0x02,
		},
		{ .uname = "1G_TLB_RELOAD",
		  .udesc = "1G TLB reload",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 23 */{.name = "MISALIGNED_ACCESSES",
	.code  = 0x47,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Misaligned Accesses",
	},
/* 24 */{.name = "MICROARCHITECTURAL_LATE_CANCEL_OF_AN_ACCESS",
	.code  = 0x48,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Microarchitectural Late Cancel of an Access",
	},
/* 25 */{.name = "MICROARCHITECTURAL_EARLY_CANCEL_OF_AN_ACCESS",
	.code  = 0x49,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Microarchitectural Early Cancel of an Access",
	},
/* 26 */{.name = "SCRUBBER_SINGLE_BIT_ECC_ERRORS",
	.code  = 0x4A,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Single-bit ECC Errors Recorded by Scrubber",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "SCRUBBER_ERROR",
		  .udesc = "Scrubber error",
		  .ucode = 0x01,
		},
		{ .uname = "PIGGYBACK_ERROR",
		  .udesc = "Piggyback scrubber errors",
		  .ucode = 0x02,
		},
		{ .uname = "LOAD_PIPE_ERROR",
		  .udesc = "Load pipe error",
		  .ucode = 0x04,
		},
		{ .uname = "STORE_WRITE_PIPE_ERROR",
		  .udesc = "Store write pipe error",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 27 */{.name = "PREFETCH_INSTRUCTIONS_DISPATCHED",
	.code  = 0x4B,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Prefetch Instructions Dispatched",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "LOAD",
		  .udesc = "Load (Prefetch, PrefetchT0/T1/T2)",
		  .ucode = 0x01,
		},
		{ .uname = "STORE",
		  .udesc = "Store (PrefetchW)",
		  .ucode = 0x02,
		},
		{ .uname = "NTA",
		  .udesc = "NTA (PrefetchNTA)",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 28 */{.name = "DCACHE_MISSES_BY_LOCKED_INSTRUCTIONS",
	.code  = 0x4C,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DCACHE Misses by Locked Instructions",
	.ngrp = 1,
	.numasks = 2,
	.umasks  = {
		{ .uname = "DATA_CACHE_MISSES_BY_LOCKED_INSTRUCTIONS",
		  .udesc = "Data cache misses by locked instructions",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x02,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 29 */{.name = "L1_DTLB_HIT",
	.code  = 0x4D,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L1 DTLB Hit",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "L1_4K_TLB_HIT",
		  .udesc = "L1 4K TLB hit",
		  .ucode = 0x01,
		},
		{ .uname = "L1_2M_TLB_HIT",
		  .udesc = "L1 2M TLB hit",
		  .ucode = 0x02,
		},
		{ .uname = "L1_1G_TLB_HIT",
		  .udesc = "L1 1G TLB hit",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 30 */{.name = "INEFFECTIVE_SW_PREFETCHES",
	.code  = 0x52,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Ineffective Software Prefetches",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "SW_PREFETCH_HIT_IN_L1",
		  .udesc = "Software prefetch hit in the L1.",
		  .ucode = 0x01,
		},
		{ .uname = "SW_PREFETCH_HIT_IN_L2",
		  .udesc = "Software prefetch hit in L2.",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x09,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 31 */{.name = "GLOBAL_TLB_FLUSHES",
	.code  = 0x54,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Global TLB Flushes",
	},
/* 32 */{.name = "MEMORY_REQUESTS",
	.code  = 0x65,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Memory Requests by Type",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "NON_CACHEABLE",
		  .udesc = "Requests to non-cacheable (UC) memory",
		  .ucode = 0x01,
		},
		{ .uname = "WRITE_COMBINING",
		  .udesc = "Requests to write-combining (WC) memory or WC buffer flushes to WB memory",
		  .ucode = 0x02,
		},
		{ .uname = "STREAMING_STORE",
		  .udesc = "Streaming store (SS) requests",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x83,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 33 */{.name = "DATA_PREFETCHES",
	.code  = 0x67,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Data Prefetcher",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "CANCELLED",
		  .udesc = "Cancelled prefetches",
		  .ucode = 0x01,
		},
		{ .uname = "ATTEMPTED",
		  .udesc = "Prefetch attempts",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 34 */{.name = "MAB_REQUESTS",
	.code  = 0x68,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Average L1 refill latency for Icache and Dcache misses (request count for cache refills)",
	.ngrp = 1,
	.numasks = 10,
	.umasks  = {
		{ .uname = "BUFFER_0",
		  .udesc = "Buffer 0",
		  .ucode = 0x00,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_1",
		  .udesc = "Buffer 1",
		  .ucode = 0x01,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_2",
		  .udesc = "Buffer 2",
		  .ucode = 0x02,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_3",
		  .udesc = "Buffer 3",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_4",
		  .udesc = "Buffer 4",
		  .ucode = 0x04,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_5",
		  .udesc = "Buffer 5",
		  .ucode = 0x05,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_6",
		  .udesc = "Buffer 6",
		  .ucode = 0x06,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_7",
		  .udesc = "Buffer 7",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_8",
		  .udesc = "Buffer 8",
		  .ucode = 0x08,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_9",
		  .udesc = "Buffer 9",
		  .ucode = 0x09,
		  .uflags = AMD64_FL_NCOMBO,
		},
	 },
	},
/* 35 */{.name = "MAB_WAIT_CYCLES",
	.code  = 0x69,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Average L1 refill latency for Icache and Dcache misses (cycles that requests spent waiting for the refills)",
	.ngrp = 1,
	.numasks = 10,
	.umasks  = {
		{ .uname = "BUFFER_0",
		  .udesc = "Buffer 0",
		  .ucode = 0x00,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_1",
		  .udesc = "Buffer 1",
		  .ucode = 0x01,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_2",
		  .udesc = "Buffer 2",
		  .ucode = 0x02,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_3",
		  .udesc = "Buffer 3",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_4",
		  .udesc = "Buffer 4",
		  .ucode = 0x04,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_5",
		  .udesc = "Buffer 5",
		  .ucode = 0x05,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_6",
		  .udesc = "Buffer 6",
		  .ucode = 0x06,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_7",
		  .udesc = "Buffer 7",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_8",
		  .udesc = "Buffer 8",
		  .ucode = 0x08,
		  .uflags = AMD64_FL_NCOMBO,
		},
		{ .uname = "BUFFER_9",
		  .udesc = "Buffer 9",
		  .ucode = 0x09,
		  .uflags = AMD64_FL_NCOMBO,
		},
	 },
	},
/* 36 */{.name = "SYSTEM_READ_RESPONSES",
	.code  = 0x6C,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Northbridge Read Responses by Coherency State",
	.ngrp = 1,
	.numasks = 6,
	.umasks  = {
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x01,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x02,
		},
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x04,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x08,
		},
		{ .uname = "DATA_ERROR",
		  .udesc = "Data Error",
		  .ucode = 0x10,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x1F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 37 */{.name = "QUADWORDS_WRITTEN_TO_SYSTEM",
	.code  = 0x6D,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Octwords Written to System",
	.ngrp = 1,
	.numasks = 2,
	.umasks  = {
		{ .uname = "QUADWORD_WRITE_TRANSFER",
		  .udesc = "Octword write transfer",
		  .ucode = 0x01,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x01,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 38 */{.name = "CPU_CLK_UNHALTED",
	.code  = 0x76,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Clocks not Halted",
	},
/* 39 */{.name = "REQUESTS_TO_L2",
	.code  = 0x7D,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Requests to L2 Cache",
	.ngrp = 1,
	.numasks = 7,
	.umasks  = {
		{ .uname = "INSTRUCTIONS",
		  .udesc = "IC fill",
		  .ucode = 0x01,
		},
		{ .uname = "DATA",
		  .udesc = "DC fill",
		  .ucode = 0x02,
		},
		{ .uname = "TLB_WALK",
		  .udesc = "TLB fill (page table walks)",
		  .ucode = 0x04,
		},
		{ .uname = "SNOOP",
		  .udesc = "Tag snoop request",
		  .ucode = 0x08,
		},
		{ .uname = "CANCELLED",
		  .udesc = "Cancelled request",
		  .ucode = 0x10,
		},
		{ .uname = "HW_PREFETCH_FROM_DC",
		  .udesc = "Hardware prefetch from DC",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 40 */{.name = "L2_CACHE_MISS",
	.code  = 0x7E,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L2 Cache Misses",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "INSTRUCTIONS",
		  .udesc = "IC fill",
		  .ucode = 0x01,
		},
		{ .uname = "DATA",
		  .udesc = "DC fill (includes possible replays, whereas EventSelect 041h does not)",
		  .ucode = 0x02,
		},
		{ .uname = "TLB_WALK",
		  .udesc = "TLB page table walk",
		  .ucode = 0x04,
		},
		{ .uname = "HW_PREFETCH_FROM_DC",
		  .udesc = "Hardware prefetch from DC",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 41 */{.name = "L2_FILL_WRITEBACK",
	.code  = 0x7F,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L2 Fill/Writeback",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "L2_FILLS",
		  .udesc = "L2 fills (victims from L1 caches, TLB page table walks and data prefetches)",
		  .ucode = 0x01,
		},
		{ .uname = "L2_WRITEBACKS",
		  .udesc = "L2 Writebacks to system.",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 42 */{.name = "INSTRUCTION_CACHE_FETCHES",
	.code  = 0x80,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Fetches",
	},
/* 43 */{.name = "INSTRUCTION_CACHE_MISSES",
	.code  = 0x81,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Misses",
	},
/* 44 */{.name = "INSTRUCTION_CACHE_REFILLS_FROM_L2",
	.code  = 0x82,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Refills from L2",
	},
/* 45 */{.name = "INSTRUCTION_CACHE_REFILLS_FROM_SYSTEM",
	.code  = 0x83,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Refills from System",
	},
/* 46 */{.name = "L1_ITLB_MISS_AND_L2_ITLB_HIT",
	.code  = 0x84,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L1 ITLB Miss and L2 ITLB Hit",
	},
/* 47 */{.name = "L1_ITLB_MISS_AND_L2_ITLB_MISS",
	.code  = 0x85,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L1 ITLB Miss and L2 ITLB Miss",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "4K_PAGE_FETCHES",
		  .udesc = "Instruction fetches to a 4K page.",
		  .ucode = 0x01,
		},
		{ .uname = "2M_PAGE_FETCHES",
		  .udesc = "Instruction fetches to a 2M page.",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 48 */{.name = "PIPELINE_RESTART_DUE_TO_INSTRUCTION_STREAM_PROBE",
	.code  = 0x86,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Pipeline Restart Due to Instruction Stream Probe",
	},
/* 49 */{.name = "INSTRUCTION_FETCH_STALL",
	.code  = 0x87,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Fetch Stall",
	},
/* 50 */{.name = "RETURN_STACK_HITS",
	.code  = 0x88,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Return Stack Hits",
	},
/* 51 */{.name = "RETURN_STACK_OVERFLOWS",
	.code  = 0x89,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Return Stack Overflows",
	},
/* 52 */{.name = "INSTRUCTION_CACHE_VICTIMS",
	.code  = 0x8B,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Victims",
	},
/* 53 */{.name = "INSTRUCTION_CACHE_LINES_INVALIDATED",
	.code  = 0x8C,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Instruction Cache Lines Invalidated",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "INVALIDATING_PROBE_NO_IN_FLIGHT",
		  .udesc = "Invalidating probe that did not hit any in-flight instructions.",
		  .ucode = 0x01,
		},
		{ .uname = "INVALIDATING_PROBE_ONE_OR_MORE_IN_FLIGHT",
		  .udesc = "Invalidating probe that hit one or more in-flight instructions.",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 54 */{.name = "ITLB_RELOADS",
	.code  = 0x99,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "ITLB Reloads",
	},
/* 55 */{.name = "ITLB_RELOADS_ABORTED",
	.code  = 0x9A,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "ITLB Reloads Aborted",
	},
/* 56 */{.name = "RETIRED_INSTRUCTIONS",
	.code  = 0xC0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Instructions",
	},
/* 57 */{.name = "RETIRED_UOPS",
	.code  = 0xC1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired uops",
	},
/* 58 */{.name = "RETIRED_BRANCH_INSTRUCTIONS",
	.code  = 0xC2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Branch Instructions",
	},
/* 59 */{.name = "RETIRED_MISPREDICTED_BRANCH_INSTRUCTIONS",
	.code  = 0xC3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Mispredicted Branch Instructions",
	},
/* 60 */{.name = "RETIRED_TAKEN_BRANCH_INSTRUCTIONS",
	.code  = 0xC4,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Taken Branch Instructions",
	},
/* 61 */{.name = "RETIRED_TAKEN_BRANCH_INSTRUCTIONS_MISPREDICTED",
	.code  = 0xC5,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Taken Branch Instructions Mispredicted",
	},
/* 62 */{.name = "RETIRED_FAR_CONTROL_TRANSFERS",
	.code  = 0xC6,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Far Control Transfers",
	},
/* 63 */{.name = "RETIRED_BRANCH_RESYNCS",
	.code  = 0xC7,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Branch Resyncs",
	},
/* 64 */{.name = "RETIRED_NEAR_RETURNS",
	.code  = 0xC8,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Near Returns",
	},
/* 65 */{.name = "RETIRED_NEAR_RETURNS_MISPREDICTED",
	.code  = 0xC9,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Near Returns Mispredicted",
	},
/* 66 */{.name = "RETIRED_INDIRECT_BRANCHES_MISPREDICTED",
	.code  = 0xCA,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Indirect Branches Mispredicted",
	},
/* 67 */{.name = "RETIRED_MMX_AND_FP_INSTRUCTIONS",
	.code  = 0xCB,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired MMX/FP Instructions",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "X87",
		  .udesc = "x87 instructions",
		  .ucode = 0x01,
		},
		{ .uname = "MMX_AND_3DNOW",
		  .udesc = "MMX and 3DNow! instructions",
		  .ucode = 0x02,
		},
		{ .uname = "PACKED_SSE_AND_SSE2",
		  .udesc = "SSE instructions (SSE, SSE2, SSE3, and SSE4A)",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 68 */{.name = "RETIRED_FASTPATH_DOUBLE_OP_INSTRUCTIONS",
	.code  = 0xCC,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired Fastpath Double Op Instructions",
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "POSITION_0",
		  .udesc = "With low op in position 0",
		  .ucode = 0x01,
		},
		{ .uname = "POSITION_1",
		  .udesc = "With low op in position 1",
		  .ucode = 0x02,
		},
		{ .uname = "POSITION_2",
		  .udesc = "With low op in position 2",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 69 */{.name = "INTERRUPTS_MASKED_CYCLES",
	.code  = 0xCD,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Interrupts-Masked Cycles",
	},
/* 70 */{.name = "INTERRUPTS_MASKED_CYCLES_WITH_INTERRUPT_PENDING",
	.code  = 0xCE,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Interrupts-Masked Cycles with Interrupt Pending",
	},
/* 71 */{.name = "INTERRUPTS_TAKEN",
	.code  = 0xCF,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Interrupts Taken",
	},
/* 72 */{.name = "DECODER_EMPTY",
	.code  = 0xD0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Decoder Empty",
	},
/* 73 */{.name = "DISPATCH_STALLS",
	.code  = 0xD1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stalls",
	},
/* 74 */{.name = "DISPATCH_STALL_FOR_BRANCH_ABORT",
	.code  = 0xD2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Branch Abort to Retire",
	},
/* 75 */{.name = "DISPATCH_STALL_FOR_SERIALIZATION",
	.code  = 0xD3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Serialization",
	},
/* 76 */{.name = "DISPATCH_STALL_FOR_SEGMENT_LOAD",
	.code  = 0xD4,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Segment Load",
	},
/* 77 */{.name = "DISPATCH_STALL_FOR_REORDER_BUFFER_FULL",
	.code  = 0xD5,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Reorder Buffer Full",
	},
/* 78 */{.name = "DISPATCH_STALL_FOR_RESERVATION_STATION_FULL",
	.code  = 0xD6,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Reservation Station Full",
	},
/* 79 */{.name = "DISPATCH_STALL_FOR_FPU_FULL",
	.code  = 0xD7,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for FPU Full",
	},
/* 80 */{.name = "DISPATCH_STALL_FOR_LS_FULL",
	.code  = 0xD8,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for LS Full",
	},
/* 81 */{.name = "DISPATCH_STALL_WAITING_FOR_ALL_QUIET",
	.code  = 0xD9,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall Waiting for All Quiet",
	},
/* 82 */{.name = "DISPATCH_STALL_FOR_FAR_TRANSFER_OR_RSYNC",
	.code  = 0xDA,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Dispatch Stall for Far Transfer or Resync to Retire",
	},
/* 83 */{.name = "FPU_EXCEPTIONS",
	.code  = 0xDB,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "FPU Exceptions",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "X87_RECLASS_MICROFAULTS",
		  .udesc = "x87 reclass microfaults",
		  .ucode = 0x01,
		},
		{ .uname = "SSE_RETYPE_MICROFAULTS",
		  .udesc = "SSE retype microfaults",
		  .ucode = 0x02,
		},
		{ .uname = "SSE_RECLASS_MICROFAULTS",
		  .udesc = "SSE reclass microfaults",
		  .ucode = 0x04,
		},
		{ .uname = "SSE_AND_X87_MICROTRAPS",
		  .udesc = "SSE and x87 microtraps",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 84 */{.name = "DR0_BREAKPOINT_MATCHES",
	.code  = 0xDC,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DR0 Breakpoint Matches",
	},
/* 85 */{.name = "DR1_BREAKPOINT_MATCHES",
	.code  = 0xDD,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DR1 Breakpoint Matches",
	},
/* 86 */{.name = "DR2_BREAKPOINT_MATCHES",
	.code  = 0xDE,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DR2 Breakpoint Matches",
	},
/* 87 */{.name = "DR3_BREAKPOINT_MATCHES",
	.code  = 0xDF,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DR3 Breakpoint Matches",
	},
/* 88 */{.name = "DRAM_ACCESSES_PAGE",
	.code  = 0xE0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DRAM Accesses",
	.ngrp = 1,
	.numasks = 7,
	.umasks  = {
		{ .uname = "HIT",
		  .udesc = "DCT0 Page hit",
		  .ucode = 0x01,
		},
		{ .uname = "MISS",
		  .udesc = "DCT0 Page Miss",
		  .ucode = 0x02,
		},
		{ .uname = "CONFLICT",
		  .udesc = "DCT0 Page Conflict",
		  .ucode = 0x04,
		},
		{ .uname = "DCT1_PAGE_HIT",
		  .udesc = "DCT1 Page hit",
		  .ucode = 0x08,
		},
		{ .uname = "DCT1_PAGE_MISS",
		  .udesc = "DCT1 Page Miss",
		  .ucode = 0x10,
		},
		{ .uname = "DCT1_PAGE_CONFLICT",
		  .udesc = "DCT1 Page Conflict",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 89 */{.name = "MEMORY_CONTROLLER_PAGE_TABLE_OVERFLOWS",
	.code  = 0xE1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "DRAM Controller Page Table Overflows",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "DCT0_PAGE_TABLE_OVERFLOW",
		  .udesc = "DCT0 Page Table Overflow",
		  .ucode = 0x01,
		},
		{ .uname = "DCT1_PAGE_TABLE_OVERFLOW",
		  .udesc = "DCT1 Page Table Overflow",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 90 */{.name = "MEMORY_CONTROLLER_SLOT_MISSES",
	.code  = 0xE2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Memory Controller DRAM Command Slots Missed",
	.ngrp = 1,
	.numasks = 3,
	.umasks  = {
		{ .uname = "DCT0_COMMAND_SLOTS_MISSED",
		  .udesc = "DCT0 Command Slots Missed",
		  .ucode = 0x01,
		},
		{ .uname = "DCT1_COMMAND_SLOTS_MISSED",
		  .udesc = "DCT1 Command Slots Missed",
		  .ucode = 0x02,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x03,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 91 */{.name = "MEMORY_CONTROLLER_TURNAROUNDS",
	.code  = 0xE3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Memory Controller Turnarounds",
	.ngrp = 1,
	.numasks = 7,
	.umasks  = {
		{ .uname = "CHIP_SELECT",
		  .udesc = "DCT0 DIMM (chip select) turnaround",
		  .ucode = 0x01,
		},
		{ .uname = "READ_TO_WRITE",
		  .udesc = "DCT0 Read to write turnaround",
		  .ucode = 0x02,
		},
		{ .uname = "WRITE_TO_READ",
		  .udesc = "DCT0 Write to read turnaround",
		  .ucode = 0x04,
		},
		{ .uname = "DCT1_DIMM",
		  .udesc = "DCT1 DIMM (chip select) turnaround",
		  .ucode = 0x08,
		},
		{ .uname = "DCT1_READ_TO_WRITE_TURNAROUND",
		  .udesc = "DCT1 Read to write turnaround",
		  .ucode = 0x10,
		},
		{ .uname = "DCT1_WRITE_TO_READ_TURNAROUND",
		  .udesc = "DCT1 Write to read turnaround",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 92 */{.name = "MEMORY_CONTROLLER_BYPASS",
	.code  = 0xE4,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Memory Controller Bypass Counter Saturation",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "HIGH_PRIORITY",
		  .udesc = "Memory controller high priority bypass",
		  .ucode = 0x01,
		},
		{ .uname = "LOW_PRIORITY",
		  .udesc = "Memory controller medium priority bypass",
		  .ucode = 0x02,
		},
		{ .uname = "DRAM_INTERFACE",
		  .udesc = "DCT0 DCQ bypass",
		  .ucode = 0x04,
		},
		{ .uname = "DRAM_QUEUE",
		  .udesc = "DCT1 DCQ bypass",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 93 */{.name = "THERMAL_STATUS_AND_ECC_ERRORS",
	.code  = 0xE8,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Thermal Status",
	.ngrp = 1,
	.numasks = 6,
	.umasks  = {
		{ .uname = "CLKS_DIE_TEMP_TOO_HIGH",
		  .udesc = "Number of times the HTC trip point is crossed",
		  .ucode = 0x04,
		},
		{ .uname = "CLKS_TEMP_THRESHOLD_EXCEEDED",
		  .udesc = "Number of clocks when STC trip point active",
		  .ucode = 0x08,
		},
		{ .uname = "STC_TRIP_POINTS_CROSSED",
		  .udesc = "Number of times the STC trip point is crossed",
		  .ucode = 0x10,
		},
		{ .uname = "CLOCKS_HTC_P_STATE_INACTIVE",
		  .udesc = "Number of clocks HTC P-state is inactive.",
		  .ucode = 0x20,
		},
		{ .uname = "CLOCKS_HTC_P_STATE_ACTIVE",
		  .udesc = "Number of clocks HTC P-state is active",
		  .ucode = 0x40,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x7C,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 94 */{.name = "CPU_IO_REQUESTS_TO_MEMORY_IO",
	.code  = 0xE9,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU/IO Requests to Memory/IO",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "I_O_TO_I_O",
		  .udesc = "IO to IO",
		  .ucode = 0x01,
		},
		{ .uname = "I_O_TO_MEM",
		  .udesc = "IO to Mem",
		  .ucode = 0x02,
		},
		{ .uname = "CPU_TO_I_O",
		  .udesc = "CPU to IO",
		  .ucode = 0x04,
		},
		{ .uname = "CPU_TO_MEM",
		  .udesc = "CPU to Mem",
		  .ucode = 0x08,
		},
		{ .uname = "TO_REMOTE_NODE",
		  .udesc = "To remote node",
		  .ucode = 0x10,
		},
		{ .uname = "TO_LOCAL_NODE",
		  .udesc = "To local node",
		  .ucode = 0x20,
		},
		{ .uname = "FROM_REMOTE_NODE",
		  .udesc = "From remote node",
		  .ucode = 0x40,
		},
		{ .uname = "FROM_LOCAL_NODE",
		  .udesc = "From local node",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 95 */{.name = "CACHE_BLOCK",
	.code  = 0xEA,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Cache Block Commands",
	.ngrp = 1,
	.numasks = 6,
	.umasks  = {
		{ .uname = "VICTIM_WRITEBACK",
		  .udesc = "Victim Block (Writeback)",
		  .ucode = 0x01,
		},
		{ .uname = "DCACHE_LOAD_MISS",
		  .udesc = "Read Block (Dcache load miss refill)",
		  .ucode = 0x04,
		},
		{ .uname = "SHARED_ICACHE_REFILL",
		  .udesc = "Read Block Shared (Icache refill)",
		  .ucode = 0x08,
		},
		{ .uname = "READ_BLOCK_MODIFIED",
		  .udesc = "Read Block Modified (Dcache store miss refill)",
		  .ucode = 0x10,
		},
		{ .uname = "READ_TO_DIRTY",
		  .udesc = "Change-to-Dirty (first store to clean block already in cache)",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3D,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 96 */{.name = "SIZED_COMMANDS",
	.code  = 0xEB,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Sized Commands",
	.ngrp = 1,
	.numasks = 7,
	.umasks  = {
		{ .uname = "NON_POSTED_WRITE_BYTE",
		  .udesc = "Non-Posted SzWr Byte (1-32 bytes) Legacy or mapped IO, typically 1-4 bytes",
		  .ucode = 0x01,
		},
		{ .uname = "NON_POSTED_WRITE_DWORD",
		  .udesc = "Non-Posted SzWr DW (1-16 dwords) Legacy or mapped IO, typically 1 DWORD",
		  .ucode = 0x02,
		},
		{ .uname = "POSTED_WRITE_BYTE",
		  .udesc = "Posted SzWr Byte (1-32 bytes) Subcache-line DMA writes, size varies; also flushes of partially-filled Write Combining buffer",
		  .ucode = 0x04,
		},
		{ .uname = "POSTED_WRITE_DWORD",
		  .udesc = "Posted SzWr DW (1-16 dwords) Block-oriented DMA writes, often cache-line sized; also processor Write Combining buffer flushes",
		  .ucode = 0x08,
		},
		{ .uname = "READ_BYTE_4_BYTES",
		  .udesc = "SzRd Byte (4 bytes) Legacy or mapped IO",
		  .ucode = 0x10,
		},
		{ .uname = "READ_DWORD_1_16_DWORDS",
		  .udesc = "SzRd DW (1-16 dwords) Block-oriented DMA reads, typically cache-line size",
		  .ucode = 0x20,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 97 */{.name = "PROBE",
	.code  = 0xEC,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Probe Responses and Upstream Requests",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "MISS",
		  .udesc = "Probe miss",
		  .ucode = 0x01,
		},
		{ .uname = "HIT_CLEAN",
		  .udesc = "Probe hit clean",
		  .ucode = 0x02,
		},
		{ .uname = "HIT_DIRTY_NO_MEMORY_CANCEL",
		  .udesc = "Probe hit dirty without memory cancel (probed by Sized Write or Change2Dirty)",
		  .ucode = 0x04,
		},
		{ .uname = "HIT_DIRTY_WITH_MEMORY_CANCEL",
		  .udesc = "Probe hit dirty with memory cancel (probed by DMA read or cache refill request)",
		  .ucode = 0x08,
		},
		{ .uname = "UPSTREAM_DISPLAY_REFRESH_READS",
		  .udesc = "Upstream display refresh/ISOC reads",
		  .ucode = 0x10,
		},
		{ .uname = "UPSTREAM_NON_DISPLAY_REFRESH_READS",
		  .udesc = "Upstream non-display refresh reads",
		  .ucode = 0x20,
		},
		{ .uname = "UPSTREAM_WRITES",
		  .udesc = "Upstream ISOC writes",
		  .ucode = 0x40,
		},
		{ .uname = "UPSTREAM_NON_ISOC_WRITES",
		  .udesc = "Upstream non-ISOC writes",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 98 */{.name = "GART",
	.code  = 0xEE,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "GART Events",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "APERTURE_HIT_FROM_CPU",
		  .udesc = "GART aperture hit on access from CPU",
		  .ucode = 0x01,
		},
		{ .uname = "APERTURE_HIT_FROM_IO",
		  .udesc = "GART aperture hit on access from IO",
		  .ucode = 0x02,
		},
		{ .uname = "MISS",
		  .udesc = "GART miss",
		  .ucode = 0x04,
		},
		{ .uname = "REQUEST_HIT_TABLE_WALK",
		  .udesc = "GART/DEV Request hit table walk in progress",
		  .ucode = 0x08,
		},
		{ .uname = "DEV_HIT",
		  .udesc = "DEV hit",
		  .ucode = 0x10,
		},
		{ .uname = "DEV_MISS",
		  .udesc = "DEV miss",
		  .ucode = 0x20,
		},
		{ .uname = "DEV_ERROR",
		  .udesc = "DEV error",
		  .ucode = 0x40,
		},
		{ .uname = "MULTIPLE_TABLE_WALK",
		  .udesc = "GART/DEV multiple table walk in progress",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 99 */{.name = "MEMORY_CONTROLLER_REQUESTS",
	.code  = 0x1F0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Memory Controller Requests",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "WRITE_REQUESTS",
		  .udesc = "Write requests sent to the DCT",
		  .ucode = 0x01,
		},
		{ .uname = "READ_REQUESTS",
		  .udesc = "Read requests (including prefetch requests) sent to the DCT",
		  .ucode = 0x02,
		},
		{ .uname = "PREFETCH_REQUESTS",
		  .udesc = "Prefetch requests sent to the DCT",
		  .ucode = 0x04,
		},
		{ .uname = "32_BYTES_WRITES",
		  .udesc = "32 Bytes Sized Writes",
		  .ucode = 0x08,
		},
		{ .uname = "64_BYTES_WRITES",
		  .udesc = "64 Bytes Sized Writes",
		  .ucode = 0x10,
		},
		{ .uname = "32_BYTES_READS",
		  .udesc = "32 Bytes Sized Reads",
		  .ucode = 0x20,
		},
		{ .uname = "64_BYTES_READS",
		  .udesc = "64 Byte Sized Reads",
		  .ucode = 0x40,
		},
		{ .uname = "READ_REQUESTS_WHILE_WRITES_REQUESTS",
		  .udesc = "Read requests sent to the DCT while writes requests are pending in the DCT",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 100 */{.name = "CPU_TO_DRAM_REQUESTS_TO_TARGET_NODE",
	.code  = 0x1E0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU to DRAM Requests to Target Node",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "LOCAL_TO_0",
		  .udesc = "From Local node to Node 0",
		  .ucode = 0x01,
		},
		{ .uname = "LOCAL_TO_1",
		  .udesc = "From Local node to Node 1",
		  .ucode = 0x02,
		},
		{ .uname = "LOCAL_TO_2",
		  .udesc = "From Local node to Node 2",
		  .ucode = 0x04,
		},
		{ .uname = "LOCAL_TO_3",
		  .udesc = "From Local node to Node 3",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_4",
		  .udesc = "From Local node to Node 4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_5",
		  .udesc = "From Local node to Node 5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_6",
		  .udesc = "From Local node to Node 6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_7",
		  .udesc = "From Local node to Node 7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 101 */{.name = "IO_TO_DRAM_REQUESTS_TO_TARGET_NODE",
	.code  = 0x1E1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "IO to DRAM Requests to Target Node",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "LOCAL_TO_0",
		  .udesc = "From Local node to Node 0",
		  .ucode = 0x01,
		},
		{ .uname = "LOCAL_TO_1",
		  .udesc = "From Local node to Node 1",
		  .ucode = 0x02,
		},
		{ .uname = "LOCAL_TO_2",
		  .udesc = "From Local node to Node 2",
		  .ucode = 0x04,
		},
		{ .uname = "LOCAL_TO_3",
		  .udesc = "From Local node to Node 3",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_4",
		  .udesc = "From Local node to Node 4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_5",
		  .udesc = "From Local node to Node 5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_6",
		  .udesc = "From Local node to Node 6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_7",
		  .udesc = "From Local node to Node 7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 102 */{.name = "CPU_READ_COMMAND_LATENCY_TO_TARGET_NODE_0_3",
	.code  = 0x1E2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Read Command Latency to Target Node 0-3",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_BLOCK",
		  .udesc = "Read block",
		  .ucode = 0x01,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read block shared",
		  .ucode = 0x02,
		},
		{ .uname = "READ_BLOCK_MODIFIED",
		  .udesc = "Read block modified",
		  .ucode = 0x04,
		},
		{ .uname = "CHANGE_TO_DIRTY",
		  .udesc = "Change-to-Dirty",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_0",
		  .udesc = "From Local node to Node 0",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_1",
		  .udesc = "From Local node to Node 1",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_2",
		  .udesc = "From Local node to Node 2",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_3",
		  .udesc = "From Local node to Node 3",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 103 */{.name = "CPU_READ_COMMAND_REQUESTS_TO_TARGET_NODE_0_3",
	.code  = 0x1E3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Read Command Requests to Target Node 0-3",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_BLOCK",
		  .udesc = "Read block",
		  .ucode = 0x01,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read block shared",
		  .ucode = 0x02,
		},
		{ .uname = "READ_BLOCK_MODIFIED",
		  .udesc = "Read block modified",
		  .ucode = 0x04,
		},
		{ .uname = "CHANGE_TO_DIRTY",
		  .udesc = "Change-to-Dirty",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_0",
		  .udesc = "From Local node to Node 0",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_1",
		  .udesc = "From Local node to Node 1",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_2",
		  .udesc = "From Local node to Node 2",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_3",
		  .udesc = "From Local node to Node 3",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 104 */{.name = "CPU_READ_COMMAND_LATENCY_TO_TARGET_NODE_4_7",
	.code  = 0x1E4,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Read Command Latency to Target Node 4-7",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_BLOCK",
		  .udesc = "Read block",
		  .ucode = 0x01,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read block shared",
		  .ucode = 0x02,
		},
		{ .uname = "READ_BLOCK_MODIFIED",
		  .udesc = "Read block modified",
		  .ucode = 0x04,
		},
		{ .uname = "CHANGE_TO_DIRTY",
		  .udesc = "Change-to-Dirty",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_4",
		  .udesc = "From Local node to Node 4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_5",
		  .udesc = "From Local node to Node 5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_6",
		  .udesc = "From Local node to Node 6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_7",
		  .udesc = "From Local node to Node 7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 105 */{.name = "CPU_READ_COMMAND_REQUESTS_TO_TARGET_NODE_4_7",
	.code  = 0x1E5,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Read Command Requests to Target Node 4-7",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_BLOCK",
		  .udesc = "Read block",
		  .ucode = 0x01,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read block shared",
		  .ucode = 0x02,
		},
		{ .uname = "READ_BLOCK_MODIFIED",
		  .udesc = "Read block modified",
		  .ucode = 0x04,
		},
		{ .uname = "CHANGE_TO_DIRTY",
		  .udesc = "Change-to-Dirty",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_4",
		  .udesc = "From Local node to Node 4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_5",
		  .udesc = "From Local node to Node 5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_6",
		  .udesc = "From Local node to Node 6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_7",
		  .udesc = "From Local node to Node 7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 106 */{.name = "CPU_COMMAND_LATENCY_TO_TARGET_NODE_0_3_4_7",
	.code  = 0x1E6,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Command Latency to Target Node 0-3/4-7",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_SIZED",
		  .udesc = "Read Sized",
		  .ucode = 0x01,
		},
		{ .uname = "WRITE_SIZED",
		  .udesc = "Write Sized",
		  .ucode = 0x02,
		},
		{ .uname = "VICTIM_BLOCK",
		  .udesc = "Victim Block",
		  .ucode = 0x04,
		},
		{ .uname = "NODE_GROUP_SELECT",
		  .udesc = "Node Group Select. 0=Nodes 0-3. 1= Nodes 4-7.",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_0_4",
		  .udesc = "From Local node to Node 0/4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_1_5",
		  .udesc = "From Local node to Node 1/5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_2_6",
		  .udesc = "From Local node to Node 2/6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_3_7",
		  .udesc = "From Local node to Node 3/7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 107 */{.name = "CPU_REQUESTS_TO_TARGET_NODE_0_3_4_7",
	.code  = 0x1E7,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "CPU Requests to Target Node 0-3/4-7",
	.ngrp = 1,
	.numasks = 9,
	.umasks  = {
		{ .uname = "READ_SIZED",
		  .udesc = "Read Sized",
		  .ucode = 0x01,
		},
		{ .uname = "WRITE_SIZED",
		  .udesc = "Write Sized",
		  .ucode = 0x02,
		},
		{ .uname = "VICTIM_BLOCK",
		  .udesc = "Victim Block",
		  .ucode = 0x04,
		},
		{ .uname = "NODE_GROUP_SELECT",
		  .udesc = "Node Group Select. 0=Nodes 0-3. 1= Nodes 4-7.",
		  .ucode = 0x08,
		},
		{ .uname = "LOCAL_TO_0_4",
		  .udesc = "From Local node to Node 0/4",
		  .ucode = 0x10,
		},
		{ .uname = "LOCAL_TO_1_5",
		  .udesc = "From Local node to Node 1/5",
		  .ucode = 0x20,
		},
		{ .uname = "LOCAL_TO_2_6",
		  .udesc = "From Local node to Node 2/6",
		  .ucode = 0x40,
		},
		{ .uname = "LOCAL_TO_3_7",
		  .udesc = "From Local node to Node 3/7",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0xFF,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 108 */{.name = "HYPERTRANSPORT_LINK0",
	.code  = 0xF6,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "HyperTransport Link 0 Transmit Bandwidth",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "COMMAND_DWORD_SENT",
		  .udesc = "Command DWORD sent",
		  .ucode = 0x01,
		},
		{ .uname = "DATA_DWORD_SENT",
		  .udesc = "Data DWORD sent",
		  .ucode = 0x02,
		},
		{ .uname = "BUFFER_RELEASE_DWORD_SENT",
		  .udesc = "Buffer release DWORD sent",
		  .ucode = 0x04,
		},
		{ .uname = "NOP_DWORD_SENT",
		  .udesc = "Nop DW sent (idle)",
		  .ucode = 0x08,
		},
		{ .uname = "ADDRESS_EXT_DWORD_SENT",
		  .udesc = "Address extension DWORD sent",
		  .ucode = 0x10,
		},
		{ .uname = "PER_PACKET_CRC_SENT",
		  .udesc = "Per packet CRC sent",
		  .ucode = 0x20,
		},
		{ .uname = "SUBLINK_MASK",
		  .udesc = "SubLink Mask",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL, /* COMBO needed to allow SUBLINK_MASK */
		},
	 },
	},
/* 109 */{.name = "HYPERTRANSPORT_LINK1",
	.code  = 0xF7,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "HyperTransport Link 1 Transmit Bandwidth",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "COMMAND_DWORD_SENT",
		  .udesc = "Command DWORD sent",
		  .ucode = 0x01,
		},
		{ .uname = "DATA_DWORD_SENT",
		  .udesc = "Data DWORD sent",
		  .ucode = 0x02,
		},
		{ .uname = "BUFFER_RELEASE_DWORD_SENT",
		  .udesc = "Buffer release DWORD sent",
		  .ucode = 0x04,
		},
		{ .uname = "NOP_DWORD_SENT",
		  .udesc = "Nop DW sent (idle)",
		  .ucode = 0x08,
		},
		{ .uname = "ADDRESS_EXT_DWORD_SENT",
		  .udesc = "Address extension DWORD sent",
		  .ucode = 0x10,
		},
		{ .uname = "PER_PACKET_CRC_SENT",
		  .udesc = "Per packet CRC sent",
		  .ucode = 0x20,
		},
		{ .uname = "SUBLINK_MASK",
		  .udesc = "SubLink Mask",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL, /* COMBO needed to allow SUBLINK_MASK */
		},
	 },
	},
/* 110 */{.name = "HYPERTRANSPORT_LINK2",
	.code  = 0xF8,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "HyperTransport Link 2 Transmit Bandwidth",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "COMMAND_DWORD_SENT",
		  .udesc = "Command DWORD sent",
		  .ucode = 0x01,
		},
		{ .uname = "DATA_DWORD_SENT",
		  .udesc = "Data DWORD sent",
		  .ucode = 0x02,
		},
		{ .uname = "BUFFER_RELEASE_DWORD_SENT",
		  .udesc = "Buffer release DWORD sent",
		  .ucode = 0x04,
		},
		{ .uname = "NOP_DWORD_SENT",
		  .udesc = "Nop DW sent (idle)",
		  .ucode = 0x08,
		},
		{ .uname = "ADDRESS_EXT_DWORD_SENT",
		  .udesc = "Address extension DWORD sent",
		  .ucode = 0x10,
		},
		{ .uname = "PER_PACKET_CRC_SENT",
		  .udesc = "Per packet CRC sent",
		  .ucode = 0x20,
		},
		{ .uname = "SUBLINK_MASK",
		  .udesc = "SubLink Mask",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL, /* COMBO needed to allow SUBLINK_MASK */
		},
	 },
	},
/* 111 */{.name = "HYPERTRANSPORT_LINK3",
	.code  = 0x1F9,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "HyperTransport Link 3 Transmit Bandwidth",
	.ngrp = 1,
	.numasks = 8,
	.umasks  = {
		{ .uname = "COMMAND_DWORD_SENT",
		  .udesc = "Command DWORD sent",
		  .ucode = 0x01,
		},
		{ .uname = "DATA_DWORD_SENT",
		  .udesc = "Data DWORD sent",
		  .ucode = 0x02,
		},
		{ .uname = "BUFFER_RELEASE_DWORD_SENT",
		  .udesc = "Buffer release DWORD sent",
		  .ucode = 0x04,
		},
		{ .uname = "NOP_DWORD_SENT",
		  .udesc = "Nop DW sent (idle)",
		  .ucode = 0x08,
		},
		{ .uname = "ADDRESS_EXT_DWORD_SENT",
		  .udesc = "Address DWORD sent",
		  .ucode = 0x10,
		},
		{ .uname = "PER_PACKET_CRC_SENT",
		  .udesc = "Per packet CRC sent",
		  .ucode = 0x20,
		},
		{ .uname = "SUBLINK_MASK",
		  .udesc = "SubLink Mask",
		  .ucode = 0x80,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x3F,
		  .uflags = AMD64_FL_DFL, /* COMBO needed to allow SUBLINK_MASK */
		},
	 },
	},
/* 112 */{.name = "READ_REQUEST_TO_L3_CACHE",
	.code  = 0x4E0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Read Request to L3 Cache",
	.flags = AMD64_FL_TILL_FAM10H_REV_C,
	.ngrp = 2,
	.numasks = 5,
	.umasks  = {
		{ .uname = "READ_BLOCK_EXCLUSIVE",
		  .udesc = "Read Block Exclusive (Data cache read)",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read Block Shared (Instruction cache read)",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_MODIFY",
		  .udesc = "Read Block Modify",
		  .ucode = 0x04,
		  .grpid = 0,
		},
		{ .uname = "ANY_READ",
		  .udesc = "any read modes (exclusive, shared, modify)",
		  .ucode = 0x07,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */
		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x80,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All sub-events selected",
		  .ucode = 0xF0,
		  .grpid = 1,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 113 */{.name = "L3_CACHE_MISSES",
	.code  = 0x4E1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L3 Cache Misses",
	.flags = AMD64_FL_TILL_FAM10H_REV_C,
	.ngrp = 2,
	.numasks = 5,
	.umasks  = {
		{ .uname = "READ_BLOCK_EXCLUSIVE",
		  .udesc = "Read Block Exclusive (Data cache read)",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read Block Shared (Instruction cache read)",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_MODIFY",
		  .udesc = "Read Block Modify",
		  .ucode = 0x04,
		  .grpid = 0,
		},
		{ .uname = "ANY_READ",
		  .udesc = "any read modes (exclusive, shared, modify)",
		  .ucode = 0x07,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */
		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x80,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 114 */{.name = "L3_FILLS_CAUSED_BY_L2_EVICTIONS",
	.code  = 0x4E2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L3 Fills caused by L2 Evictions",
	.flags = AMD64_FL_TILL_FAM10H_REV_C,
	.ngrp = 2,
	.numasks = 6,
	.umasks  = {
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x04,
		  .grpid = 0,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x08,
		  .grpid = 0,
		},
		{ .uname = "ANY_STATE",
		  .udesc = "any line state (shared, owned, exclusive, modified)",
		  .ucode = 0x0f,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */

		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x80,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 115 */{.name = "L3_EVICTIONS",
	.code  = 0x4E3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L3 Evictions",
	.ngrp = 1,
	.numasks = 5,
	.umasks  = {
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x01,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x02,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x04,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x08,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x0F,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},

/* Family 10h RevC, Shanghai */

/* 116 */{.name = "PAGE_SIZE_MISMATCHES",
	.code  = 0x165,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Page Size Mismatches",
	.flags = AMD64_FL_FAM10H_REV_C,
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "GUEST_LARGER",
		  .udesc = "Guest page size is larger than the host page size.",
		  .ucode = 0x01,
		},
		{ .uname = "MTRR_MISMATCH",
		  .udesc = "MTRR mismatch.",
		  .ucode = 0x02,
		},
		{ .uname = "HOST_LARGER",
		  .udesc = "Host page size is larger than the guest page size.",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 117 */{.name = "RETIRED_X87_OPS",
	.code  = 0x1C0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Retired x87 Floating Point Operations",
	.flags = AMD64_FL_FAM10H_REV_C,
	.ngrp = 1,
	.numasks = 4,
	.umasks  = {
		{ .uname = "ADD_SUB_OPS",
		  .udesc = "Add/subtract ops",
		  .ucode = 0x01,
		},
		{ .uname = "MUL_OPS",
		  .udesc = "Multiply ops",
		  .ucode = 0x02,
		},
		{ .uname = "DIV_OPS",
		  .udesc = "Divide ops",
		  .ucode = 0x04,
		},
		{ .uname = "ALL",
		  .udesc = "All sub-events selected",
		  .ucode = 0x07,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 118 */{.name = "IBS_OPS_TAGGED",
	.code  = 0x1CF,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "IBS Ops Tagged",
	.flags = AMD64_FL_FAM10H_REV_C,
	},
/* 119 */{.name = "LFENCE_INST_RETIRED",
	.code  = 0x1D3,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "LFENCE Instructions Retired",
	.flags = AMD64_FL_FAM10H_REV_C,
	},
/* 120 */{.name = "SFENCE_INST_RETIRED",
	.code  = 0x1D4,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "SFENCE Instructions Retired",
	.flags = AMD64_FL_FAM10H_REV_C,
	},
/* 121 */{.name = "MFENCE_INST_RETIRED",
	.code  = 0x1D5,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "MFENCE Instructions Retired",
	.flags = AMD64_FL_FAM10H_REV_C,
	},

/* Family 10h RevD, Istanbul */

/* 122 */{.name = "READ_REQUEST_TO_L3_CACHE",
	.code  = 0x4E0,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Read Request to L3 Cache",
	.flags = AMD64_FL_FAM10H_REV_D,
	.ngrp = 2,
	.numasks = 5,
	.umasks  = {
		{ .uname = "READ_BLOCK_EXCLUSIVE",
		  .udesc = "Read Block Exclusive (Data cache read)",
		  .ucode = 0x01,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read Block Shared (Instruction cache read)",
		  .ucode = 0x02,
		},
		{ .uname = "READ_BLOCK_MODIFY",
		  .udesc = "Read Block Modify",
		  .ucode = 0x04,
		},
		{ .uname = "ANY_READ",
		  .udesc = "any read modes (exclusive, shared, modify)",
		  .ucode = 0x07,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */
		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x00,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x30,
		},
		{ .uname = "CORE_4_SELECT",
		  .udesc = "Core 4 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_5_SELECT",
		  .udesc = "Core 5 Select",
		  .ucode = 0x50,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		},
	 },
	},
/* 123 */{.name = "L3_CACHE_MISSES",
	.code  = 0x4E1,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L3 Cache Misses",
	.flags = AMD64_FL_FAM10H_REV_D,
	.ngrp = 2,
	.numasks = 5,
	.umasks  = {
		{ .uname = "READ_BLOCK_EXCLUSIVE",
		  .udesc = "Read Block Exclusive (Data cache read)",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read Block Shared (Instruction cache read)",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_MODIFY",
		  .udesc = "Read Block Modify",
		  .grpid = 0,
		  .ucode = 0x04,
		},
		{ .uname = "ANY_READ",
		  .udesc = "any read modes (exclusive, shared, modify)",
		  .ucode = 0x07,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */

		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x00,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x30,
		},
		{ .uname = "CORE_4_SELECT",
		  .udesc = "Core 4 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_5_SELECT",
		  .udesc = "Core 5 Select",
		  .ucode = 0x50,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 124 */{.name = "L3_FILLS_CAUSED_BY_L2_EVICTIONS",
	.code  = 0x4E2,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "L3 Fills caused by L2 Evictions",
	.flags = AMD64_FL_FAM10H_REV_D,
	.ngrp = 2,
	.numasks = 6,
	.umasks  = {
		{ .uname = "SHARED",
		  .udesc = "Shared",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "EXCLUSIVE",
		  .udesc = "Exclusive",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "OWNED",
		  .udesc = "Owned",
		  .ucode = 0x04,
		  .grpid = 0,
		},
		{ .uname = "MODIFIED",
		  .udesc = "Modified",
		  .ucode = 0x08,
		  .grpid = 0,
		},
		{ .uname = "ANY_STATE",
		  .udesc = "any line state (shared, owned, exclusive, modified)",
		  .ucode = 0x0f,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */
		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x00,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x30,
		},
		{ .uname = "CORE_4_SELECT",
		  .udesc = "Core 4 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_5_SELECT",
		  .udesc = "Core 5 Select",
		  .ucode = 0x50,
		},
		{ .uname = "ANY_CORE",
		  .udesc = "Any core",
		  .ucode = 0xF0,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		  .uflags = AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
	 },
	},
/* 125 */{.name = "NON_CANCELLED_L3_READ_REQUESTS",
	.code  = 0x4ED,
	.modmsk = AMD64_FAM10H_ATTRS,
	.desc  = "Non-cancelled L3 Read Requests",
	.flags = AMD64_FL_FAM10H_REV_D,
	.ngrp = 2,
	.numasks = 5,
	.umasks  = {
		{ .uname = "READ_BLOCK_EXCLUSIVE",
		  .udesc = "Read Block Exclusive (Data cache read)",
		  .ucode = 0x01,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_SHARED",
		  .udesc = "Read Block Shared (Instruction cache read)",
		  .ucode = 0x02,
		  .grpid = 0,
		},
		{ .uname = "READ_BLOCK_MODIFY",
		  .udesc = "Read Block Modify",
		  .ucode = 0x04,
		  .grpid = 0,
		},
		{ .uname = "ANY_READ",
		  .udesc = "any read modes (exclusive, shared, modify)",
		  .ucode = 0x07,
		  .grpid = 0,
		  .uflags=AMD64_FL_DFL|AMD64_FL_NCOMBO,
		},
#if 0
/*
 *    http://support.amd.com/us/Processor_TechDocs/41322.pdf
 *
 *    Issue number 437 on page 131.
 *
 */
		{ .uname = "CORE_0_SELECT",
		  .udesc = "Core 0 Select",
		  .ucode = 0x00,
		},
		{ .uname = "CORE_1_SELECT",
		  .udesc = "Core 1 Select",
		  .ucode = 0x10,
		},
		{ .uname = "CORE_2_SELECT",
		  .udesc = "Core 2 Select",
		  .ucode = 0x20,
		},
		{ .uname = "CORE_3_SELECT",
		  .udesc = "Core 3 Select",
		  .ucode = 0x30,
		},
		{ .uname = "CORE_4_SELECT",
		  .udesc = "Core 4 Select",
		  .ucode = 0x40,
		},
		{ .uname = "CORE_5_SELECT",
		  .udesc = "Core 5 Select",
		  .ucode = 0x50,
		},
#endif
		{ .uname = "ALL_CORES",
		  .udesc = "All cores",
		  .ucode = 0xF0,
		  .grpid = 1,
		},
	 },
	},

/* Family 10h, IBS pseudo-events */
#if 0
/* 126 */{.name = "IBSFETCH_EVENT",
	.code  = 0xFF,
	.modmsk = AMD64_FAM10H_ATTRS_IBSFE,
	.desc  = "pseudo-event to enable IBS Fetch sampling",
	.flags = AMD64_FL_IBSFE,
	},
/* 127 */{.name = "IBSOP_EVENT",
	.code  = 0xFF,
	.modmsk = AMD64_FAM10H_ATTRS_IBSOP,
	.desc  = "pseudo-event to enable IBS Op sampling",
	.flags = AMD64_FL_IBSOP,
	},
#endif
};

#define PME_AMD64_FAM10H_EVENT_COUNT		(sizeof(amd64_fam10h_pe)/sizeof(amd64_entry_t))
