#define PAPI_QUIET       0
#define PAPI_VERB_ECONT  1
#define PAPI_VERB_ESTOP  2
#define PAPI_SET_DEBUG   2
#define PAPI_GET_DEBUG   3
#define PAPI_SET_DEFDOM  6
#define PAPI_GET_DEFDOM  7
#define PAPI_SET_DOMAIN  8
#define PAPI_GET_DOMAIN  9
#define PAPI_SET_DEFGRN  10
#define PAPI_GET_DEFGRN  11
#define PAPI_SET_GRANUL  12
#define PAPI_GET_GRANUL  13 
#define PAPI_SET_INHERIT 15
#define PAPI_GET_INHERIT 16

#define PAPI_DOM_MIN     PAPI_DOM_USER
#define PAPI_DOM_MAX     PAPI_DOM_ALL
#define PAPI_DOM_HWSPEC  z'80000000' 

#define PAPI_GRN_THR     z'1'
#define PAPI_GRN_MIN     PAPI_GRN_THR
#define PAPI_GRN_PROC    z'2'
#define PAPI_GRN_PROCG   z'4'
#define PAPI_GRN_SYS     z'8'
#define PAPI_GRN_SYS_CPU z'10'
#define PAPI_GRN_MAX     PAPI_GRN_SYS_CPU

#define PAPI_PROFIL_POSIX    z'0'
#define PAPI_PROFIL_RANDOM   z'1' 
#define PAPI_PROFIL_WEIGHTED z'2' 
#define PAPI_PROFIL_COMPRESS z'4'

#define NUM_TESTS 5
#define NUM_FLOPS 10000000
