

cuda-component-job:
  tags: [nvidia-gh200]
  image: nvidia/cuda:12.8.2-devel-ubuntu24.04
  script:
    - /usr/local/cuda/bin/nvcc --version
    - cd src
    - ./configure --prefix=$PWD/test-install --with-components="stealtime" --with-debug=yes
    - make && make install
    - utils/papi_component_avail

example-job:
  tags: [amd-mi100]
  script:
    - ls /opt
