cuda-component-job:
  tags: [nvidia-gh200]
  image: nvidia/cuda:12.8.2-devel-ubuntu24.04
  script:
    - export PAPI_CUDA_ROOT=/usr/local/cuda
    - cd src
    - ./configure --prefix=$PWD/test-install --with-components="cuda" --with-debug=yes
    - make && make install
    - utils/papi_component_avail
    - bash components/cuda/tests/run_cuda_tests.sh
  rules:
    - changes:
        paths:
          - 'src/components/cuda/**'

amd-smi-component-job:
  tags: [odyssey]
  image: rocm/dev-ubuntu-24.04:7.2.2-complete
  script:
    - export PAPI_AMDSMI_ROOT=/opt/rocm-7.2.2
    - cd src
    - ./configure --prefix=$PWD/test-install --with-components="amd_smi" --with-debug=yes
    - make && make install
    - utils/papi_component_avail
    - bash components/amd_smi/tests/runtest.sh

disable-cpu-job:
  tags: [hpsf-x86_64]
  script:
    - cd src
    - ./configure --prefix=$PWD/test-install --disable-cpu
    - utils/papi_component_avail

disable-perf-event-job:
  tags: [hpsf-x86_64]
  script:
    - cd src 
    - ./configure --prefix=$PWD/test-install --disable-cpu
    - utils/papi_component_avail

disable-perf-event-uncore-job:
  tags: [hpsf-x86_64]
  script:
    - cd src 
    - ./configure --prefix=$PWD/test-install --disable-cpu
    - utils/papi_component_avail
    
