# File: ctests/Makefile

include Makefile.target

INCLUDE = -I../testlib -I.. -I.
PAPILIB= ../$(LIBRARY)
testlibdir= ../testlib
TESTLIB= $(testlibdir)/libtestlib.a
DOLOOPS= $(testlibdir)/do_loops.o
CLOCKCORE= $(testlibdir)/clockcore.o
EXTRALIB = -lrt

include Makefile.recipies

