.TH "binary_tree_t" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binary_tree_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBroot\fP"
.br
.ti -1c
.RI "\fBthreads_t\fP * \fBfind_p\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBthreads_t\fP* binary_tree_t::find_p"
Pointer that is used for finding a thread node 
.SS "void* binary_tree_t::root"
Root of binary tree 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
