.TH "HighLevelInfo" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HighLevelInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBEventSet\fP"
.br
.ti -1c
.RI "short int \fBnum_evts\fP"
.br
.ti -1c
.RI "short int \fBrunning\fP"
.br
.ti -1c
.RI "long long \fBinitial_time\fP"
.br
.ti -1c
.RI "float \fBtotal_proc_time\fP"
.br
.ti -1c
.RI "float \fBtotal_ins\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBHighLevelInfo::EventSet\fP"EventSet of the thread 
.SS "long long \fBHighLevelInfo::initial_time\fP"Start time 
.SS "float \fBHighLevelInfo::total_ins\fP"Total instructions 
.SS "float \fBHighLevelInfo::total_proc_time\fP"Total processor time 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
