.TH "local_components_t" 3 "Thu Feb 27 2020" "Version 6.0.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local_components_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBEventSet\fP"
.br
.ti -1c
.RI "long_long * \fBvalues\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long_long* local_components_t::values"
Return values for the eventsets 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
