.\" $Id$
.TH PAPI_describe_eventset 3 "October, 2000" "PAPI Programmer's Manual" "PAPI"

.SH NAME
PAPI_describe_event, PAPI_event_name_to_code, PAPI_event_code_to_name \- convert a hardware event to a description, number or string symbol.

.SH SYNOPSIS
.B #include <papi.h>

.nf
.BI "int\ PAPI_describe_event(char *" name ", int *" code ", char *" descr ");"
.BI "int\ PAPI_event_name_to_code(char *" name ", int *" code ");"
.BI "int\ PAPI_event_code_to_name(int " code ", char *" name ");"
.if

.SH DESCRIPTION
.B PAPI_describe_event(\|)
is used to translate either an ASCII PAPI preset name or an integer PAPI preset event code into an ASCII description of that event. The functionality of this call is a superset of the following two calls. 

.B PAPI_event_name_to_code(\|)
is used to translate an ASCII PAPI preset name into an integer PAPI event code.

.B PAPI_event_code_to_name(\|)
is used to translate an integer PAPI event code into an ASCII PAPI preset name.

The
.IR name
argument for the three calls must always be non-NULL and point to a string of at least length
.BR PAPI_MAX_STR_LEN .

.SH RETURN VALUES
On success, this function returns
.IR "PAPI_OK" .
On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOTPRESET"
The hardware event specified is not a valid PAPI preset. 

.SH EXAMPLES
.LP
.nf
.if t .ft CW
int EventCode, EventSet = PAPI_NULL;
char EventCodeStr[PAPI_MAX_STR_LEN];
char EventDescr[PAPI_MAX_STR_LEN];
	
/* Convert to integer */

if (PAPI_event_name_to_code("PAPI_TOT_INS",&EventCode) != PAPI_OK)
  handle_error(1);

/* Describe event from EventCode */

if (PAPI_describe_event(EventCodeStr,&EventCode,EventDescr) != PAPI_OK)
  handle_error(1);

/* Create the EventSet */

if (PAPI_create_eventset(&EventSet) != PAPI_OK)
  handle_error(1);

/* Add Total Instructions Executed to our EventSet */

if (PAPI_add_event(&EventSet, EventCode) != PAPI_OK)
  handle_error(1);
.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_preset "(3), " PAPI_add_event "(3), " 
.BR PAPI_set_opt "(3), " PAPI__events "(3), " PAPI_query "(3), "
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi

