.\" $Id$
.TH PAPI_num_components 3 "April, 2007" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_num_components \- return the number of components currently installed 

.SH SYNOPSIS
.B C Interface
.nf
.B #include <papi.h>
.BI "int PAPI_num_components();"
.fi

.SH DESCRIPTION
.B "PAPI_num_components()" 
returns the number of counting components
 installed in the library. 

.SH ARGUMENTS
This function takes no arguments.

.SH RETURN VALUES
This function returns a value greater than zero.

.SH EXAMPLES
.LP
.nf
.if t .ft CW
/* Query the library for a component count. */
printf("%d components installed.\n", PAPI_num_components());
.if t .ft P
.fi

.SH BUGS
None.

.SH SEE ALSO
.BR PAPI "(3)"
