.TH "PAPIF_get_clockrate" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_get_clockrate \- 
.PP
Get the clockrate in MHz for the current cpu.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Prototype:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_set_domain( C_INT cr )
.RE
.PP
\fBNote:\fP
.RS 4
This is a Fortran only interface that returns a value from the \fBPAPI_get_opt\fP call.
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_get_opt\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
