.\" @(#)$Id$
.TH PAPI_profil 3 "October, 2000" "PAPI Programmer's Manual" "PAPI"

.SH NAME
PAPI_profil, PAPI_sprofil \- generate PC histogram data where hardware counter overflow occurs

.SH SYNOPSIS
.B #include <papi.h>

.BI "int PAPI_profil(unsigned short *" buf ", unsigned " bufsiz ", unsigned long " offset ", unsigned " scale ", int " EventSet ", int " EventCode ", int " threshold ", int " flags ");"
.LP
.BI "int PAPI_sprofil(PAPI_sprofil_t *" prof ", int " profcnt ", int " EventSet ", int " EventCode ", int " threshold ", int " flags ");"

.SH DESCRIPTION
.B PAPI_profil()
takes the following arguments:
.LP
.I *buf
-- pointer to profile buffer array.
.LP
.I bufsiz
-- number of entries in *buf.
.LP
.I offset
-- starting value of lowest entry in *buf
.LP
.I scale
-- 
.LP
.I EventSet 
-- The PAPI EventSet to profile when it is started.
.LP
.I EventCode
-- Code of the Event in the EventSet to profile.
.LP
.I threshold 
-- threshold value for the Event triggers the handler. 
.LP
.I flags 
-- bit pattern to control the behavior of PAPI_sprofil(). 
.LP

.B PAPI_sprofil()
takes the following arguments:
.LP
.I *prof
-- pointer to sprofil structure.
.LP
.I profcnt
-- 
.LP
.I EventSet 
-- The PAPI EventSet to profile when it is started.
.LP
.I EventCode
-- Code of the Event in the EventSet to profile.
.LP
.I threshold 
-- threshold value for the Event triggers the handler. 
.LP
.I flags 
-- bit pattern to control the behavior of PAPI_sprofil(). 

.TS
allbox tab($);
cw(40)  s
lB lw(40).
T{
Defined bits for the 
.I flags 
varible
T}
PAPI_PROFIL_POSIX$T{
Default type of profiling, similar to 
.BR profil (3).
T}
PAPI_PROFIL_RANDOM$T{
Drop a random 25% of the samples.
T}
PAPI_PROFIL_WEIGHTED$T{
Weight the samples by their value.
T}
PAPI_PROFIL_COMPRESS$T{
Ignore samples if hash buckets get big.
T}
.TE

.SH RETURN VALUES
On success, this function returns
.I "PAPI_OK."
On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOMEM"
Insufficient memory to complete the operation.
.TP
.B "PAPI_ENOEVST"
The EventSet specified does not exist.
.TP
.B "PAPI_EISRUN"
The EventSet is currently counting events.
.TP
.B "PAPI_ECNFLCT"
The underlying counter hardware can not count this event and other events
in the EventSet simultaneously.
.TP
.B "PAPI_NOEVNT"
The PAPI preset is not available on the underlying hardware. 

.SH EXAMPLES
.nf
.if t .ft CW
int retval;
int EventSet = PAPI_NULL;
unsigned long start, end, length;
PAPI_exe_info_t *prginfo;
unsigned short *profbuf;

retval = PAPI_library_init(PAPI_VER_CURRENT);

if (retval != PAPI_VER_CURRENT & retval > 0) {
  fprintf(stderr,"PAPI library version mismatch!\n");
  exit(1); }

if (retval < 0) 
  handle_error(retval);

if ((prginfo = PAPI_get_executable_info()) == NULL)
  handle_error(1);

start = (unsigned long)prginfo->text_start;
end = (unsigned long)prginfo->text_end;
length = end - start;

profbuf = (unsigned short *)malloc(length*sizeof(unsigned short));
if (profbuf == NULL)
  handle_error(1);
memset(profbuf,0x00,length*sizeof(unsigned short));

if ((retval = PAPI_create_eventset(&EventSet)) != PAPI_OK)
  handle_error(retval);

/* Add Total FP Instructions Executed to our EventSet */

if ((retval = PAPI_add_event(&EventSet, PAPI_FP_INS)) != PAPI_OK)
  handle_error(retval);

if ((retval = PAPI_profil(profbuf, length, start, 65536, EventSet, 
                PAPI_FP_INS, 1000000, PAPI_PROFIL_POSIX)) != PAPI_OK)
  handle_error(retval);

/* Start counting */

if ((retval = PAPI_start(EventSet)) != PAPI_OK)
  handle_error(1);
.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This woeful man page.

.SH SEE ALSO
.BR PAPI_preset "(3), " PAPI_get_executable_info "(3), "
.BR PAPI_set_opt "(3), " PAPI_start "(3), " PAPI_rem_event "(3), " 
.BR PAPI_rem_events "(3), " PAPI_query "(3), "
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The\ PAPI\ Web\ Site: 
.B http://icl.cs.utk.edu/projects/papi

