.\" $Id$
.TH PAPI_multiplex_init 3 "September, 2004" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_multiplex_init \- initialize multiplex support in the PAPI library

.SH SYNOPSIS
.B C Interface
.nf
.B #include <papi.h>
.BI "int PAPI_multiplex_init (void);"
.fi
.B Fortran Interface
.nf
.B #include "fpapi.h"
.BI PAPIF_multiplex_init(C_INT\  check )
.fi

.SH DESCRIPTION
.B "PAPI_multiplex_init"
enables and initializes multiplex support in the PAPI library.
Multiplexing allows a user to count more events than total physical counters
by time sharing the existing counters at some loss in precision.
Applications that make no use of multiplexing do not need to call
this routine.

.SH RETURN VALUES
This function always returns
.B "PAPI_OK."

.SH ERRORS
.I No errors are reported.

.SH EXAMPLES
.nf         
.if t .ft CW
retval = PAPI_multiplex_init();
.if t .ft P
.fi

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_set_multiplex "(3), "PAPI_get_multiplex "(3)"
