.TH "PAPIF_accum" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_accum \- accumulate and reset counters in an event set  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
\fBPAPIF_accum( C_INT EventSet, C_LONG_LONG(*) values, C_INT  check )\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_accum\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
