.TH "PAPIF_is_initialized" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_is_initialized \- 
.PP
Check for initialization.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_is_initialized( C_INT level )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_is_initialized\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
