.TH "PAPI_num_cmp_hwctrs" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_num_cmp_hwctrs \- 
.PP
Return the number of hardware counters for the specified component'\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBPAPI_num_cmp_hwctrs()\fP returns the number of counters present in the specified component'\&. By convention, component 0 is always the cpu'\&. This count does not include any special purpose registers or other performance hardware'\&. \fBPAPI_library_init()\fP must be called in order for this function to return anything greater than 0'\&.
.PP
\fBC Interface:\fP
.RS 4
#include <\fBpapi'\&.h\fP> 
.br
 int PAPI_num_cmp_hwctrs(int  cidx );
.RE
.PP
\fBParameters:\fP
.RS 4
\fIcidx\fP -- An integer identifier for a component'\&. By convention, component 0 is always the cpu component'\&.
.RE
.PP
\fBExample\fP
.RS 4

.PP
.nf
 // Query the cpu component for the number of counters\&.
 printf(\'%d hardware counters found\&.\\n\', PAPI_num_cmp_hwctrs(0));

.fi
.PP
.RE
.PP
\fBReturns:\fP
.RS 4
On success, this function returns a value greater than zero'\&.
.br
 A zero result usually means the library has not been initialized'\&.
.RE
.PP
\fBBug\fP
.RS 4
This count may include fixed-use counters in addition to the general purpose counters'\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
