.\" $Id$
.TH "PAPI_save" 3 "October, 2000" "PAPI Programmer's Manual" "PAPI"

.SH NAME
.nf
PAPI_save \- Save the current state of the PAPI library
PAPI_restore \- Restore the saved state of the PAPI library
.fi

.SH SYNOPSIS
.B #include <papi.h>

.nf
.BI int PAPI_save(void);
.BI int PAPI_restore(void);
.fi

.SH DESCRIPTION
.B "PAPI_save()"
"freezes" the current state of the PAPI_library. Among tasks done is
to register the current values of any running virtual counters to be able to
restore these at the time of a subsequent 
.BR PAPI_restore .
.LP
.B "PAPI_restore()"
restores the current state of the PAPI_library to a state that has previously
been saved using 
.BR PAPI_save .

.SH RETURN VALUES
On success, 
.IR "PAPI_OK" , 
is returned and on error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_ESBSTR"
The substrate does not provide the save/restore functionality.
.TP
.B "PAPI_EINVAL"
A 
.B PAPI_restore 
was attempted, but there is no saved state to restore.

.SH EXAMPLES
.LP
.nf
.if t .ft CW
int retval;

retval = PAPI_save();
THIRD_PARTY_TOOL_update_gui_counters();
retval = PAPI_restore();

.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
These functions are not yet implemented.

.SH SEE ALSO
The\ PAPI\ Web\ Site: 
.B http://icl.cs.utk.edu/projects/papi

