.TH "PAPIF_set_debug" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_set_debug \- 
.PP
Set the current debug level for error output from PAPI.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Prototype:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_set_debug( C_INT level, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_set_debug\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
