.TH "PAPIF_remove_event" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_remove_event \- 
.PP
Remove a hardware event from a PAPI event set.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran interface:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_remove_event( C_INT EventSet, C_INT EventCode, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_remove_event\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
