.\" $Id$
.TH PAPI_native 3 "September, 2004" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_native \- Accessing PAPI native events

.SH SYNOPSIS
.nf
.B #include <papi.h>
.fi

.SH DESCRIPTION
In addition to the predefined PAPI preset events, the PAPI library also
exposes a majority of the events native to each platform.
Native events form the basic building blocks for PAPI presets. They can also
be used directly to access functions specific to a given platform.
.LP
Since native events are
.I by definition
specific to each platform, the names for these events are unique to each platform.
Native events for a given platform can be discovered by combining the
.BR PAPI_enum_event "(3) and " PAPI_event_code_to_name "(3) or " PAPI_get_event_info "(3) functions."

.SH BUGS
Not every native event on every platform can be represented 
through the native event interface. Occasionally, exotic but 
valuable events are not represented. There is presently no method
for representing these events in a PAPI event set.

.SH SEE ALSO
.BR PAPI "(3), " PAPI_presets "(3), " PAPI_enum_event "(3), " PAPI_get_event_info "(3), "
.BR PAPI_event_code_to_name "(3), " PAPI_event_name_to_code "(3)"
