.TH "PAPI_exe_info_t" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_exe_info_t \- 
.PP
get the executable's info  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <papi.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBfullname\fP [1024]"
.br
.ti -1c
.RI "\fBPAPI_address_map_t\fP \fBaddress_info\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPAPI_address_map_t\fP \fBPAPI_exe_info_t::address_info\fP"executable's address space info 
.SS "char \fBPAPI_exe_info_t::fullname\fP[1024]"path + name 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
