.TH "PAPI_num_components" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_num_components \- Get the number of components available on the system\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBReturns\fP
.RS 4
Number of components available on the system
.RE
.PP
.PP
.nf
// Query the library for a component count\&. 
printf("%d components installed\&., PAPI_num_components() );
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
