.TH "PAPIF_get_dev_attr" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_get_dev_attr \- returns device attributes  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
\fBPAPIF_get_dev_attr\fP( C_INT handle, C_INT id, C_INT attribute, 
.br
 C_INT value, C_STRING string, C_INT check )
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPIF_get_dev_attr\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
