.TH "PAPIF_cleanup_eventset" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_cleanup_eventset \- empty and destroy an EventSet  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
\fBPAPIF_cleanup_eventset( C_INT EventSet, C_INT check )\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_cleanup_eventset\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
