.\" @(#)$Id$
.TH PAPI_profil 3 "October, 2000" "" "PAPI"

.SH NAME
PAPI_profil, PAPI_sprofil \- generate PC histogram data where hardware counter overflow occurs
.LP
.SH SYNOPSIS
.LP
int PAPI_sprofil (prof, profcnt, EventSet, EventNum, threshold, flags)
.LP
PAPI_sprofil_t *prof -- pointer to array of profile buffers.
.LP
int profcnt -- number of profile buffers in pointed to by prof.
.LP
int EventSet -- The PAPI EventSet to profile when it is started.
.LP
int EventNum -- Number of the Event in the EventSet to profile.
.LP
int threshold -- threshold value for the Event triggers the handler.
.LP
int flags -- flags to control the behavior of PAPI_sprofil(). 
.LP
.SH DESCRIPTION

.SH RETURN VALUES
On success, this function returns
.I "PAPI_OK."
On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOMEM"
Insufficient memory to complete the operation.
.TP
.B "PAPI_ENOEVST"
The EventSet specified does not exist.
.TP
.B "PAPI_EISRUN"
The EventSet is currently counting events.
.TP
.B "PAPI_ECNFLCT"
The underlying counter hardware can not count this event and other events
in the EventSet simultaneously.
.TP
.B "PAPI_NOEVNT"
The PAPI preset is not available on the underlying hardware. 

.SH EXAMPLES
.LP

  int EventSet = PAPI_NULL;
  unsigned int native = 0x0;
.LP
	
  if (PAPI_create_eventset(&EventSet) != PAPI_OK)
    handle_error(1);

  /* Add Total Instructions Executed to our EventSet */

  if (PAPI_add_event(&EventSet, PAPI_TOT_INS) != PAPI_OK)
    handle_error(1);

  /* Add native event (0xc1 on hardware counter 1) */

  native = (0xc1 << 8) | 1;
  if (PAPI_add_event(&EventSet, native) != PAPI_OK)
    handle_error(1);

  /* Start counting */

  if (PAPI_start(EventSet) != PAPI_OK)
    handle_error(1);

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_preset "(3), "
.BR PAPI_set_opt "(3), " PAPI_start "(3), " PAPI_rem_event "(3), " 
.BR PAPI_rem_events "(3), " PAPI_query "(3), "
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi

