.TH "PAPIF_get_dmem_info" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_get_dmem_info \- 
.PP
get information about the dynamic memory usage of the current program  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include fpapi'\&.h 
.br
 PAPIF_get_dmem_info( C_INT EventSet, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_get_dmem_info\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
