.TH "PAPIF_register_thread" 3 "Fri Feb 22 2019" "Version 5.7.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_register_thread \- 
.PP
Notify PAPI that a thread has 'appeared'\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
 \fBPAPIF_register_thread( C_INT check )\fP
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBPAPI_register_thread\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
