.\" $Id$
.TH PAPI_list_events 3 "October, 2000" "PAPI Programmer's Manual" "PAPI"

.SH NAME
PAPI_list_events \- list the events defined in an event set
.SH SYNOPSIS
.B #include <papi.h>

.nf
.BI "int PAPI_list_events(int " EventSet ", int *" Events ", int *" number ");"
.if

.SH DESCRIPTION
.LP
.B PAPI_list_events(\|)
decomposes an event set into the hardware events it contains.
.LP
.I EventSet 
-- a reference to an EventSetInfo structure
.LP
.I *Events 
-- an array of codes for events, such as PAPI_INT_INS. No more than 
.I *number
codes will be stored into the array.
.LP
.I *number 
-- On input the variable determines the size of the 
.I Events
array. On output the variable contains the number of counters in the
event set.
.LP
Note that if the given array
.I *Events
is too short to hold all the counters in the event set the
.I *number
variable will be larger than the actually stored number of counter codes.

.SH RETURN VALUES
The return value is an integer that indicates whether the call
succeeded (PAPI_OK) or failed (not PAPI_OK). 
.LP

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOEVST"
The EventSet specified does not exist.
.TP
.B "PAPI_ENOTPRESET"
The hardware event specified is not a PAPI preset for this architecture. 

.SH EXAMPLES

.nf
.if t .ft CW
  int EventCode, EventSet = PAPI_NULL;
  char EventCodeStr[PAPI_MAX_STR_LEN];
  char EventDescr[PAPI_MAX_STR_LEN];
	
  /* Convert to integer */

  if (PAPI_event_name_to_code("PAPI_TOT_INS",&EventCode) != PAPI_OK)
    handle_error(1);

  /* Query Total Instructions Executed to our EventSet */

  if (PAPI_query(EventCode) != PAPI_OK)
    handle_error(1);

  /* Describe event from EventCode */

  if (PAPI_describe_event(EventCodeStr,&EventCode,EventDescr) != PAPI_OK)
    handle_error(1);

  /* Create the EventSet */

  if (PAPI_create_eventset(&EventSet) != PAPI_OK)
    handle_error(1);

  /* Add Total Instructions Executed to our EventSet */

  if (PAPI_add_event(&EventSet, EventCode) != PAPI_OK)
    handle_error(1);
.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_preset "(3), "
.BR PAPI_set_opt "(3), " PAPI_start "(3), " PAPI_rem_event "(3), " 
.BR PAPI_rem_events "(3), " PAPI_query "(3), "
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi
