.\" @(#)$Id$
.TH PAPI_profil 3 "1 June 2000"
.SH NAME
PAPI_profil \- set values in the EventSetProfileInfo_t strct.
.LP
.SH SYNOPSIS
.LP
int PAPI_sprofil (prof, profcnt, EventSet, EventNum, threshold, flags)
.LP
PAPI_sprofil_t *prof -- pointer to array of profile buffers.
.LP
int profcnt -- number of profile buffers in pointed to by prof.
.LP
int EventSet -- The PAPI EventSet to profile when it is started.
.LP
int EventNum -- Number of the Event in the EventSet to profile.
.LP
int threshold -- threshold value for the Event triggers the handler.
.LP
int flags -- flags to control the behavior of PAPI_sprofil(). 
.LP
.SH DESCRIPTION
.LP
.B PAPI_sprofil(\|)
.LP
.SH RETURN VALUES
.LP
.SH SEE ALSO
.LP
.SH BUGS
.LP
