.\" @(#).B PAPI_help    0.10 99/07/28 CHD; from S5
.TH PAPI_help 0 "28 July 1999"
.SH NAME
PAPI_help \- List of all functions in PerfAPI Library
.SH PerfAPI FUNCTION List 
.nf 
.B PAPI_accum
.B PAPI_add_event
.B PAPI_add_events
.B PAPI_add_pevent
.B PAPI_cleanup
.B PAPI_describe_event
.B PAPI_get_opt
.B PAPI_help
.B PAPI_init
.B PAPI_list_events
.B PAPI_mytest
.B PAPI_num_events
.B PAPI_overflow
.B PAPI_perror
.B PAPI_profil
.B PAPI_read
.B PAPI_read_counters
.B PAPI_rem_event
.B PAPI_rem_events
.B PAPI_reset
.B PAPI_set_domain
.B PAPI_set_granularity
.B PAPI_set_opt
.B PAPI_shutdown
.B PAPI_start
.B PAPI_start_counters
.B PAPI_state
.B PAPI_stop
.B PAPI_stop_counters
.B PAPI_write
.fi
.LP
.SH SEE ALSO
.nf 
.B The PerfAPI Draft: http://icl.cs.utk.edu/projects/papi/api/ 
.B The PerfAPI Draft: 
.B \thttp://icl.cs.utk.edu/projects/papi/api/ 
.fi
.SH BUGS
.LP
Please contact us if this list is in error or if anything on
any PerfAPI Manpage is in error or unclear.
.LP
The PerfAPI email address is: ptools-perfapi@ptools.org

