.TH "PAPI_mh_tlb_info_t" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_mh_tlb_info_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "int \fBnum_entries\fP"
.br
.ti -1c
.RI "int \fBpage_size\fP"
.br
.ti -1c
.RI "int \fBassociativity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Field Documentation"
.PP 
.SS "int \fBPAPI_mh_tlb_info_t::type\fP"Empty, instr, data, vector, unified 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
