.\" $Id$
.TH PAPI_query_event 3 "October, 2000" "" "PAPI"

.SH NAME
PAPI_query_event \- query if PAPI event exists

.SH SYNOPSIS
.B #include <papi.h>

.BI "int PAPI_query_event (int " EventCode ");"

.SH DESCRIPTION
.B "PAPI_query_event"
asks the hardware if the PAPI Preset event can be counted on this
architecture. If the event CAN be counted, the function returns PAPI_OK. 
If the event CANNOT be counted, the function returns an error code. 
On some platforms, this function can be used to check the syntax of
a native event. 

.SH RETURN VALUES
On success, this function returns
.I "PAPI_OK."
On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOMEM"
Insufficient memory to complete the operation.
.TP
.B "PAPI_ENOEVST"
The EventSet specified does not exist.
.TP
.B "PAPI_EISRUN"
The EventSet is currently counting events.
.TP
.B "PAPI_ECNFLCT"
The underlying counter hardware can not count this event and other events
in the EventSet simultaneously.
.TP
.B "PAPI_NOEVNT"
The PAPI preset is not available on the underlying hardware. 

.SH EXAMPLES
.LP
.nf
.if t .ft CW
int EventSet = PAPI_NULL;
unsigned int native = 0x0;
int retval;

/* Initialize the library */

retval = PAPI_library_init(PAPI_VER_CURRENT);

if (retval != PAPI_VER_CURRENT) {
  fprintf(stderr,"PAPI library init error!\n");
  exit(1); }
	
/* Create the event set */

if (PAPI_create_eventset(&EventSet) != PAPI_OK)
  handle_error(1);

/* Check if the event PAPI_TOT_INS or
   Total Instructions Executed exists */

if (PAPI_query_event(PAPI_TOT_INS) != PAPI_OK) {
  fprintf(stderr,"No instruction counter? How lame.\n");
  exit(1);
  }
	
/* Add the event PAPI_TOT_INS or
   Total Instructions Executed to the EventSet */

if (PAPI_add_event(&EventSet, PAPI_TOT_INS) != PAPI_OK)
  handle_error(1);

/* Add native event (0xc1 on hardware counter 1) */

native = (0xc1 << 8) | 1;
if (PAPI_add_event(&EventSet, native) != PAPI_OK)
  handle_error(1);

/* Start counting */

if (PAPI_start(EventSet) != PAPI_OK)
  handle_error(1);
.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_preset "(3), " PAPI_native "(3), "
.BR PAPI_set_opt "(3), " PAPI_start "(3), " PAPI_rem_event "(3), " 
.BR PAPI_rem_events "(3), " PAPI_query "(3), "
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The\ PAPI\ Web\ Site: 
.B http://icl.cs.utk.edu/projects/papi

