.TH "PAPI_num_hwctrs" 3 "Wed Nov 2 2022" "Version 6.0.0.1" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_num_hwctrs \- Return the number of hardware counters on the cpu\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBSee also\fP
.RS 4
\fBPAPI_num_cmp_hwctrs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
