.\" @(#)PAPI_accum    0.10 99/07/28 CHD; from S5
.TH PAPI_accum 0 "28 July 1999"
.SH NAME
PAPI_accum \- start counting events contained in an EventSet
.SH SYNOPSIS
.LP
int PAPI_accum (int EventSet, unsigned long long *values)
.LP
int EventSet --  a reference to an EventSetInfo structure
.LP
unsigned long long *values -- array to contain counts
.LP
.SH DESCRIPTION
.LP
.B PAPI_accum(\|)
This function accumulates the running or stopped counters in EventSet
into the values array.  In addition, it re-initializes the internal 
counters to zero.
.LP
The return value is an integer that indicates whether the call
succeeded (PAPI_OK) or failed (not PAPI_OK).  
.LP
.SH CROSS-REFERENCE WITH OTHER PerfAPI FUNCTIONS
.nf
.B  \t
.B  PAPI_accum may be called by:
.B  \t
.B  \tthe user application program
.fi
.nf
.B  \t
.B  PAPI_accum contains calls to:
.B  \t
.B  \tlookup_EventSet 
.B  \thandle_error
.B  \t_papi_hwd_read ( a substrate function )
.B  \t_papi_hwd_reset ( a substrate function )
.fi
.LP
.SH SEE ALSO
.nf 
.B The PerfAPI Draft: 
.B \thttp://icl.cs.utk.edu/projects/papi/api/ 
.SH BUGS
.LP
This function has no known bugs.
