.TH "PAPI_get_event_component" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_get_event_component \- return component an event belongs to  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBReturn values\fP
.RS 4
\fIENOCMP\fP component does not exist
.RE
.PP
\fBParameters\fP
.RS 4
\fIEventCode\fP EventCode for which we want to know the component index 
.RE
.PP
\fBExamples:\fP
.RS 4

.PP
.nf
int cidx,eventcode;
cidx = PAPI_get_event_component(eventcode);

.fi
.PP
 \fBPAPI_get_event_component()\fP returns the component an event belongs to\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_get_event_info\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
