.TH "PAPI_num_hwctrs" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_num_hwctrs \- 
.PP
Return the number of hardware counters on the cpu'\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBDeprecated\fP
.RS 4
This is included to preserve backwards compatibility'\&. Use \fBPAPI_num_cmp_hwctrs()\fP instead'\&.
.RE
.PP
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_num_cmp_hwctrs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
