.\" @(#)PAPI_rem_event    0.10 99/07/28 CHD; from S5
.TH PAPI_rem_event 0 "28 July 1999"
.SH NAME
PAPI_rem_event \- remove one Event from an EventSet
.SH SYNOPSIS
.LP
int PAPI_rem_event (int EventSet, int Event)
.LP
int EventSet -- a reference to an EventSetInfo structure
.LP
int Event -- code for an event, such as PAPI_INT_INS
.LP
.SH DESCRIPTION
.LP
.B PAPI_rem_event(\|)
This function removes the hardware counter Event from EventSet.
.LP
The return value is an integer that indicates whether the call
succeeded (PAPI_OK) or failed (not PAPI_OK).  
.LP
.SH CROSS-REFERENCE WITH OTHER PerfAPI FUNCTIONS
.nf
.B  \t
.B  PAPI_rem_event may be called by:
.B  \t
.B  \tthe user application program
.B  \tPAPI_rem_events 
.fi
.nf
.B  \t
.B  PAPI_rem_event contains calls to:
.B  \t
.B  \tlookup_EventSet 
.B  \thandle_error
.B  \tremove_EventSet
.B  \t_papi_hwd_rem_event ( a substrate function )
.fi
.LP
.SH SEE ALSO
.nf 
.B The PerfAPI Draft: 
.B \thttp://icl.cs.utk.edu/projects/papi/api/ 
.fi
.SH BUGS
.LP
This function has no known bugs.
