.TH "PAPI_option_t" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_option_t \- A pointer to the following is passed to PAPI_set/get_opt().  

.PP
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "PAPI_preload_info_t \fBpreload\fP"
.br
.ti -1c
.RI "PAPI_debug_option_t \fBdebug\fP"
.br
.ti -1c
.RI "PAPI_inherit_option_t \fBinherit\fP"
.br
.ti -1c
.RI "PAPI_granularity_option_t \fBgranularity\fP"
.br
.ti -1c
.RI "PAPI_granularity_option_t \fBdefgranularity\fP"
.br
.ti -1c
.RI "PAPI_domain_option_t \fBdomain\fP"
.br
.ti -1c
.RI "PAPI_domain_option_t \fBdefdomain\fP"
.br
.ti -1c
.RI "PAPI_attach_option_t \fBattach\fP"
.br
.ti -1c
.RI "PAPI_cpu_option_t \fBcpu\fP"
.br
.ti -1c
.RI "PAPI_multiplex_option_t \fBmultiplex\fP"
.br
.ti -1c
.RI "PAPI_itimer_option_t \fBitimer\fP"
.br
.ti -1c
.RI "\fBPAPI_hw_info_t\fP * \fBhw_info\fP"
.br
.ti -1c
.RI "PAPI_shlib_info_t * \fBshlib_info\fP"
.br
.ti -1c
.RI "\fBPAPI_exe_info_t\fP * \fBexe_info\fP"
.br
.ti -1c
.RI "PAPI_component_info_t * \fBcmp_info\fP"
.br
.ti -1c
.RI "\fBPAPI_addr_range_option_t\fP \fBaddr\fP"
.br
.ti -1c
.RI "\fBPAPI_user_defined_events_file_t\fP \fBevents_file\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
