.\" $Id$
.TH PAPI_register_thread 3 "November, 2003" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_register_thread \- Notify PAPI of the existence of a new thread

.SH SYNOPSIS
.nf
.B #include <papi.h>
.BI "int PAPI_register_thread (void);"
.fi

.SH DESCRIPTION
When a new thread is created of which PAPI needs to be aware, a call to 
this function will register it. PAPI looks it up in its internal thread list, 
and adds it if it is not found. There is no Fortran eqivalent to this call.

.SH ARGUMENTS

.SH RETURN VALUES
On success, this function returns
.B "PAPI_OK."
 On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_ENOMEM"
Space could not be allocated to store the new thread information.

.SH EXAMPLES

.SH AUTHORS
The PAPI Team. See them at the PAPI Web Site: 
http://icl.cs.utk.edu/projects/papi

.SH SEE ALSO
.BR PAPI_thread_init "(3), "
.BR PAPI_thread_id "(3), "
.BR PAPI_get_thr_specific "(3), "
.BR PAPI_set_thr_specific "(3), "
.BR PAPI_register_thread "(3)" 

