.TH "PAPI_exe_info_t" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_exe_info_t \- 
.PP
get the executable's info  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBfullname\fP [1024]"
.br
.ti -1c
.RI "\fBPAPI_address_map_t\fP \fBaddress_info\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBPAPI_address_map_t\fP \fBPAPI_exe_info_t::address_info\fP"executable's address space info 
.SS "char \fBPAPI_exe_info_t::fullname\fP[1024]"path + name 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
