.TH "PAPI Fortran API" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI Fortran API \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPAPIF_accum\fP"
.br
.RI "\fIaccumulate and reset counters in an event set \fP"
.ti -1c
.RI "class \fBPAPIF_add_event\fP"
.br
.RI "\fIadd PAPI preset or native hardware event to an event set \fP"
.ti -1c
.RI "class \fBPAPIF_add_events\fP"
.br
.RI "\fIadd multiple PAPI presets or native hardware events to an event set \fP"
.ti -1c
.RI "class \fBPAPIF_cleanup_eventset\fP"
.br
.RI "\fIempty and destroy an EventSet \fP"
.ti -1c
.RI "class \fBPAPIF_create_eventset\fP"
.br
.RI "\fIcreate a new empty PAPI EventSet \fP"
.ti -1c
.RI "class \fBPAPIF_assign_eventset_component\fP"
.br
.RI "\fIassign a component index to an existing but empty EventSet \fP"
.ti -1c
.RI "class \fBPAPIF_destroy_eventset\fP"
.br
.RI "\fIempty and destroy an EventSet \fP"
.ti -1c
.RI "class \fBPAPIF_get_dmem_info\fP"
.br
.RI "\fIget information about the dynamic memory usage of the current program \fP"
.ti -1c
.RI "class \fBPAPIF_get_exe_info\fP"
.br
.RI "\fIget information about the dynamic memory usage of the current program \fP"
.ti -1c
.RI "class \fBPAPIF_get_hardware_info\fP"
.br
.RI "\fIget information about the system hardware \fP"
.ti -1c
.RI "class \fBPAPIF_num_hwctrs\fP"
.br
.RI "\fIReturn the number of hardware counters on the cpu. \fP"
.ti -1c
.RI "class \fBPAPIF_num_cmp_hwctrs\fP"
.br
.RI "\fIReturn the number of hardware counters on the specified component. \fP"
.ti -1c
.RI "class \fBPAPIF_get_real_cyc\fP"
.br
.RI "\fIGet real time counter value in clock cycles. \fP"
.ti -1c
.RI "class \fBPAPIF_get_real_usec\fP"
.br
.RI "\fIGet real time counter value in microseconds. \fP"
.ti -1c
.RI "class \fBPAPIF_get_real_nsec\fP"
.br
.RI "\fIGet real time counter value in nanoseconds. \fP"
.ti -1c
.RI "class \fBPAPIF_get_virt_cyc\fP"
.br
.RI "\fIGet virtual time counter value in clock cycles. \fP"
.ti -1c
.RI "class \fBPAPIF_get_virt_usec\fP"
.br
.RI "\fIGet virtual time counter value in microseconds. \fP"
.ti -1c
.RI "class \fBPAPIF_is_initialized\fP"
.br
.RI "\fICheck for initialization. \fP"
.ti -1c
.RI "class \fBPAPIF_library_init\fP"
.br
.RI "\fIInitialize the PAPI library. \fP"
.ti -1c
.RI "class \fBPAPIF_thread_id\fP"
.br
.RI "\fIGet the thread identifier of the current thread. \fP"
.ti -1c
.RI "class \fBPAPIF_register_thread\fP"
.br
.RI "\fINotify PAPI that a thread has 'appeared'. \fP"
.ti -1c
.RI "class \fBPAPIF_unregister_thread\fP"
.br
.RI "\fINotify PAPI that a thread has 'disappeared'. \fP"
.ti -1c
.RI "class \fBPAPIF_thread_init\fP"
.br
.RI "\fIInitialize thread support in the PAPI library. \fP"
.ti -1c
.RI "class \fBPAPI_list_events\fP"
.br
.RI "\fIlist the events in an event set \fP"
.ti -1c
.RI "class \fBPAPIF_multiplex_init\fP"
.br
.RI "\fIInitialize multiplex support in the PAPI library. \fP"
.ti -1c
.RI "class \fBPAPIF_get_multiplex\fP"
.br
.RI "\fIGet the multiplexing status of specified event set. \fP"
.ti -1c
.RI "class \fBPAPIF_set_multiplex\fP"
.br
.RI "\fIConvert a standard event set to a multiplexed event set. \fP"
.ti -1c
.RI "class \fBPAPIF_perror\fP"
.br
.RI "\fIConvert PAPI error codes to strings, and print error message to stderr. \fP"
.ti -1c
.RI "class \fBPAPIF_query_event\fP"
.br
.RI "\fIQuery if PAPI event exists. \fP"
.ti -1c
.RI "class \fBPAPIF_get_event_info\fP"
.br
.RI "\fIGet the event's name and description info. \fP"
.ti -1c
.RI "class \fBPAPIF_event_code_to_name\fP"
.br
.RI "\fIConvert a numeric hardware event code to a name. \fP"
.ti -1c
.RI "class \fBPAPIF_event_name_to_code\fP"
.br
.RI "\fIConvert a name to a numeric hardware event code. \fP"
.ti -1c
.RI "class \fBPAPIF_num_events\fP"
.br
.RI "\fIEnumerate PAPI preset or native events. \fP"
.ti -1c
.RI "class \fBPAPIF_enum_event\fP"
.br
.RI "\fIReturn the number of events in an event set. \fP"
.ti -1c
.RI "class \fBPAPIF_read\fP"
.br
.RI "\fIRead hardware counters from an event set. \fP"
.ti -1c
.RI "class \fBPAPIF_read_ts\fP"
.br
.RI "\fIRead hardware counters with a timestamp. \fP"
.ti -1c
.RI "class \fBPAPIF_remove_event\fP"
.br
.RI "\fIRemove a hardware event from a PAPI event set. \fP"
.ti -1c
.RI "class \fBPAPIF_remove_events\fP"
.br
.RI "\fIRemove an array of hardware event codes from a PAPI event set. \fP"
.ti -1c
.RI "class \fBPAPIF_reset\fP"
.br
.RI "\fIReset the hardware event counts in an event set. \fP"
.ti -1c
.RI "class \fBPAPIF_set_debug\fP"
.br
.RI "\fISet the current debug level for error output from PAPI. \fP"
.ti -1c
.RI "class \fBPAPIF_set_domain\fP"
.br
.RI "\fISet the default counting domain for new event sets bound to the cpu component. \fP"
.ti -1c
.RI "class \fBPAPIF_set_cmp_domain\fP"
.br
.RI "\fISet the default counting domain for new event sets bound to the specified component. \fP"
.ti -1c
.RI "class \fBPAPIF_set_granularity\fP"
.br
.RI "\fISet the default counting granularity for eventsets bound to the cpu component. \fP"
.ti -1c
.RI "class \fBPAPIF_set_cmp_granularity\fP"
.br
.RI "\fISet the default counting granularity for eventsets bound to the specified component. \fP"
.ti -1c
.RI "class \fBPAPIF_shutdown\fP"
.br
.RI "\fIfinish using PAPI and free all related resources. \fP"
.ti -1c
.RI "class \fBPAPIF_start\fP"
.br
.RI "\fIStart counting hardware events in an event set. \fP"
.ti -1c
.RI "class \fBPAPIF_state\fP"
.br
.RI "\fIReturn the counting state of an EventSet. \fP"
.ti -1c
.RI "class \fBPAPIF_stop\fP"
.br
.RI "\fIStop counting hardware events in an EventSet. \fP"
.ti -1c
.RI "class \fBPAPIF_write\fP"
.br
.RI "\fIWrite counter values into counters. \fP"
.ti -1c
.RI "class \fBPAPIF_lock\fP"
.br
.RI "\fILock one of two mutex variables defined in \fBpapi.h\fP. \fP"
.ti -1c
.RI "class \fBPAPIF_unlock\fP"
.br
.RI "\fIUnlock one of the mutex variables defined in \fBpapi.h\fP. \fP"
.ti -1c
.RI "class \fBPAPIF_start_counters\fP"
.br
.RI "\fIStart counting hardware events. \fP"
.ti -1c
.RI "class \fBPAPI_read_counters\fP"
.br
.RI "\fIRead and reset counters. \fP"
.ti -1c
.RI "class \fBPAPIF_stop_counters\fP"
.br
.RI "\fIStop counting hardware events and reset values to zero. \fP"
.ti -1c
.RI "class \fBPAPIF_accum_counters\fP"
.br
.RI "\fIAccumulate and reset counters. \fP"
.ti -1c
.RI "class \fBPAPIF_num_counters\fP"
.br
.RI "\fIGet the number of hardware counters available on the system. \fP"
.ti -1c
.RI "class \fBPAPIF_ipc\fP"
.br
.RI "\fIGet instructions per cycle, real and processor time. \fP"
.ti -1c
.RI "class \fBPAPIF_flips\fP"
.br
.RI "\fISimplified call to get Mflips/s (floating point instruction rate), real and processor time. \fP"
.ti -1c
.RI "class \fBPAPIF_flops\fP"
.br
.RI "\fISimplified call to get Mflops/s (floating point instruction rate), real and processor time. \fP"
.ti -1c
.RI "class \fBPAPIF_get_clockrate\fP"
.br
.RI "\fIGet the clockrate in MHz for the current cpu. \fP"
.ti -1c
.RI "class \fBPAPIF_get_preload\fP"
.br
.RI "\fIGet the LD_PRELOAD environment variable. \fP"
.ti -1c
.RI "class \fBPAPIF_get_granularity\fP"
.br
.RI "\fIGet the granularity setting for the specified EventSet. \fP"
.ti -1c
.RI "class \fBPAPIF_get_domain\fP"
.br
.RI "\fIGet the domain setting for the specified EventSet. \fP"
.ti -1c
.RI "class \fBPAPIF_set_event_domain\fP"
.br
.RI "\fISet the default counting domain for specified EventSet. \fP"
.ti -1c
.RI "class \fBPAPIF_set_inherit\fP"
.br
.RI "\fITurn on inheriting of counts from daughter to parent process. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
