.\" $Id$
.TH PAPI_set_granularity "October, 2000" "" "PAPI"

.SH NAME
PAPI_set_granularity \- set the execution domain in which events are counted

.SH SYNOPSIS
.B #include <papi.h>

.BI "int\ PAPI_set_granularity(int " granularity );

.SH DESCRIPTION
This function is currently unimplemented.

.SH RETURN VALUES
.SH ERRORS
.SH EXAMPLES

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_set_domain "(3), " PAPI_set_opt "(3), " PAPI_get_opt "(3), "
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi
