.\" $Id$
.TH PAPI_shutdown 3 "October, 2000" "" "PAPI"

.SH NAME
PAPI_shutdown \- finish using PAPI and free all related resources

.SH SYNOPSIS
.LP
void PAPI_shutdown (void)

.LP
.SH DESCRIPTION
.LP
.B PAPI_shutdown(\|)
This is an exit function used by the PAPI Library to free resources
and shut down when  certain error conditions arise.  This call is
not necessary, but allows the user the capability to free memory 
and resources used by the PAPI Library.

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi

