.TH "PAPIF_num_counters" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_num_counters \- 
.PP
Get the number of hardware counters available on the system.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_num_counters( C_INT numevents )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_num_counters\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
