.\" $Id$
.TH PAPI_set_debug 3 "November, 2003" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_set_debug \- set the current debug level for PAPI

.SH SYNOPSIS
.B C Interface
.nf
.B #include <papi.h>
.BI "int PAPI_set_debug(int " debuglevel ");"
.fi
.B Fortran Interface
.nf
.B #include "fpapi.h"
.BI PAPIF_set_debug(C_INT\  debug,\  C_INT\  check )
.fi

.SH DESCRIPTION
.B "PAPI_set_debug" 
sets the default debug level for the PAPI library.

.SH ARGUMENTS
.I "debuglevel"
-- one of the constants shown in the table below and defined 
in the papi.h header file.
The current debug level is internally stored in the PAPI library and
is used by the default internal PAPI error handler subroutine. 
The error handler is called by library routines
on the occurence of recoverable errors.
The default PAPI error handler handles the possible debug levels 
shown in the table below.
.TS
allbox tab($);
lB l.
PAPI_QUIET$Quietly handle errors
PAPI_VERB_ECONT$Print error message and continue
PAPI_VERB_ESTOP$Print error message and exit
.TE

.SH RETURN VALUES
On success, this function returns
.B "PAPI_OK."
 On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.

.SH AUTHORS
The PAPI Team. See them at the PAPI Web Site: 
http://icl.cs.utk.edu/projects/papi

.SH BUGS
It is currently not possible for the user to substitute default error handler.
 This function is also only activated when PAPI is compiled with
debugging enabled.

.SH SEE ALSO
.BR PAPI_set_opt "(3)" 
