.\" $Id$
.TH PAPI_get_dmem_info 3 "November, 2003" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_get_dmem_info \- get information about the dynamic memory usage of the current program

.SH SYNOPSIS
.B C Interface
.nf
.B #include <papi.h>
.BI " long PAPI_get_dmem_info(int option);"
.fi

.SH DESCRIPTION
In C, this function returns a pointer to a structure containing information
about the memory hardware on which the program runs. There is no Fortran equivalent call.

.SH NOTE
The exact calling syntax and returned information for this function is likely to change.

.SH ARGUMENTS
.LP
.I option
--  Can currently be one of the following: 
.B PAPI_GET_SIZE 
(Size of process image in pages),
.B PAPI_GET_RESSIZE 
(Resident set size in pages),
.B PAPI_GET_PAGESIZE 
(Pagesize in bytes).

.SH RETURN VALUES
On success, this function returns the positive value of the specified option. 
On error a negative error value is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
The value of 
.I option 
is invalid.
.TP
.B "PAPI_SYS"
A system error occured.

.SH EXAMPLE
.LP
.nf
.if t .ft CW
   int retval;

   if (PAPI_library_init(PAPI_VER_CURRENT) != PAPI_VER_CURRENT)
   exit(1);

   retval = PAPI_library_init(PAPI_VER_CURRENT);
   if (retval != PAPI_VER_CURRENT)
      handle_error(retval);

   printf("Resident Size in Pages: %ld  Size in Pages: %ld  Pagesize in bytes: %ld\n",
           PAPI_get_dmem_info(PAPI_GET_RESSIZE),
           PAPI_get_dmem_info(PAPI_GET_SIZE),
           PAPI_get_dmem_info(PAPI_GET_PAGESIZE));
.if t .ft P
.fi

.SH AUTHORS
The PAPI Team. See them at the PAPI Web Site: 
http://icl.cs.utk.edu/projects/papi

.SH BUGS
If called before 
.B PAPI_library_init()
the behavior of the routine is undefined.

.SH SEE ALSO
.BR PAPI_library_init "(3), "
.BR PAPI_get_opt "(3), " 
.BR PAPI_get_hardware_info "(3), "
.BR PAPI_get_executable_info "(3)"
