.TH "PAPIF_add_event" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_add_event \- 
.PP
add PAPI preset or native hardware event to an event set  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_add_event( C_INT EventSet, C_INT EventCode, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_add_event\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
