.TH "PAPIF_reset" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_reset \- 
.PP
Reset the hardware event counts in an event set.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Prototype:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_reset( C_INT EventSet, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_reset\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
