.TH "PAPIF_set_debug" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_set_debug \- 
.PP
Set the current debug level for error output from PAPI.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Prototype:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_set_debug( C_INT level, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_set_debug\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
