.TH "PAPIF_thread_init" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_thread_init \- 
.PP
Initialize thread support in the PAPI library.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_thread_init( C_INT FUNCTION  handle,  C_INT  check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_thread_init\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
