.TH "PAPI Data Structures" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI Data Structures \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBPAPI_all_thr_spec_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_sprofil_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_itimer_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_inherit_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_domain_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_granularity_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_preload_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_component_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_mpx_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_debug_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_address_map_t\fP"
.br
.RI "\fIget the executable's address space info \fP"
.ti -1c
.RI "struct \fBPAPI_exe_info_t\fP"
.br
.RI "\fIget the executable's info \fP"
.ti -1c
.RI "struct \fBPAPI_shlib_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_mh_tlb_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_mh_cache_info_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_mh_level_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_mh_info_t\fP"
.br
.RI "\fImh for mem hierarchy maybe? \fP"
.ti -1c
.RI "struct \fBPAPI_hw_info_t\fP"
.br
.RI "\fIHardware info structure. \fP"
.ti -1c
.RI "struct \fBPAPI_attach_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_cpu_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_multiplex_option_t\fP"
.br
.ti -1c
.RI "struct \fBPAPI_addr_range_option_t\fP"
.br
.RI "\fIaddress range specification for range restricted counting if both are zero, range is disabled \fP"
.ti -1c
.RI "struct \fBPAPI_dmem_info_t\fP"
.br
.RI "\fIA pointer to the following is passed to \fBPAPI_get_dmem_info()\fP \fP"
.ti -1c
.RI "struct \fBPAPI_event_info_t\fP"
.br
.RI "\fIThis structure is the event information that is exposed to the user through the API. \fP"
.ti -1c
.RI "union \fBPAPI_option_t\fP"
.br
.RI "\fIA pointer to the following is passed to PAPI_set/get_opt() \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
