.TH "PAPIF_register_thread" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_register_thread \- 
.PP
Notify PAPI that a thread has 'appeared'.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_register_thread( C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_register_thread\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
