.TH "PAPI_destroy_eventset" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPI_destroy_eventset \- Empty and destroy an EventSet\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBC Interface:\fP
.RS 4
#include <\fBpapi\&.h\fP> 
.br
 int \fBPAPI_destroy_eventset( int * EventSet )\fP;
.RE
.PP
\fBPAPI_destroy_eventset\fP deallocates the memory associated with an empty PAPI EventSet\&.
.PP
\fBParameters\fP
.RS 4
\fI*EventSet\fP A pointer to the integer handle for a PAPI event set as created by \fBPAPI_create_eventset\fP\&. The value pointed to by EventSet is then set to PAPI_NULL on success\&.
.RE
.PP
\fBReturn values\fP
.RS 4
\fIPAPI_EINVAL\fP One or more of the arguments is invalid\&. Attempting to destroy a non-empty event set or passing in a null pointer to be destroyed\&. 
.br
\fIPAPI_ENOEVST\fP The EventSet specified does not exist\&. 
.br
\fIPAPI_EISRUN\fP The EventSet is currently counting events\&. 
.br
\fIPAPI_EBUG\fP Internal error, send mail to ptools-perfapi@icl.utk.edu and complain\&.
.RE
.PP
\fBExamples:\fP
.RS 4

.PP
.nf
// Free all memory and data structures, EventSet must be empty\&.
if ( PAPI_destroy_eventset( &EventSet ) != PAPI_OK )
handle_error( 1 );

.fi
.PP
.RE
.PP
.PP
\fBSee also\fP
.RS 4
\fBPAPI_profil\fP 
.br
 \fBPAPI_create_eventset\fP 
.br
 \fBPAPI_add_event\fP 
.br
 \fBPAPI_stop\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
