.TH "PAPIF_num_hwctrs" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_num_hwctrs \- 
.PP
Return the number of hardware counters on the cpu'\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include fpapi'\&.h 
.br
 PAPIF_num_hwctrs( C_INT num )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_num_hwctrs\fP 
.PP
\fBPAPI_num_cmp_hwctrs\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
