.\" $Id$
.TH PAPI_stop_counters 3 "September, 2002" "PAPI Programmer's Reference" "PAPI"

.SH NAME
PAPI_stop_counters \- PAPI High Level: stop counting hardware events

.SH SYNOPSIS
.B C Interface
.nf
.B #include <papi.h>
.BI "int\ PAPI_stop_counters(long_long *" values ", int " array_len ");"
.fi
.B Fortran Interface
.nf
.BI PAPIF_stop_counters(C_LONG_LONG(*)\  values,\  C_INT\  array_len,\  C_INT\  check )
.B #include "fpapi.h"
.fi

.SH DESCRIPTION
.B PAPI_stop_counters(\|)
.LP
This function stops the counters and returns their values. The
counters must have been started by a previous call to
PAPI_start_counters().
.SH ARGUMENTS
.I *values
-- an array where to put the counter values
.LP
.I array_len 
-- the number of items in the *values array
.LP

.SH RETURN VALUES
On success, this function returns
.B "PAPI_OK."
 On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ENOTRUN"
The eventset is not started yet.

.SH EXAMPLES
.nf
.if t .ft CW
  int Events[2] = { PAPI_TOT_CYC, PAPI_TOT_INS };
  long_long values[2];
  int num_hwcntrs = 0;
	
  if ((num_hwcntrs = PAPI_num_counters()) < PAPI_OK)
    handle_error(1);

  if (num_hwcntrs > 2)
    num_hwcntrs = 2;

  /* Start counting events */

  if (PAPI_start_counters(Events, num_hwcntrs) != PAPI_OK)
    handle_error(1);

  your_slow_code();

  /* Stop counting events */

  if (PAPI_stop_counters(values, num_hwcntrs) != PAPI_OK)
    handle_error(1);
.if t .ft P
.fi

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_num_counters "(3),"
.BR PAPI_start_counters "(3),"
.BR PAPI_read_counters "(3),"
 The PAPI Web Site: 
http://icl.cs.utk.edu/projects/papi
