.TH "PAPIF_get_hardware_info" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_get_hardware_info \- get information about the system hardware  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
\fBPAPIF_get_hardware_info\fP( C_INT ncpu, C_INT nnodes, C_INT totalcpus,
.br
 C_INT vendor, C_STRING vendor_str, C_INT model, C_STRING model_str, 
.br
 C_FLOAT revision, C_FLOAT mhz )
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_get_hardware_info\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
