.TH "PAPIF_thread_id" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_thread_id \- 
.PP
Get the thread identifier of the current thread.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_thread_id( C_INT id )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_thread_id\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
