.TH "PAPIF_lock" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_lock \- Lock one of two mutex variables defined in \fBpapi\&.h\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
 \fBPAPIF_lock( C_INT lock )\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_lock\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
