.\" @(#)PAPI_init    0.10 99/07/28 CHD; from S5
.TH PAPI_init 0 "28 July 1999"
.LP
.SH NAME
PAPI_init \- start counting events contained in an EventSet
.SH SYNOPSIS
.LP
int PAPI_init (void)
.LP
.SH DESCRIPTION
.LP
.B PAPI_init(\|)
This function checks if the PAPI_EVENTSET_INFO structure has 
been initialized. If it has, the function returns PAPI_OK. 
If not, the function calls for initialization of the 
PAPI_EVENTSET_INFO structure and then returns PAPI_OK.
.LP
The return value is an integer that indicates whether the call
succeeded (PAPI_OK) or failed (not PAPI_OK).  
.LP
.SH CROSS-REFERENCE WITH OTHER PerfAPI FUNCTIONS
.nf
.B  \t
.B  PAPI_init may be called by:
.B  \t
.B  \tthe user application program
.B  \tPAPI_add_event
.B  \tPAPI_get_opt
.B  \tPAPI_add_pevent
.fi
.nf
.B  \t
.B  PAPI_init contains calls to:
.B  \t
.B  \tcheck_initialize 
.fi
.LP
.SH SEE ALSO
.nf 
.B The PerfAPI Draft: 
.B \thttp://icl.cs.utk.edu/projects/papi/api/ 
.fi
.SH BUGS
.LP
This function has no known bugs.

