.TH "PAPIF_event_name_to_code" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_event_name_to_code \- 
.PP
Convert a name to a numeric hardware event code.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include 'fpapi.h' 
.br
 PAPIF_event_name_to_code( C_STRING EventName, C_INT EventCode, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_event_name_to_code\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
