.TH "PAPIF_set_multiplex" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_set_multiplex \- 
.PP
Convert a standard event set to a multiplexed event set.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_set_multiplex( C_INT  EventSet,  C_INT  check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_set_multiplex\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
