.\" @(#)PAPI_library_init    0.10 00/05/17 CHD; from S5
.TH PAPI_library_init 0 "17 May 2000"
.SH NAME
PAPI_library_init \- Initializes the PAPI library 
.LP
.SH SYNOPSIS
.LP
int PAPI_library_init (int *EventSet)
.LP
.SH DESCRIPTION
.LP
.B PAPI_library_init(\|)
This function initializes the PAPI library and has to be called
before PAPI can be used.  Also PAPI_thread_init has to be called
before PAPI calls can be used in a user application.
.LP
.SH CROSS-REFERENCE WITH OTHER PerfAPI FUNCTIONS
.nf
.B  \t
.B  PAPI_library_init may be called by:
.B  \t
.B  \tthe user application program
.B  \tPAPI_start_counters
.B  \tPAPI_read_counters
.B  \tPAPI_stop_counters
.fi
.nf
.B  \t
.B  PAPI_library_init contains calls to:
.B  \t
.B  \t_papi_hwd_init_globabl 
.B  \t_papi_hwd_query
.B  \tallocate_eventset_map
.fi
.LP
.SH SEE ALSO
.nf 
.B The PerfAPI Draft: 
.B \thttp://icl.cs.utk.edu/projects/papi/api/ 
.SH BUGS
.LP
This function has no known bugs.
