.TH "PAPIF_lock" 3 "14 Sep 2016" "Version 5.5.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_lock \- 
.PP
Lock one of two mutex variables defined in \fBpapi.h\fP.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP.RS 4
#include 'fpapi.h' 
.br
 PAPIF_lock( C_INT lock )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_lock\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code.
