.TH "PAPIF_enum_event" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_enum_event \- Return the number of events in an event set\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
 \fBPAPIF_enum_event( C_INT  EventCode,  C_INT  modifier,  C_INT  check )\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_enum_event\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
