.TH "PAPIF_destroy_eventset" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_destroy_eventset \- 
.PP
empty and destroy an EventSet  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include fpapi'\&.h 
.br
 PAPIF_destroy_eventset( C_INT EventSet, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_destroy_eventset\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
