.TH "PAPIF_add_events" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_add_events \- add multiple PAPI presets or native hardware events to an event set  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.PP
\fBFortran Interface:\fP
.RS 4
#include 'fpapi\&.h' 
.br
\fBPAPIF_add_events( C_INT EventSet, C_INT(*) EventCodes, C_INT number, C_INT  check )\fP
.RE
.PP
\fBSee also\fP
.RS 4
\fBPAPI_add_events\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
