.TH "PAPIF_assign_eventset_component" 3 "Fri Aug 26 2011" "Version 4.1.4.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PAPIF_assign_eventset_component \- 
.PP
assign a component index to an existing but empty EventSet  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBFortran Interface:\fP
.RS 4
#include fpapi'\&.h 
.br
 PAPIF_assign_eventset_component( C_INT EventSet, C_INT EventSet, C_INT check )
.RE
.PP
\fBSee also:\fP
.RS 4
\fBPAPI_assign_eventset_component\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
