.\" $Id$
.TH PAPI 3 "October, 2000" "" "PAPI"

.SH NAME
PAPI \- Performance Application Programming Interface

.SH SYNOPSIS
High Level Functions \- Simple interface for single thread applications
.LP
.BR "PAPI_num_counters" (3), 
.BR "PAPI_read_counters" (3), 
.BR "PAPI_stop_counters" (3),
.BR "PAPI_start_counters" (3),

Low Level Functions \- Advanced interface for all applications and performance tools

.BR "PAPI_accum" (3),
.BR "PAPI_add_event" (3),
.BR "PAPI_add_events" (3),
.BR "PAPI_add_pevent" (3),
.BR "PAPI_cleanup_eventset" (3),
.BR "PAPI_create_eventset" (3),
.BR "PAPI_describe_event" (3),
.BR "PAPI_destroy_eventset" (3),
.BR "PAPI_event_code_to_name" (3),
.BR "PAPI_event_name_to_code" (3),
.BR "PAPI_get_executable_info" (3),
.BR "PAPI_get_hardware_info" (3),
.BR "PAPI_get_opt" (3),
.BR "PAPI_get_overflow_address" (3),
.BR "PAPI_get_real_cyc" (3),
.BR "PAPI_get_real_usec" (3),
.BR "PAPI_get_real_virt_cyc" (3),
.BR "PAPI_get_real_virt_usec" (3),
.BR "PAPI_library_init" (3),
.BR "PAPI_list_events" (3),
.BR "PAPI_lock" (3),
.BR "PAPI_overflow" (3),
.BR "PAPI_perror" (3),
.BR "PAPI_profil" (3),
.BR "PAPI_query_all_events_verbose" (3),
.BR "PAPI_query_event" (3),
.BR "PAPI_query_event_verbose" (3),
.BR "PAPI_read" (3),
.BR "PAPI_rem_event" (3),
.BR "PAPI_rem_events" (3),
.BR "PAPI_reset" (3),
.BR "PAPI_restore" (3),
.BR "PAPI_save" (3),
.BR "PAPI_set_debug" (3),
.BR "PAPI_set_domain" (3),
.BR "PAPI_set_granularity" (3),
.BR "PAPI_set_opt" (3),
.BR "PAPI_shutdown" (3),
.BR "PAPI_start" (3),
.BR "PAPI_state" (3),
.BR "PAPI_stop" (3),
.BR "PAPI_thread_init" (3), 
.BR "PAPI_unlock" (3),
.BR "PAPI_write" (3),

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This woeful excuse for a man page.

.SH SEE ALSO
The\ PAPI\ Web\ Site: 
.B http://icl.cs.utk.edu/projects/papi

