.\" $Id$
.TH PAPI_read "October, 2000" "" "PAPI"

.SH NAME
PAPI_read, PAPI_accum \- read, accumulate and reset hardware events from an EventSet

.SH SYNOPSIS

.SH RETURN VALUES
On success, this function returns
.I "PAPI_OK."
On error, a non-zero error code is returned.

.SH ERRORS
.TP
.B "PAPI_EINVAL"
One or more of the arguments is invalid.
.TP
.B "PAPI_ESYS"
A system or C library call failed inside PAPI, see the 
.I "errno"
variable.
.TP
.B "PAPI_ENOEVST"
The EventSet specified does not exist.

.SH EXAMPLES
.LP

  int EventSet = PAPI_NULL;
  unsigned int native = 0x0;
  long long values[1] = (long long)0;
.LP
	
  if (PAPI_create_eventset(&EventSet) != PAPI_OK)
    handle_error(1);

  /* Add Total Instructions Executed to our EventSet */

  if (PAPI_add_event(&EventSet, PAPI_TOT_INS) != PAPI_OK)
    handle_error(1);

  /* Start counting */

  if (PAPI_start(EventSet) != PAPI_OK)
    handle_error(1);

  poorly_tuned_function();

  if (PAPI_accum(EventSet, values) != PAPI_OK)
    handle_error(1);

  printf("%lld\n",values[0]);

  poorly_tuned_function();

  if (PAPI_stop(EventSet, values) != PAPI_OK)
    handle_error(1);

  printf("%lld\n",values[0]);

.SH AUTHOR
Philip J. Mucci <mucci@cs.utk.edu>

.SH BUGS
This function has no known bugs.

.SH SEE ALSO
.BR PAPI_add_event "(3), " PAPI_reset "(3), " PAPI_read "(3), "
.BR PAPI_set_opt "(3), " PAPI_rem_event "(3), " 
.BR PAPI_cleanup_eventset "(3), " PAPI_destroy_eventset "(3), " 
The PAPI Web Site: 
.B http://icl.cs.utk.edu/projects/papi
