.TH "reads_t" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reads_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct reads * \fBnext\fP"
.br
.ti -1c
.RI "struct reads * \fBprev\fP"
.br
.ti -1c
.RI "long_long \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "long_long reads_t::value"
Event value 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
