.TH "Return Codes" 3 "Wed Feb 8 2012" "Version 4.2.1.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Return Codes \- 
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPAPI_OK\fP   0"
.br
.ti -1c
.RI "#define \fBPAPI_EINVAL\fP   -1"
.br
.ti -1c
.RI "#define \fBPAPI_ENOMEM\fP   -2"
.br
.ti -1c
.RI "#define \fBPAPI_ESYS\fP   -3"
.br
.ti -1c
.RI "#define \fBPAPI_ESBSTR\fP   -4"
.br
.ti -1c
.RI "#define \fBPAPI_ECLOST\fP   -5"
.br
.ti -1c
.RI "#define \fBPAPI_EBUG\fP   -6"
.br
.ti -1c
.RI "#define \fBPAPI_ENOEVNT\fP   -7"
.br
.ti -1c
.RI "#define \fBPAPI_ECNFLCT\fP   -8"
.br
.ti -1c
.RI "#define \fBPAPI_ENOTRUN\fP   -9"
.br
.ti -1c
.RI "#define \fBPAPI_EISRUN\fP   -10"
.br
.ti -1c
.RI "#define \fBPAPI_ENOEVST\fP   -11"
.br
.ti -1c
.RI "#define \fBPAPI_ENOTPRESET\fP   -12"
.br
.ti -1c
.RI "#define \fBPAPI_ENOCNTR\fP   -13"
.br
.ti -1c
.RI "#define \fBPAPI_EMISC\fP   -14"
.br
.ti -1c
.RI "#define \fBPAPI_EPERM\fP   -15"
.br
.ti -1c
.RI "#define \fBPAPI_ENOINIT\fP   -16"
.br
.ti -1c
.RI "#define \fBPAPI_ENOCMP\fP   -17"
.br
.ti -1c
.RI "#define \fBPAPI_ENOSUPP\fP   -18"
.br
.ti -1c
.RI "#define \fBPAPI_ENOIMPL\fP   -19"
.br
.ti -1c
.RI "#define \fBPAPI_EBUF\fP   -20"
.br
.ti -1c
.RI "#define \fBPAPI_EINVAL_DOM\fP   -21"
.br
.ti -1c
.RI "#define \fBPAPI_EATTR\fP   -22"
.br
.ti -1c
.RI "#define \fBPAPI_ECOUNT\fP   -23"
.br
.ti -1c
.RI "#define \fBPAPI_ECOMBO\fP   -24"
.br
.ti -1c
.RI "#define \fBPAPI_NUM_ERRORS\fP   25"
.br
.ti -1c
.RI "#define \fBPAPI_NOT_INITED\fP   0"
.br
.ti -1c
.RI "#define \fBPAPI_LOW_LEVEL_INITED\fP   1"
.br
.ti -1c
.RI "#define \fBPAPI_HIGH_LEVEL_INITED\fP   2"
.br
.ti -1c
.RI "#define \fBPAPI_THREAD_LEVEL_INITED\fP   4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Return Codes All of the functions contained in the PerfAPI return standardized error codes. Values greater than or equal to zero indicate success, less than zero indicates failure. 
.SH "Define Documentation"
.PP 
.SS "#define PAPI_EATTR   -22"Invalid or missing event attributes 
.SS "#define PAPI_EBUF   -20"Buffer size exceeded 
.SS "#define PAPI_EBUG   -6"Internal error, please send mail to the developers 
.SS "#define PAPI_ECLOST   -5"Access to the counters was lost or interrupted 
.SS "#define PAPI_ECNFLCT   -8"Event exists, but cannot be counted due to counter resource limitations 
.SS "#define PAPI_ECOMBO   -24"Bad combination of features 
.SS "#define PAPI_ECOUNT   -23"Too many events or attributes 
.SS "#define PAPI_EINVAL   -1"Invalid argument 
.SS "#define PAPI_EINVAL_DOM   -21"EventSet domain is not supported for the operation 
.SS "#define PAPI_EISRUN   -10"EventSet is currently counting 
.SS "#define PAPI_EMISC   -14"Unknown error code 
.SS "#define PAPI_ENOCMP   -17"Component Index isn't set 
.SS "#define PAPI_ENOCNTR   -13"Hardware does not support performance counters 
.SS "#define PAPI_ENOEVNT   -7"Event does not exist 
.SS "#define PAPI_ENOEVST   -11"No such EventSet Available 
.SS "#define PAPI_ENOIMPL   -19"Not implemented 
.SS "#define PAPI_ENOINIT   -16"PAPI hasn't been initialized yet 
.SS "#define PAPI_ENOMEM   -2"Insufficient memory 
.SS "#define PAPI_ENOSUPP   -18"Not supported 
.SS "#define PAPI_ENOTPRESET   -12"Event in argument is not a valid preset 
.SS "#define PAPI_ENOTRUN   -9"EventSet is currently not running 
.SS "#define PAPI_EPERM   -15"Permission level does not permit operation 
.SS "#define PAPI_ESBSTR   -4"Not supported by substrate 
.SS "#define PAPI_ESYS   -3"A System/C library call failed 
.SS "#define PAPI_NUM_ERRORS   25"Number of error messages specified in this API 
.SS "#define PAPI_OK   0"No error 
.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code.
