.TH "threads_t" 3 "Thu Dec 14 2023" "Version 7.1.0.0" "PAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
threads_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned long \fBkey\fP"
.br
.ti -1c
.RI "\fBregions_t\fP * \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned long threads_t::key"
Thread ID 
.SS "\fBregions_t\fP* threads_t::value"
List of regions 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI from the source code\&.
