cd ..\man
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_accum.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_accum_counters.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_add_event.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_add_events.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_add_pevent.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_cleanup_eventset.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_create_eventset.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_describe_event.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_destroy_eventset.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_event_code_to_name.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_event_name_to_code.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_flops.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_executable_info.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_hardware_info.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_opt.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_overflow_address.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_real_cyc.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_real_usec.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_virt_cyc.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_get_virt_usec.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_help.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_label_event.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_library_init.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_list_events.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_lock.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_multiplex_init.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_num_counters.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_overflow.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_perror.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_presets.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_profil.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_query_all_events_verbose.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_query_event.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_query_event_verbose.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_read.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_read_counters.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_rem_event.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_rem_events.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_rem_pevent.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_restore.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_reset.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_save.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_set_debug.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_set_domain.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_set_granularity.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_set_multiplex.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_set_opt.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_shutdown.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_sprofil.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_start.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_start_counters.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_state.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_stop.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_stop_counters.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_strerror.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_thread_id.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_thread_init.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_unlock.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_write.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_get_clockrate.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_get_domain.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_get_exe_info.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_get_granularity.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_get_preload.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPIF_set_event_domain.3
perl ../doc/papi_progref.pl -o ../doc/progref man3/PAPI_num_hwctrs.3
cd ..\doc
