#ifndef __PAPI_CUDA_STD_EVENT_DEFS_H__
#define __PAPI_CUDA_STD_EVENT_DEFS_H__

#define PAPI_MAX_cuda_PRESETS 128

enum
{
    PAPI_CUDA_FP16_FMA_idx = PAPI_cuda_PRESET_OFFSET,
    PAPI_CUDA_BF16_FMA_idx,
    PAPI_CUDA_FP32_FMA_idx,
    PAPI_CUDA_FP64_FMA_idx,
    PAPI_CUDA_FP_FMA_idx,
    PAPI_CUDA_FP8_OPS_idx
};

#define PAPI_CUDA_FP16_FMA  (PAPI_CUDA_FP16_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_CUDA_BF16_FMA  (PAPI_CUDA_BF16_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_CUDA_FP32_FMA  (PAPI_CUDA_FP32_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_CUDA_FP64_FMA  (PAPI_CUDA_FP64_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_CUDA_FP_FMA    (PAPI_CUDA_FP_FMA_idx   | PAPI_PRESET_MASK)
#define PAPI_CUDA_FP8_OPS   (PAPI_CUDA_FP8_OPS_idx  | PAPI_PRESET_MASK)

#endif /* __PAPI_CUDA_STD_EVENT_DEFS_H__ */
