.TH "event_chooser.c" 1 "Fri Aug 26 2011" "Version 4.1.3.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event_chooser.c \- 
.PP
papi_event_chooser utility'\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'papi_test\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static char * \fBis_derived\fP (PAPI_event_info_t *info)"
.br
.ti -1c
.RI "static int \fBadd_remove_event\fP (int EventSet, int evt)"
.br
.ti -1c
.RI "static int \fBshow_event_info\fP (int evt)"
.br
.ti -1c
.RI "void \fBpapi_init\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBnative\fP ()"
.br
.ti -1c
.RI "int \fBpreset\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBEventSet\fP = PAPI_NULL"
.br
.ti -1c
.RI "int \fBretval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
