.\" $Id$
.TH EVENT_CHOOSER 1 "March, 2005"
.SH NAME
event_chooser \- given a list of named events, lists other events that can be counted with them.

.SH SYNOPSIS

\fBevent_chooser\fP NATIVE | PRESET <event> <event> ...

 
.SH DESCRIPTION
\fBevent_chooser\fP is a PAPI utility program that reports information about the current PAPI installation and supported preset events.  


.SH OPTIONS

This utility has no command line options.

.SH BUGS 
There are no known bugs in this utility. 
.LP
If you find a bug, it should be reported to the PAPI Mailing List at <ptools-perfapi@ptools.org>. 

.SH SEE ALSO
.BR PAPI "(3), " avail "(1), " clockres "(1), " command_line "(1), " cost "(1), " mem_info "(1), " native_avail "(1)"
