.TH "native_avail.c" 1 "Fri Aug 26 2011" "Version 4.1.3.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
native_avail.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'papi_test\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcommand_flags_t\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBEVT_LINE\fP   80"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBprint_help\fP (char **argv, const PAPI_component_info_t *c)"
.br
.ti -1c
.RI "static void \fBparse_args\fP (int argc, char **argv, \fBcommand_flags_t\fP *f)"
.br
.ti -1c
.RI "static void \fBspace_pad\fP (char *str, int spaces)"
.br
.ti -1c
.RI "static void \fBprint_event\fP (PAPI_event_info_t *info, int offset)"
.br
.ti -1c
.RI "static int \fBparse_unit_masks\fP (PAPI_event_info_t *info)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBTESTS_QUIET\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for PAPI-C from the source code'\&.
