.TH "papi_native_avail" 1 "Fri Aug 26 2011" "Version 4.1.3.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
papi_native_avail \- papi_native_avail utility'\&.
.SH "NAME"
.PP
papi_native_avail - provides detailed information for PAPI native events'\&.
.SH "Synopsis"
.PP
.SH "Description"
.PP
papi_native_avail is a PAPI utility program that reports information about the native events available on the current platform'\&. A native event is an event specific to a specific hardware platform'\&. On many platforms, a specific native event may have a number of optional settings'\&. In such cases, the native event and the valid settings are presented, rather than every possible combination of those settings'\&. For each native event, a name, a description, and specific bit patterns are provided'\&.
.SH "Options"
.PP
This utility has no command line options'\&.
.SH "Bugs"
.PP
There are no known bugs in this utility'\&. If you find a bug, it should be reported to the PAPI Mailing List at <ptools-perfapi@ptools.org>'\&. 
