.\" $Id$
.TH PAPI_CLOCKRES 1 "May, 2005"
.SH NAME
papi_clockres \- measures and reports clock latency and resolution for PAPI timers.

.SH SYNOPSIS

\fBpapi_clockres\fP


.SH DESCRIPTION
\fBpapi_clockres\fP is a PAPI utility program that measures and reports the latency and resolution of the four PAPI timer functions:
\fBPAPI_get_real_cyc(), PAPI_get_virt_cyc(), PAPI_get_real_usec()
and 
\fBPAPI_get_virt_usec().


.SH OPTIONS


This utility has no command line options.


.SH BUGS 
There are no known bugs in this utility. 
.LP
If you find a bug, it should be reported to the PAPI Mailing List at <ptools-perfapi@ptools.org>. 

.SH SEE ALSO
.BR PAPI "(3), " papi_avail "(1), " papi_command_line "(1), " papi_cost "(1), " papi_decode "(1), "
.BR papi_event_chooser "(1), " papi_mem_info "(1), " papi_native_avail "(1)"
