.TH "papi_command_line" 1 "Fri Aug 26 2011" "Version 4.1.3.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
papi_command_line \- .SH "NAME"
.PP
papi_command_line - executes PAPI preset or native events from the command line'\&.
.SH "Synopsis"
.PP
papi_command_line <event> <event> '\&.'\&.'\&.
.SH "Description"
.PP
papi_command_line is a PAPI utility program that adds named events from the command line to a PAPI EventSet and does some work with that EventSet'\&. This serves as a handy way to see if events can be counted together, and if they give reasonable results for known work'\&.
.SH "Options"
.PP
This utility has no command line options'\&.
.SH "Bugs"
.PP
There are no known bugs in this utility'\&. If you find a bug, it should be reported to the PAPI Mailing List at <ptools-perfapi@ptools.org>'\&. 
