.TH "papi_component_avail" 1 "Fri Aug 26 2011" "Version 4.1.3.0" "PAPI-C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
papi_component_avail \- papi_component_avail utility'\&.
.SH "NAME"
.PP
papi_native_avail - provides detailed information for PAPI native events'\&.
.SH "Synopsis"
.PP
.SH "Description"
.PP
papi_component_avail is a PAPI utility program that reports information about the components papi was built with'\&.
.SH "Options"
.PP
-h help message -d provide detailed information about each component'\&.
.SH "Bugs"
.PP
There are no known bugs in this utility'\&. If you find a bug, it should be reported to the PAPI Mailing List at <ptools-perfapi@ptools.org>'\&. 
