/* This file generates the #defines needed for Fortran examples of PAPI.
Its output is usually directed to fpapi.h. See Makefile.inc for details. */

#include <stdlib.h>
#include <stdio.h>

  /* Windows doesn't have a unistd.h */
#ifndef _WIN32
  #include <unistd.h>
#endif

#include <errno.h>
#include <sys/types.h>
#include <memory.h>
#include <malloc.h>
#include "papiStdEventDefs.h"
#include "papi.h"
#include "papiStrings.h"
#undef NDEBUG
#include <assert.h>

/*
	The following 6 arrays are used to create a series of defines
	for use with PAPI in Fortran programs.
	The first, third and fifth contain the string names of the defines.
	The second, fourth and sixth contain the integer values associated with the names.
	These pairs of arrays MUST be kept synchonized. Sizes are computed automagically.
*/

const char *papi_defNam[] = {
  "PAPI_NULL",
  "PAPI_VER_CURRENT",

  "PAPI_DOM_USER",
  "PAPI_DOM_KERNEL",
  "PAPI_DOM_OTHER",
  "PAPI_DOM_ALL",
  "PAPI_DOM_MIN",
  "PAPI_DOM_MAX",
  "PAPI_DOM_HWSPEC", 

  "PAPI_STOPPED",
  "PAPI_RUNNING",
  "PAPI_OVERFLOWING",
  "PAPI_PROFILING",

  "PAPI_QUIET",
  "PAPI_VERB_ECONT",
  "PAPI_VERB_ESTOP",

  "PAPI_MAX_STR_LEN",
  "PAPI_NUM_ERRORS",

  "PAPI_SET_DEBUG",
  "PAPI_GET_DEBUG",
  "PAPI_SET_DEFDOM",
  "PAPI_GET_DEFDOM",
  "PAPI_SET_DOMAIN",
  "PAPI_GET_DOMAIN",
  "PAPI_SET_DEFGRN",
  "PAPI_GET_DEFGRN",
  "PAPI_SET_GRANUL",
  "PAPI_GET_GRANUL",
  "PAPI_SET_INHERIT",
  "PAPI_GET_INHERIT",

  "PAPI_GRN_THR",
  "PAPI_GRN_MIN",
  "PAPI_GRN_PROC",
  "PAPI_GRN_PROCG ",
  "PAPI_GRN_SYS",
  "PAPI_GRN_SYS_CPU",
  "PAPI_GRN_MAX",

  "PAPI_PROFIL_POSIX",
  "PAPI_PROFIL_RANDOM",
  "PAPI_PROFIL_WEIGHTED",
  "PAPI_PROFIL_COMPRESS"
};

const int papi_defNum[] = {
  PAPI_NULL,
  PAPI_VER_CURRENT,

  PAPI_DOM_USER,
  PAPI_DOM_KERNEL,
  PAPI_DOM_OTHER,
  PAPI_DOM_ALL,
  PAPI_DOM_MIN,
  PAPI_DOM_MAX,
  PAPI_DOM_HWSPEC, 

  PAPI_STOPPED,
  PAPI_RUNNING,
  PAPI_OVERFLOWING,
  PAPI_PROFILING,
  PAPI_QUIET,
  PAPI_VERB_ECONT,
  PAPI_VERB_ESTOP,

  PAPI_MAX_STR_LEN,
  PAPI_NUM_ERRORS,

  PAPI_SET_DEBUG,
  PAPI_GET_DEBUG,
  PAPI_SET_DEFDOM,
  PAPI_GET_DEFDOM,
  PAPI_SET_DOMAIN,
  PAPI_GET_DOMAIN,
  PAPI_SET_DEFGRN,
  PAPI_GET_DEFGRN,
  PAPI_SET_GRANUL,
  PAPI_GET_GRANUL,
  PAPI_SET_INHERIT,
  PAPI_GET_INHERIT,

  PAPI_GRN_THR,
  PAPI_GRN_MIN,
  PAPI_GRN_PROC,
  PAPI_GRN_PROCG ,
  PAPI_GRN_SYS,
  PAPI_GRN_SYS_CPU,
  PAPI_GRN_MAX,

  PAPI_PROFIL_POSIX,
  PAPI_PROFIL_RANDOM,
  PAPI_PROFIL_WEIGHTED,
  PAPI_PROFIL_COMPRESS
};

const char *papi_errNam[] = {
  PAPI_OK_nm,
  PAPI_EINVAL_nm,
  PAPI_ENOMEM_nm,
  PAPI_ESYS_nm,
  PAPI_ESBSTR_nm,
  PAPI_ECLOST_nm,
  PAPI_EBUG_nm,
  PAPI_ENOEVNT_nm,
  PAPI_ECNFLCT_nm,
  PAPI_ENOTRUN_nm,
  PAPI_EISRUN_nm,
  PAPI_ENOEVST_nm,
  PAPI_ENOTPRESET_nm,
  PAPI_ENOCNTR_nm,
  PAPI_EMISC_nm 
};

const int papi_errNum[] = {
  PAPI_OK,
  PAPI_EINVAL,
  PAPI_ENOMEM,
  PAPI_ESYS,
  PAPI_ESBSTR,
  PAPI_ECLOST,
  PAPI_EBUG,
  PAPI_ENOEVNT,
  PAPI_ECNFLCT,
  PAPI_ENOTRUN,
  PAPI_EISRUN,
  PAPI_ENOEVST,
  PAPI_ENOTPRESET,
  PAPI_ENOCNTR,
  PAPI_EMISC 
};

const char *papi_miscNam[] = {
  "NUM_FLOPS" 
};

const int papi_miscNum[] = {
  10000000 
};


static void define_val(const char *val_string, int val)
{
      printf("#define %-18s % d\n",val_string,val);
}

static void createDef(char *title, const char **names, const int *nums, int size)
{
	int i,j;
  /* compute the size of the predefined arrays */
  j = size/sizeof(int);

  /* create defines for each line in the general arrays */
  printf("\nC\nC\t%s\nC\n\n", title);
  for (i=0;i<j;i++) define_val(names[i],nums[i]);
}


int main(int argc, char **argv) 
{
  int i,j;
  const PAPI_preset_info_t *info = NULL;

  assert(info = PAPI_query_all_events_verbose());

  /* print a file header block */
  printf("C\nC\tThis file contains defines required by the PAPI Fortran interface.\n");
  printf("C\tIt is automagically generated by genpapifdef.c\n");
  printf("C\tDO NOT modify its contents and expect the changes to stick.\n");
  printf("C\tChanges MUST be made in genpapifdef.c instead.\nC\n\n");

  /* create defines for the internal array pairs */
  createDef("General purpose defines.", papi_defNam, papi_defNum, sizeof(papi_defNum));
  createDef("Error defines.", papi_errNam, papi_errNum, sizeof(papi_errNum));
  createDef("Miscellaneous defines.", papi_miscNam, papi_miscNum, sizeof(papi_miscNum));

  /* create defines for each member of the PRESET array */
  printf("\nC\nC\tPAPI preset event values.\nC\n\n");
  for (i=0;i<PAPI_MAX_PRESET_EVENTS;i++)
    if (info[i].event_name)
      define_val(info[i].event_name,info[i].event_code);

  exit(0);
}

