SUBSTR  = linux-x86
DESCR	= "Patched linux 2.x with Intel Pentium Pro, II or III"
TARGET	= libraries
TESTS	= serial

CFLAGS  = -g -Wall
OPTFLAGS= -O6 -mpentiumpro
SMPCFLGS= 
OMPCFLGS= 
LDFLAGS = 
CC_R	= cc
CC	= cc
F77	= g77

include Makefile.inc




