OPTFLAGS= -O3 -Wall -march=athlon
TOPTFLAGS= -O -Wall -march=athlon
F77	= g77
CC      = gcc
CC_SHR  = $(CC) -shared -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(PREFIX)/lib"
# include Rules.perfctr-2.6.x
include Rules.perfctr-2.4.x
