COMPILER	= CATAMOUNT

VERSION 	= 2.5.4
CPU	        = p3
NOTLS       = -DNO_TLS
CFLAGS	    = -D__CATAMOUNT__ -DPFMLIB_VERSION_22
TOPTFLAGS	= -D__x86_64__

#include Rules.perfctr
include Rules.perfctr-pfm
