# Libpfm version is set automatically by the Rules.libpfm file
# Override on command line or in this makefile
# VERSION	= 2.0
# COMPILER	?= INTEL
CPU		= 2

# Optional additional substrates
# ACPI = TRUE
# MYRINET_MX = TRUE

include Rules.pfm
