VERSION 	= 2.7.x
CPU		= ppc64
CPU_MODEL	= POWER6
ARCH_EVENTS	= power6_events
CPU_TYPE 	= ppc64
SHRFLAGS	= -fPIC
# for Debian, comment the following line out
BITS		= 32
CFLAGS	= -D_$(CPU_MODEL) -DNEED_FFSLL -D__perfctr__ -DARCH_EVTS=\"$(ARCH_EVENTS).h\" -DPAPI_DATADIR=\"${DATADIR}\"
FFLAGS  = -D_$(CPU_MODEL)
include Rules.perfctr
