VERSION 	= 2.7.x
CPU		= ppc64
CPU_MODEL	= POWER4
ARCH_EVENTS	= power4_events
CPU_TYPE 	= ppc64
# for Debian, comment the following line out
BITS		= 32
CFLAGS		= -D_$(CPU_MODEL) -D__perfctr__ -DARCH_EVTS=\"$(ARCH_EVENTS).h\"
FFLAGS		= -D_$(CPU_MODEL)
include Rules.perfctr
