LIBRARY   = libpapi.a
SHLIB     = libpapi.so
SUBSTR  = pmapi-ppc64
ARCH_EVENTS    = power4_events
CPU_MODEL      = POWER4
cpu_option     = pwr4
MSUBSTR = power4
DESCR	= "AIX 5.1.0 or greater with POWER4"
BITS    =
ARG64	= 

include Makefile.aix-powerpc.common
