LIBRARY   = libpapi.a
SHLIB     = libpapi.so
SUBSTR  = any-null
MEMSUBSTR = any-null
DESCR	= "Sample substrate: Any hardware platform with GNU compilers"
LIBS	= static
TARGETS = serial multiplex

CFLAGS  = -Wall -g -DDEBUG
FFLAGS	= -Wall -g
CC	= gcc
F77	= g77

include Makefile.inc

native_clean:

native_install:

