all:
	@echo "Please use one of the following commands:";
	@echo "";
	@echo "make -f Makefile.linux-ia64-libpfm2.0 (see ./pfmon-2.0)";
	@echo "make -f Makefile.linux-ia64-itanium2-libpfm2.0 (see ./pfmon-2.0)";
	@echo "make -f Makefile.unicos-t3e";
	@echo "make -f Makefile.aix5-power3";
	@echo "make -f Makefile.aix-power4";
	@echo "make -f Makefile.aix-power4-64bit";
	@echo "make -f Makefile.aix-power";
	@echo "make -f Makefile.solaris-ultra";
	@echo "make -f Makefile.irix64-mips";
	@echo "make -f Makefile.irix-mips";
	@echo "make -f Makefile.linux-perfctr-2.4.5 (see ./perfctr-2.4.5)";
#	@echo "OLD: make -f Makefile.linux-perfctr-2.3.12 (see ./perfctr-2.3.12)";
#	@echo "OLD: make -f Makefile.linux-perfctr-1.6.1 (see ./perfctr-1.6.1)";
	@echo "make -f Makefile.dadd-alpha (EV6/67/7 only)";
	@echo "make -f Makefile.tru64-alpha (EV6/67 only)";
	@echo "make -f Makefile.linux-alpha (with patched iprobe)";
	@echo "make -f Makefile.any-null (for testing)";
	@echo "";
	@echo "With one of the following targets as an argument";
	@echo "";
	@echo "<none>		- Compiles the library and tests";
	@echo "test		- Runs the simplest test case";
	@echo "fulltest	- Runs the all the test cases";
	@echo "install PREFIX=<dir> - Installs in directory PREFIX/lib, PREFIX/man, PREFIX/share/papi"; 
	@echo "clean		- Removes object files and executables";
	@echo "dist		- Prepares a tarball";


