MAKEVER   = solaris-ultra
PREFIX    = /usr/local
PMAPI     = 
NOTLS     = -DNO_TLS
ALTIX	  = 
PMINIT	  = 
# PFM_PREFIX= @pfm_prefix@
# PFM	  = @pfm@
# PERFCTR_PREFIX= @perfctr_prefix@
# PERFCTR	  = @perfctr@

include ./Makefile.$(MAKEVER)
