#****************************
#* THIS IS OPEN SOURCE CODE *
#****************************
#* (C) COPYRIGHT International Business Machines Corp. 2005
#*  This file is licensed under the University of Tennessee license.
#*  See LICENSE.txt.
#*

VERSION 	= 2.7.x
CPU		= ppc64
CPU_MODEL	= PPC970
ARCH_EVENTS	= ppc970_events
CPU_TYPE 	= ppc64
SHRFLAGS	= -fPIC
BITS		= 32
CFLAGS	= -D_$(CPU_MODEL) -DNEED_FFSLL -D__perfctr__ -DARCH_EVTS=\"$(ARCH_EVENTS).h\"
include Rules.perfctr
