VERSION 	?= 2.6.x
CPU		= p4
CC		= gcc
CC_SHR		= $(CC) -shared -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(PREFIX)/lib"
OPTFLAGS	= -march=pentium4 -msse -msse2

include Rules.perfctr

