all:
	@echo "Please use one of the following commands:";
	@echo "";
	@echo "make -f Makefile.linux-ia64-libpfm2.0 (see ./pfmon-2.0)";
	@echo "make -f Makefile.linux-ia64-itanium2-libpfm2.0 (see ./pfmon-2.0)";
	@echo "make -f Makefile.unicos-t3e";
	@echo "make -f Makefile.aix5-power3";
	@echo "make -f Makefile.aix-power4";
	@echo "make -f Makefile.aix-power4-64bit";
	@echo "make -f Makefile.aix-power";
	@echo "make -f Makefile.solaris-ultra";
	@echo "make -f Makefile.irix64-mips";
	@echo "make -f Makefile.irix-mips";
	@echo "make -f Makefile.linux-perfctr-p3 (see ./perfctr-2.4/6.x)";
	@echo "make -f Makefile.linux-perfctr-p4 (see ./perfctr-2.4/6.x)";
	@echo "make -f Makefile.linux-opteron (see ./perfctr-2.4/6.x)";
	@echo "make -f Makefile.dadd-alpha (EV6/67/7 only)";
	@echo "make -f Makefile.tru64-alpha (EV6/67 only)";
	@echo "make -f Makefile.linux-alpha (with patched iprobe)";
	@echo "make -f Makefile.any-null (for testing)";
	@echo "";
	@echo "With one of the following targets as an argument";
	@echo "";
	@echo "<none>		- Compiles the library and tests";
	@echo "test		- Runs the simplest test case";
	@echo "fulltest		- Runs the all the test cases";
	@echo "install PREFIX=<dir> - Installs PAPI in PREFIX/..."; 
	@echo "install-man PREFIX=<dir> - Installs man pages in PREFIX/..."; 
	@echo "install-tests PREFIX=<dir> - Installs tests in PREFIX/..."; 
	@echo "install-all PREFIX=<dir> - Installs everything in PREFIX/..."; 
	@echo "clean		- Removes object files and temporary files";
	@echo "clobber		- Removes libraries, executables and generated header files";
	@echo "dist		- Prepares a binary tarball in the curent directory";


