OPTFLAGS= -O3 -g -Wall -march=athlon
TOPTFLAGS= -O -g -Wall -march=athlon
F77	= g77
CC      = gcc
CC_SHR  = $(CC) -shared -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(PREFIX)/lib"
# include Makefile.perfctr-2.6.x
include Makefile.perfctr-2.4.x
