PE := $(shell echo $${CRAY_PE_TARGET})

ifeq ($(PE), cray-x2)

COMPILER	= CRAYX2
CC		= craynv-cray-linux-gnu-gcc
F77		= craynv-cray-linux-gnu-gfortran
CPP		= $(CC) -E
LDFLAGS		= -lpthread
TESTS		= ctests

else

COMPILER	= CRAYXT
CFLAGS		+= -D __crayxt

endif

CFLAGS		+= $(PFM_VERSION)

include Rules.pfm2
