PE := $(shell echo $${CRAY_PE_TARGET})

ifeq ($(PE), cray-x2)

COMPILER	= CRAYX2
CC		= craynv-cray-linux-gnu-gcc
F77		= craynv-cray-linux-gnu-gfortran
CPP		= $(CC) -E
LDFLAGS		= -lpthread -static
TESTS		= ctests

else

COMPILER	= CRAYXT

endif

CFLAGS		+= -DPFMLIB_VERSION_22

include Rules.pfm2
