LIBRARY   = libpapi64.a
SHLIB     = libpapi64.so
SUBSTR  = pmapi-ppc64
ARCH_EVENTS    = power6_events
CPU_MODEL      = POWER6
cpu_option     = pwr6
MSUBSTR = power6
DESCR	= "AIX 5.1.0 or greater with POWER6 64 bit build"
BITS    = -q64
ARG64	= -X64
CPPFLAGS = -qlanglvl=extended

include Makefile.aix-powerpc.common
