CPU	= p3
VERSION	?= 2.6.x
OPTFLAGS= -O3 -Wall -march=pentiumpro
TOPTFLAGS= -O -Wall -march=pentiumpro
F77	= g77
CC	= gcc
CC_SHR  = $(CC) -shared -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(PREFIX)/lib"
include Rules.perfctr-$(VERSION)
