CFLAGS	= -DITANIUM2  -DPFM20
FFLAGS	= -DITANIUM2  -DPFM20
DESCR	= "Stock Linux 2.4.18 + for the Intel Itanium 2"

LIBPFMHOME = libpfm-2.0
PFM_LIB_PATH = ./$(LIBPFMHOME)/libpfm
PFM_INC_PATH = ./$(LIBPFMHOME)/include
MSUBSTR  = linux-ia64-itanium2-libpfm2.0

PFMOBJS = pfmlib_generic.o 

include Rules.linux-libpfm
