LIBRARY   = libpapi.a
SHLIB     = libpapi.so
SUBSTR  = pmapi-ppc64
ARCH_EVENTS	= power5_events
CPU_MODEL	= POWER5
cpu_option	= pwr5
MSUBSTR = power5
DESCR	= "AIX 5.1.0 or greater with POWER5"
BITS	=
ARG64	= 


include Makefile.aix-powerpc.common
