LIBRARY   = libpapi64.a
SHLIB     = libpapi64.so

ARCH_EVENTS	= power5_events
CPU_MODEL	= POWER5
cpu_option	= pwr5
SUBSTR  = pmapi-ppc64
MSUBSTR = power5
DESCR	= "AIX 5.1.0 or greater with POWER5 64 bit build"
BITS	= -q64
ARG64	= -X64

include Makefile.aix-powerpc.common

