LIBRARY   = libpapi64.a
SHLIB     = libpapi64.so

ARCH_EVENTS	= power4_events
CPU_MODEL	= POWER4
cpu_option	= pwr4
SUBSTR  = pmapi-ppc64
MSUBSTR = power4
DESCR	= "AIX 5.1.0 or greater with POWER4 64 bit build"
BITS	= -q64
ARG64	= -X64

include Makefile.aix-powerpc.common

