VERSION 	= 2.7.x
CPU		= ppc64
CPU_MODEL	= POWER5+
ARCH_EVENTS	= power5+_events
CPU_TYPE 	= ppc64
SHRFLAGS	= -fPIC
# for Debian, comment the following line out
BITS		= 64
CFLAGS	= -g -DDEBUG -D_$(CPU_MODEL) -DNEED_FFSLL -D__perfctr__ -DARCH_EVTS=\"$(ARCH_EVENTS).h\"
include Rules.perfctr
