SUBSTR  = aix-power
DESCR	= "AIX 4.3.3 or greater with 604, 604e or 630"
LIBS	= static shared
TARGETS	= serial
# omp smp pthreads

CFLAGS  = -I/usr/lpp/pmtoolkit/include -qmaxmem=-1 -g -qtune=pwr3 -qarch=pwr3
#OPTFLAGS= -O3 -qstrict
SMPCFLGS= -qsmp
OMPCFLGS= -qsmp=omp
LDFLAGS = -bI:/usr/lpp/pmtoolkit/lib/pmsvcs.exp -L/usr/lpp/pmtoolkit/lib -lpmapi
CC_R	= xlc_r -qnolm
CC	= xlc -qnolm
CC_SHR	= ld -G -r
F77	= xlf -qnolm

include Makefile.inc
