VERSION 	= 2.7.x
CPU		= ppc64
CPU_MODEL	= PPC970
ARCH_EVENTS	= ppc970_events
CPU_TYPE 	= ppc64
# for Debian, comment the following line out
BITS		= 64
CFLAGS	= -D_$(CPU_MODEL) -D__perfctr__ -DARCH_EVTS=\"$(ARCH_EVENTS).h\"
FFLAGS  = -D_$(CPU_MODEL)
include Rules.perfctr
