SUBSTR  = irix-mips
DESCR	= "IRIX 6.x or greater with MIPS R10000 or R12000"
LIBS	= static shared
TARGETS	= serial smp omp
FOR_USED= -DFORTRANUNDERSCORE
CFLAGS  = -g -woff 1552,1174,1116,15
OPTFLAGS= -O3 -DNDEBUG
FFLAGS	= -g
SMPCFLGS= -mp
OMPCFLGS= -mp
CC_SHR  = cc -shared -all
CC_R	= cc
CC	= cc
F77	= f77

include ./Makefile.inc

