OPTFLAGS= -Wall -O3
TOPTFLAGS= -Wall -O -D__x86_64__
F77	= g77 gcc
CC      = gcc
CC_SHR  = $(CC) -shared -fPIC -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(DESTDIR)/lib"
include Rules.perfctr-2.6.x
