SUBSTR  = solaris-ultra
DESCR	= "Solaris 5.8 or greater with UltraSPARC I or II"
LIBS	= static shared
TARGETS	= serial
# omp smp pthreads

CFLAGS  = -xarch=v8plusa -g
#OPTFLAGS= -xO3
NOOPT 	= -xO0
SMPCFLGS= -xexplicitpar
LDFLAGS = -lcpc
CC_R	= cc -mt
CC	= cc -mt
CC_SHR	= cc -shared -dy -G
F77	= 
MISCOBJS= get_tick.o

include Makefile.inc

get_tick.o: solaris-ultra/get_tick.S
	$(CC) -c -O -D_ASM -xarch=v8plusa solaris-ultra/get_tick.S
