SUBSTR  = linux-perf
DESCR	= "Linux with Perf Kernel Patch for the Pentium Pro, II, III"
LIBS	= static shared
TARGETS = serial pthreads

CFLAGS  = -Wall -mpentiumpro -g -DDEBUG
FFLAGS	= -Wall -g
OPTFLAGS= -O3
CC	= gcc
F77	= g77
CC_SHR  = $(CC) -shared -Xlinker "-soname" -Xlinker "libpapi.so" -Xlinker "-rpath" -Xlinker "$(PWD)"
CC_R	= $(CC)

include Makefile.inc


