/* 
* File:    p3_events.c
* CVS:     $Id$
* Author:  Philip Mucci
*          mucci@cs.utk.edu
* Mods:    <your name here>
*          <your email address>
*/  


#ifdef _WIN32
  /* Define SUBSTRATE to map to linux-perfctr.h
   * since we haven't figured out how to assign a value 
   * to a label at make inside the Windows IDE */
  #define SUBSTRATE "linux-perfctr.h"
#endif

#include "papi.h"
#include SUBSTRATE
#include "papi_internal.h"
#include "papi_protos.h"

native_event_entry_t *native_table;
hwi_search_t *preset_search_map;

/* Events that require tagging should be ordered such that the
   first event is the one that is read. See PAPI_FP_INS for an example. */

/* Note:  MESI and unit mask bits can be summed into the same event.
          This can be done, in some instances, using a predefined
          "TOT" event or by ORing the events together manually.
          For instance, L2 Instruction fetches can be further defined
          to count only invalid and shared fetches by simply defining
          your event as (L2_IFETCH_INV | L2_IFETCH_SHR).  An event has
          been added that can count all L2 Instruction Fetches as well.
          It's name is L2_IFETCH_TOT (for total).  This scheme has been
          implemented for any event dealing with a MESI bit.  Unit masks
          have been left to the user to simply OR together.
*/

enum {
   PNE_P3_DATA_MEM_REFS = 0x40000000,
   PNE_P3_DCU_LINES_IN,
   PNE_P3_DCU_M_LINES_IN,
   PNE_P3_DCU_M_LINES_OUT,
   PNE_P3_DCU_MISS_OUTSTANDING,
   PNE_P3_IFU_IFETCH,
   PNE_P3_IFU_IFETCH_MISS,
   PNE_P3_ITLB_MISS,
   PNE_P3_IFU_MEM_STALL,
   PNE_P3_ILD_STALL,
   PNE_P3_L2_IFETCH_MOD,
   PNE_P3_L2_IFETCH_EXC,
   PNE_P3_L2_IFETCH_SHD,
   PNE_P3_L2_IFETCH_INV,
   PNE_P3_L2_IFETCH_TOT,
   PNE_P3_L2_LD_MOD,
   PNE_P3_L2_LD_EXC,
   PNE_P3_L2_LD_SHD,
   PNE_P3_L2_LD_INV,
   PNE_P3_L2_LD_TOT,
   PNE_P3_L2_ST_MOD,
   PNE_P3_L2_ST_EXC,
   PNE_P3_L2_ST_SHD,
   PNE_P3_L2_ST_INV,
   PNE_P3_L2_ST_TOT,
   PNE_P3_L2_LINES_IN,
   PNE_P3_L2_LINES_OUT,
   PNE_P3_L2_M_LINES_INM,
   PNE_P3_L2_M_LINES_OUTM,
   PNE_P3_L2_RQSTS_MOD,
   PNE_P3_L2_RQSTS_EXC,
   PNE_P3_L2_RQSTS_SHD,
   PNE_P3_L2_RQSTS_INV,
   PNE_P3_L2_RQSTS_TOT,
   PNE_P3_L2_ADS,
   PNE_P3_L2_DBS_BUSY,
   PNE_P3_L2_DBS_BUSY_RD,
   PNE_P3_BUS_DRDY_CLOCKS_SELF,
   PNE_P3_BUS_DRDY_CLOCKS_ANY,
   PNE_P3_BUS_LOCK_CLOCKS_SELF,
   PNE_P3_BUS_LOCK_CLOCKS_ANY,
   PNE_P3_BUS_REQ_OUTSTANDING,
   PNE_P3_BUS_TRAN_BRD_SELF,
   PNE_P3_BUS_TRAN_BRD_ANY,
   PNE_P3_BUS_TRAN_RFO_SELF,
   PNE_P3_BUS_TRAN_RFO_ANY,
   PNE_P3_BUS_TRANS_WB_SELF,
   PNE_P3_BUS_TRANS_WB_ANY,
   PNE_P3_BUS_TRAN_IFETCH_SELF,
   PNE_P3_BUS_TRAN_IFETCH_ANY,
   PNE_P3_BUS_TRAN_INVAL_SELF,
   PNE_P3_BUS_TRAN_INVAL_ANY,
   PNE_P3_BUS_TRAN_PWR_SELF,
   PNE_P3_BUS_TRAN_PWR_ANY,
   PNE_P3_BUS_TRANS_P_SELF,
   PNE_P3_BUS_TRANS_P_ANY,
   PNE_P3_BUS_TRANS_IO_SELF,
   PNE_P3_BUS_TRANS_IO_ANY,
   PNE_P3_BUS_TRAN_DEF_SELF,
   PNE_P3_BUS_TRAN_DEF_ANY,
   PNE_P3_BUS_TRAN_BURST_SELF,
   PNE_P3_BUS_TRAN_BURST_ANY,
   PNE_P3_BUS_TRAN_ANY_SELF,
   PNE_P3_BUS_TRAN_ANY_ANY,
   PNE_P3_BUS_TRAN_MEM_SELF,
   PNE_P3_BUS_TRAN_MEM_ANY,
   PNE_P3_BUS_TRAN_RCV,
   PNE_P3_BUS_BNR_DRV,
   PNE_P3_BUS_HIT_DRV,
   PNE_P3_BUS_HITM_DRV,
   PNE_P3_BUS_SNOOP_STALL,
   PNE_P3_FLOPS,
   PNE_P3_FP_COMP_OPS_EXE,
   PNE_P3_FP_ASSIST,
   PNE_P3_MUL,
   PNE_P3_DIV,
   PNE_P3_CYCLES_DIV_BUSY,
   PNE_P3_LD_BLOCKS,
   PNE_P3_SB_DRAINS,
   PNE_P3_MISALIGN_MEM_REF,
   PNE_P3_EMON_KNI_PREF_DISPATCHED_PREFETCH_NTA,
   PNE_P3_EMON_KNI_PREF_DISPATCHED_PREFETCH_T1,
   PNE_P3_EMON_KNI_PREF_DISPATCHED_PREFETCH_T2,
   PNE_P3_EMON_KNI_PREF_DISPATCHED_WEAKLY_ORDERED_STORES,
   PNE_P3_EMON_KNI_PREF_MISS_PREFETCH_NTA,
   PNE_P3_EMON_KNI_PREF_MISS_PREFETCH_T1,
   PNE_P3_EMON_KNI_PREF_MISS_PREFETCH_T2,
   PNE_P3_EMON_KNI_PREF_MISS_WEAKLY_ORDERED_STORES,
   PNE_P3_INST_RETIRED,
   PNE_P3_UOPS_RETIRED,
   PNE_P3_INST_DECODED,
   PNE_P3_EMON_KNI_INST_RETIRED_PACKED_AND_SCALAR,
   PNE_P3_EMON_KNI_INST_RETIRED_SCALAR,
   PNE_P3_EMON_KNI_COMP_INST_RET_PACKED_AND_SCALAR,
   PNE_P3_EMON_KNI_COMP_INST_RET_SCALAR,
   PNE_P3_HW_INT_RX,
   PNE_P3_CYCLES_INT_MASKED,
   PNE_P3_CYCLES_INT_PENDING_AND_MASKED,
   PNE_P3_BR_INST_RETIRED,
   PNE_P3_BR_MISS_PRED_RETIRED,
   PNE_P3_BR_TAKEN_RETIRED,
   PNE_P3_BR_MISS_PRED_TAKEN_RET,
   PNE_P3_BR_INST_DECODED,
   PNE_P3_BTB_MISSES,
   PNE_P3_BR_BOGUS,
   PNE_P3_BACLEARS,
   PNE_P3_RESOURCE_STALLS,
   PNE_P3_PARTIAL_RAT_STALLS,
   PNE_P3_SEGMENT_REG_LOADS,
   PNE_P3_CPU_CLK_UNHALTED,
   PNE_P3_MMX_SAT_INSTR_EXEC,
   PNE_P3_MMX_UOPS_EXEC,
   PNE_P3_MMX_INSTR_TYPE_EXEC_MUL,
   PNE_P3_MMX_INSTR_TYPE_EXEC_SHIFT,
   PNE_P3_MMX_INSTR_TYPE_EXEC_PACK_OPS,
   PNE_P3_MMX_INSTR_TYPE_EXEC_UNPACK_OPS,
   PNE_P3_MMX_INSTR_TYPE_EXEC_LOGICAL,
   PNE_P3_MMX_INSTR_TYPE_EXEC_ARITHMETIC,
   PNE_P3_FP_MMX_TRANS_MMX_TO_FP,
   PNE_P3_FP_MMX_TRANS_FP_TO_MMX,
   PNE_P3_MMX_ASSIST,
   PNE_P3_SEG_RENAME_STALLS_ES,
   PNE_P3_SEG_RENAME_STALLS_DS,
   PNE_P3_SEG_RENAME_STALLS_FS,
   PNE_P3_SEG_RENAME_STALLS_GS,
   PNE_P3_SEG_RENAME_STALLS_TOT,
   PNE_P3_SEG_REG_RENAMES_ES,
   PNE_P3_SEG_REG_RENAMES_DS,
   PNE_P3_SEG_REG_RENAMES_FS,
   PNE_P3_SEG_REG_RENAMES_GS,
   PNE_P3_SEG_REG_RENAMES_TOT,
   PNE_P3_RET_SEG_RENAMES
};

enum {
   PNE_P2_DATA_MEM_REFS = 0x40000000,
   PNE_P2_DCU_LINES_IN,
   PNE_P2_DCU_M_LINES_IN,
   PNE_P2_DCU_M_LINES_OUT,
   PNE_P2_DCU_MISS_OUTSTANDING,
   PNE_P2_IFU_IFETCH,
   PNE_P2_IFU_IFETCH_MISS,
   PNE_P2_ITLB_MISS,
   PNE_P2_IFU_MEM_STALL,
   PNE_P2_ILD_STALL,
   PNE_P2_L2_IFETCH_MOD,
   PNE_P2_L2_IFETCH_EXC,
   PNE_P2_L2_IFETCH_SHD,
   PNE_P2_L2_IFETCH_INV,
   PNE_P2_L2_IFETCH_TOT,
   PNE_P2_L2_LD_MOD,
   PNE_P2_L2_LD_EXC,
   PNE_P2_L2_LD_SHD,
   PNE_P2_L2_LD_INV,
   PNE_P2_L2_LD_TOT,
   PNE_P2_L2_ST_MOD,
   PNE_P2_L2_ST_EXC,
   PNE_P2_L2_ST_SHD,
   PNE_P2_L2_ST_INV,
   PNE_P2_L2_ST_TOT,
   PNE_P2_L2_LINES_IN,
   PNE_P2_L2_LINES_OUT,
   PNE_P2_L2_M_LINES_INM,
   PNE_P2_L2_M_LINES_OUTM,
   PNE_P2_L2_RQSTS_MOD,
   PNE_P2_L2_RQSTS_EXC,
   PNE_P2_L2_RQSTS_SHD,
   PNE_P2_L2_RQSTS_INV,
   PNE_P2_L2_RQSTS_TOT,
   PNE_P2_L2_ADS,
   PNE_P2_L2_DBS_BUSY,
   PNE_P2_L2_DBS_BUSY_RD,
   PNE_P2_BUS_DRDY_CLOCKS_SELF,
   PNE_P2_BUS_DRDY_CLOCKS_ANY,
   PNE_P2_BUS_LOCK_CLOCKS_SELF,
   PNE_P2_BUS_LOCK_CLOCKS_ANY,
   PNE_P2_BUS_REQ_OUTSTANDING,
   PNE_P2_BUS_TRAN_BRD_SELF,
   PNE_P2_BUS_TRAN_BRD_ANY,
   PNE_P2_BUS_TRAN_RFO_SELF,
   PNE_P2_BUS_TRAN_RFO_ANY,
   PNE_P2_BUS_TRANS_WB_SELF,
   PNE_P2_BUS_TRANS_WB_ANY,
   PNE_P2_BUS_TRAN_IFETCH_SELF,
   PNE_P2_BUS_TRAN_IFETCH_ANY,
   PNE_P2_BUS_TRAN_INVAL_SELF,
   PNE_P2_BUS_TRAN_INVAL_ANY,
   PNE_P2_BUS_TRAN_PWR_SELF,
   PNE_P2_BUS_TRAN_PWR_ANY,
   PNE_P2_BUS_TRANS_P_SELF,
   PNE_P2_BUS_TRANS_P_ANY,
   PNE_P2_BUS_TRANS_IO_SELF,
   PNE_P2_BUS_TRANS_IO_ANY,
   PNE_P2_BUS_TRAN_DEF_SELF,
   PNE_P2_BUS_TRAN_DEF_ANY,
   PNE_P2_BUS_TRAN_BURST_SELF,
   PNE_P2_BUS_TRAN_BURST_ANY,
   PNE_P2_BUS_TRAN_ANY_SELF,
   PNE_P2_BUS_TRAN_ANY_ANY,
   PNE_P2_BUS_TRAN_MEM_SELF,
   PNE_P2_BUS_TRAN_MEM_ANY,
   PNE_P2_BUS_TRAN_RCV,
   PNE_P2_BUS_BNR_DRV,
   PNE_P2_BUS_HIT_DRV,
   PNE_P2_BUS_HITM_DRV,
   PNE_P2_BUS_SNOOP_STALL,
   PNE_P2_FLOPS,
   PNE_P2_FP_COMP_OPS_EXE,
   PNE_P2_FP_ASSIST,
   PNE_P2_MUL,
   PNE_P2_DIV,
   PNE_P2_CYCLES_DIV_BUSY,
   PNE_P2_LD_BLOCKS,
   PNE_P2_SB_DRAINS,
   PNE_P2_MISALIGN_MEM_REF,
   PNE_P2_INST_RETIRED,
   PNE_P2_UOPS_RETIRED,
   PNE_P2_INST_DECODED,
   PNE_P2_HW_INT_RX,
   PNE_P2_CYCLES_INT_MASKED,
   PNE_P2_CYCLES_INT_PENDING_AND_MASKED,
   PNE_P2_BR_INST_RETIRED,
   PNE_P2_BR_MISS_PRED_RETIRED,
   PNE_P2_BR_TAKEN_RETIRED,
   PNE_P2_BR_MISS_PRED_TAKEN_RET,
   PNE_P2_BR_INST_DECODED,
   PNE_P2_BTB_MISSES,
   PNE_P2_BR_BOGUS,
   PNE_P2_BACLEARS,
   PNE_P2_RESOURCE_STALLS,
   PNE_P2_PARTIAL_RAT_STALLS,
   PNE_P2_SEGMENT_REG_LOADS,
   PNE_P2_CPU_CLK_UNHALTED,
   PNE_P2_MMX_INSTR_EXEC,
   PNE_P2_MMX_SAT_INSTR_EXEC,
   PNE_P2_MMX_UOPS_EXEC,
   PNE_P2_MMX_INSTR_TYPE_EXEC_MUL,
   PNE_P2_MMX_INSTR_TYPE_EXEC_SHIFT,
   PNE_P2_MMX_INSTR_TYPE_EXEC_PACK_OPS,
   PNE_P2_MMX_INSTR_TYPE_EXEC_UNPACK_OPS,
   PNE_P2_MMX_INSTR_TYPE_EXEC_LOGICAL,
   PNE_P2_MMX_INSTR_TYPE_EXEC_ARITHMETIC,
   PNE_P2_FP_MMX_TRANS_MMX_TO_FP,
   PNE_P2_FP_MMX_TRANS_FP_TO_MMX,
   PNE_P2_MMX_ASSIST,
   PNE_P2_MMX_INSTR_RET,
   PNE_P2_SEG_REG_RENAMES_ES,
   PNE_P2_SEG_REG_RENAMES_DS,
   PNE_P2_SEG_REG_RENAMES_FS,
   PNE_P2_SEG_REG_RENAMES_GS,
   PNE_P2_SEG_REG_RENAMES_TOT,
   PNE_P2_RET_SEG_RENAMES
};

enum {
   PNE_ATH_SEG_REG_LOADS = 0x40000000,
   PNE_ATH_ST_ACTIVE_IS,
   PNE_ATH_DC_ACCESSES,
   PNE_ATH_DC_MISSES,
   PNE_ATH_L2_DC_REFILLS_MOD,
   PNE_ATH_L2_DC_REFILLS_OWN,
   PNE_ATH_L2_DC_REFILLS_EXC,
   PNE_ATH_L2_DC_REFILLS_SHR,
   PNE_ATH_L2_DC_REFILLS_INV,
   PNE_ATH_L2_DC_REFILLS_TOT,
   PNE_ATH_SYS_DC_REFILLS_MOD,
   PNE_ATH_SYS_DC_REFILLS_OWN,
   PNE_ATH_SYS_DC_REFILLS_EXC,
   PNE_ATH_SYS_DC_REFILLS_SHR,
   PNE_ATH_SYS_DC_REFILLS_INV,
   PNE_ATH_SYS_DC_REFILLS_TOT,
   PNE_ATH_DC_WB_MOD,
   PNE_ATH_DC_WB_OWN,
   PNE_ATH_DC_WB_EXC,
   PNE_ATH_DC_WB_SHR,
   PNE_ATH_DC_WB_INV,
   PNE_ATH_DC_WB_TOT,
   PNE_ATH_L1_DTLB_MISSES_AND_L2_DTLB_HITS,
   PNE_ATH_L1_AND_L2_DTLB_MISSES,
   PNE_ATH_MISALIGNED_DATA_REFERENCES,
   PNE_ATH_DRAM_SYS_REQS,
   PNE_ATH_SYS_REQS_SEL_TYPE,
   PNE_ATH_SNOOP_HITS,
   PNE_ATH_ECC_ERR,
   PNE_ATH_INTERNAL_CACHE_INV,
   PNE_ATH_TOT_CYC,
   PNE_ATH_L2_REQ,
   PNE_ATH_FILL_REQ_STALLS,
   PNE_ATH_IC_FETCHES,
   PNE_ATH_IC_MISSES,
   PNE_ATH_L2_IC_REFILLS,
   PNE_ATH_SYS_IC_REFILLS,
   PNE_ATH_L1_ITLB_MISSES,
   PNE_ATH_L2_ITLB_MISSES,
   PNE_ATH_SNOOP_RESYNCS,
   PNE_ATH_IFETCH_STALLS,
   PNE_ATH_RET_STACK_HITS,
   PNE_ATH_RET_STACK_OVERFLOW,
   PNE_ATH_RET_INSTRUCTIONS,
   PNE_ATH_RET_OPS,
   PNE_ATH_RET_BR,
   PNE_ATH_RET_BR_MIS,
   PNE_ATH_RET_TAKEN_BR,
   PNE_ATH_RET_TAKEN_BR_MIS,
   PNE_ATH_RET_FAR_CONTROL_TRANSFERS,
   PNE_ATH_RET_RESYNC_BR,
   PNE_ATH_RET_NEAR_RETURNS,
   PNE_ATH_RET_NEAR_RETURNS_MIS,
   PNE_ATH_RET_INDIRECT_BR_MIS,
   PNE_ATH_INTS_MASKED_CYC,
   PNE_ATH_INTS_MASKED_WHILE_PENDING_CYC,
   PNE_ATH_TAKEN_HARDWARE_INTS,
   PNE_ATH_INS_DECODER_EMPTY,
   PNE_ATH_DISPATCH_STALLS,
   PNE_ATH_BRANCH_ABORTS,
   PNE_ATH_SERIALIZE,
   PNE_ATH_SEG_LOAD_STALLS,
   PNE_ATH_ICU_FULL,
   PNE_ATH_RES_STATIONS_FULL,
   PNE_ATH_FPU_FULL,
   PNE_ATH_LS_FULL,
   PNE_ATH_ALL_QUIET_STALL,
   PNE_ATH_TRANS_OR_BRANCH_PENDING,
   PNE_ATH_BP_DR0,
   PNE_ATH_BP_DR1,
   PNE_ATH_BP_DR2,
   PNE_ATH_BP_DR3
};

enum {
   PNE_OPT_FP_ADD_PIPE = 0x40000000,
   PNE_OPT_FP_MULT_PIPE,
   PNE_OPT_FP_ST_PIPE,
   PNE_OPT_FP_ADD_PIPE_JUNK,
   PNE_OPT_FP_MULT_PIPE_JUNK,
   PNE_OPT_FP_ST_PIPE_JUNK,
   PNE_OPT_FP_NONE_RET,
   PNE_OPT_FP_FAST_FLAG,
   PNE_OPT_LS_SEG_REG_LOADS_ES,
   PNE_OPT_LS_SEG_REG_LOADS_CS,
   PNE_OPT_LS_SEG_REG_LOADS_SS,
   PNE_OPT_LS_SEG_REG_LOADS_DS,
   PNE_OPT_LS_SEG_REG_LOADS_FS,
   PNE_OPT_LS_SEG_REG_LOADS_GS,
   PNE_OPT_LS_SEG_REG_LOADS_HS,
   PNE_OPT_LS_SELF_MODIFYING_RESYNC,
   PNE_OPT_LS_SNOOP_RESYNC,
   PNE_OPT_LS_BUF_2_FULL,
   PNE_OPT_LS_LOCK_INS,
   PNE_OPT_LS_LOCK_REQ,
   PNE_OPT_LS_LOCK_COMP,
   PNE_OPT_LS_LATE_CANCEL,
   PNE_OPT_LS_CFLUSH,
   PNE_OPT_LS_CPUID,
   PNE_OPT_DC_ACCESS,
   PNE_OPT_DC_MISS,
   PNE_OPT_DC_L2_REFILL_INV,
   PNE_OPT_DC_L2_REFILL_SHR,
   PNE_OPT_DC_L2_REFILL_EXC,
   PNE_OPT_DC_L2_REFILL_OWN,
   PNE_OPT_DC_L2_REFILL_MOD,
   PNE_OPT_DC_L2_REFILL_TOT,
   PNE_OPT_DC_SYS_REFILL_INV,
   PNE_OPT_DC_SYS_REFILL_SHR,
   PNE_OPT_DC_SYS_REFILL_EXC,
   PNE_OPT_DC_SYS_REFILL_OWN,
   PNE_OPT_DC_SYS_REFILL_MOD,
   PNE_OPT_DC_SYS_REFILL_TOT,
   PNE_OPT_DC_COPYBACK_INV,
   PNE_OPT_DC_COPYBACK_SHR,
   PNE_OPT_DC_COPYBACK_EXC,
   PNE_OPT_DC_COPYBACK_OWN,
   PNE_OPT_DC_COPYBACK_MOD,
   PNE_OPT_DC_COPYBACK_TOT,
   PNE_OPT_DC_L1_DTLB_MISS_AND_L2_DTLB_HIT,
   PNE_OPT_DC_L1_DTLB_MISS_AND_L2_DTLB_MISS,
   PNE_OPT_DC_MISALIGNED_DATA_REF,
   PNE_OPT_DC_LATE_CANCEL,
   PNE_OPT_DC_EARLY_CANCEL,
   PNE_OPT_DC_ECC_SCRUBBER_ERR,
   PNE_OPT_DC_ECC_PIGGY_SCRUBBER_ERR,
   PNE_OPT_DC_DISPATCHED_PREFETCH_LOAD,
   PNE_OPT_DC_DISPATCHED_PREFETCH_STORE,
   PNE_OPT_DC_DISPATCHED_PREFETCH_NTA,
   PNE_OPT_DC_ACCESSES_BY_LOCK,
   PNE_OPT_DC_MISSES_BY_LOCK,
   PNE_OPT_BU_L2_REQ_IC,
   PNE_OPT_BU_L2_REQ_DC,
   PNE_OPT_BU_L2_REQ_TLB_RELOAD,
   PNE_OPT_BU_L2_REQ_TAG_SNOOP_REQ,
   PNE_OPT_BU_L2_REQ_CANC_REQ,
   PNE_OPT_BU_L2_FILL_MISS_IC,
   PNE_OPT_BU_L2_FILL_MISS_DC,
   PNE_OPT_BU_L2_FILL_MISS_TLB_RELOAD,
   PNE_OPT_BU_L2_FILL_DIRTY,
   PNE_OPT_BU_L2_FILL_FROM_L1,
   PNE_OPT_IC_FETCH,
   PNE_OPT_IC_MISS,
   PNE_OPT_IC_L2_REFILL,
   PNE_OPT_IC_SYS_REFILL,
   PNE_OPT_IC_L1ITLB_MISS_AND_L2ITLB_HIT,
   PNE_OPT_IC_L1ITLB_MISS_AND_L2ITLB_MISS,
   PNE_OPT_IC_RESYNC,
   PNE_OPT_IC_FETCH_STALL,
   PNE_OPT_IC_STACK_HIT,
   PNE_OPT_IC_STACK_OVERFLOW,
   PNE_OPT_FR_X86_INS,
   PNE_OPT_FR_RET_UOPS,
   PNE_OPT_FR_BR,
   PNE_OPT_FR_BR_MIS,
   PNE_OPT_FR_BR_TAKEN,
   PNE_OPT_FR_BR_TAKEN_MIS,
   PNE_OPT_FR_FAR_CONTROL_TRANSFERS,
   PNE_OPT_FR_RESYNCS,
   PNE_OPT_FR_NEAR_RETURNS,
   PNE_OPT_FR_NEAR_RETURNS_MIS,
   PNE_OPT_FR_BR_MISCOMPARE,
   PNE_OPT_FR_FPU_X87,
   PNE_OPT_FR_FPU_MMX_3D,
   PNE_OPT_FR_FPU_SSE_SSE2_PACKED,
   PNE_OPT_FR_FPU_SSE_SSE2_SCALAR,
   PNE_OPT_FR_FASTPATH_POS0,
   PNE_OPT_FR_FASTPATH_POS1,
   PNE_OPT_FR_FASTPATH_POS2,
   PNE_OPT_FR_INTS_MASKED,
   PNE_OPT_FR_INTS_MASKED_PENDING,
   PNE_OPT_FR_HW_INTS,
   PNE_OPT_FR_DECODER_EMPTY,
   PNE_OPT_FR_DISPATCH_STALLS,
   PNE_OPT_FR_DISPATCH_STALLS_BR,
   PNE_OPT_FR_DISPATCH_STALLS_SER,
   PNE_OPT_FR_DISPATCH_STALLS_SEG,
   PNE_OPT_FR_DISPATCH_STALLS_FULL_REORDER,
   PNE_OPT_FR_DISPATCH_STALLS_FULL_RESERVATION,
   PNE_OPT_FR_DISPATCH_STALLS_FULL_FPU,
   PNE_OPT_FR_DISPATCH_STALLS_FULL_LS,
   PNE_OPT_FR_DISPATCH_STALLS_QUEIT,
   PNE_OPT_FR_DISPATCH_STALLS_FAR,
   PNE_OPT_FR_FPU_EXCEPTIONS_X87,
   PNE_OPT_FR_FPU_EXCEPTIONS_SSE_RETYPE,
   PNE_OPT_FR_FPU_EXCEPTIONS_SSE_RECLASS,
   PNE_OPT_FR_FPU_EXCEPTIONS_SSE_MICROTRAPS,
   PNE_OPT_FR_BP_DR0,
   PNE_OPT_FR_BP_DR1,
   PNE_OPT_FR_BP_DR2,
   PNE_OPT_FR_BP_DR3,
   PNE_OPT_NB_MC_PAGE_HIT,
   PNE_OPT_NB_MC_PAGE_MISS,
   PNE_OPT_NB_MC_PAGE_CONFLICT,
   PNE_OPT_NB_MC_PAGE_TBL_OVERFLOW,
   PNE_OPT_NB_MC_DRAM,
   PNE_OPT_NB_MC_TURNAROUND_DIMM,
   PNE_OPT_NB_MC_TURNAROUND_RTW,
   PNE_OPT_NB_MC_TURNAROUND_WTR,
   PNE_OPT_NB_MC_BYPASS_HP,
   PNE_OPT_NB_MC_BYPASS_LP,
   PNE_OPT_NB_MC_BYPASS_INTERFACE,
   PNE_OPT_NB_MC_BYPASS_QUEUE,
   PNE_OPT_NB_SIZED_NONPOSTWRSZBYTE,
   PNE_OPT_NB_SIZED_NONPOSTWRSZDWORD,
   PNE_OPT_NB_SIZED_POSTWRSZBYTE,
   PNE_OPT_NB_SIZED_POSTWRSZDWORD,
   PNE_OPT_NB_SIZED_RDSZBYTE,
   PNE_OPT_NB_SIZED_RDSZDWORD,
   PNE_OPT_NB_SIZED_RDMODWR,
   PNE_OPT_NB_PROBE_MISS,
   PNE_OPT_NB_PROBE_HIT,
   PNE_OPT_NB_PROBE_HIT_DIRTY_NO_MEM_CANCEL,
   PNE_OPT_NB_PROBE_HIT_DIRTY_MEM_CANCEL,
   PNE_OPT_NB_HT_BUS0_COMMAND,
   PNE_OPT_NB_HT_BUS0_DATA,
   PNE_OPT_NB_HT_BUS0_BUFF,
   PNE_OPT_NB_HT_BUS0_NOP,
   PNE_OPT_NB_HT_BUS1_COMMAND,
   PNE_OPT_NB_HT_BUS1_DATA,
   PNE_OPT_NB_HT_BUS1_BUFF,
   PNE_OPT_NB_HT_BUS1_NOP,
   PNE_OPT_NB_HT_BUS2_COMMAND,
   PNE_OPT_NB_HT_BUS2_DATA,
   PNE_OPT_NB_HT_BUS2_BUFF,
   PNE_OPT_NB_HT_BUS2_NOP
};

const hwi_search_t _papi_hwd_p3_preset_map[] = {
   { PAPI_L1_DCM,        {0, {PNE_P3_DCU_LINES_IN,0,0,0},{0,}}},
   { PAPI_L1_ICM,        {0, {PNE_P3_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L2_DCM,        {DERIVED_SUB, {PNE_P3_L2_LINES_IN,PNE_P3_BUS_TRAN_IFETCH_SELF,0,0},{0,}}},
   { PAPI_L2_ICM,        {0, {PNE_P3_BUS_TRAN_IFETCH_SELF,0,0,0},{0,}}},
   { PAPI_L1_TCM,        {0, {PNE_P3_L2_RQSTS_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCM,        {0, {PNE_P3_L2_LINES_IN,0,0,0},{0,}}},
   { PAPI_CA_SHR,        {0, {PNE_P3_L2_RQSTS_SHD,0,0,0},{0,}}},
   { PAPI_CA_CLN,        {0, {PNE_P3_BUS_TRAN_RFO_SELF,0,0,0},{0,}}},
/*   { PAPI_CA_INV,        {0, {PNE_P3_BUS_HITM_DRV,0,0,0},{0,}}},   */
   { PAPI_CA_ITV,        {0, {PNE_P3_BUS_TRAN_INVAL_SELF,0,0,0},{0,}}},
   { PAPI_TLB_IM,        {0, {PNE_P3_ITLB_MISS,0,0,0},{0,}}},
   { PAPI_L1_LDM,        {0, {PNE_P3_L2_LD_TOT,0,0,0},{0},}},
   { PAPI_L1_LDM,        {0, {PNE_P3_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_L2_LDM,        {DERIVED_SUB, {PNE_P3_L2_LINES_IN,PNE_P3_L2_M_LINES_INM,0,0},{0,}}},
   { PAPI_L2_STM,        {0, {PNE_P3_L2_M_LINES_INM,0,0,0},{0,}}},
   { PAPI_BTAC_M,        {0, {PNE_P3_BTB_MISSES,0,0,0},{0,}}},
   { PAPI_HW_INT,        {0, {PNE_P3_HW_INT_RX,0,0,0},{0,}}},
   { PAPI_BR_CN,         {0, {PNE_P3_BR_INST_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_TKN,        {0, {PNE_P3_BR_TAKEN_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_NTK,        {DERIVED_SUB,{PNE_P3_BR_INST_RETIRED,PNE_P3_BR_TAKEN_RETIRED,0,0},{0,}}},
   { PAPI_BR_MSP,        {0, {PNE_P3_BR_MISS_PRED_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_PRC,        {DERIVED_SUB,{PNE_P3_BR_INST_RETIRED,PNE_P3_BR_MISS_PRED_RETIRED,0,0},{0,}}},
   { PAPI_TOT_IIS,       {0, {PNE_P3_INST_DECODED,0,0,0},{0,}}},
   { PAPI_TOT_INS,       {0, {PNE_P3_INST_RETIRED,0,0,0},{0,}}},
   { PAPI_FP_INS,        {0, {PNE_P3_FLOPS,0,0,0},{0,}}},
   { PAPI_BR_INS,        {0, {PNE_P3_BR_INST_RETIRED,0,0,0},{0,}}},
/*   { PAPI_VEC_INS,       {0, {PNE_P3_MMX_INSTR_EXEC,0,0,0},{0,}}},  Says event exists on P2 only  */
   { PAPI_FLOPS,         {DERIVED_PS, {PNE_P3_FLOPS,PNE_P3_CPU_CLK_UNHALTED,0,0},{0,}}},
   { PAPI_RES_STL,       {0, {PNE_P3_RESOURCE_STALLS,0,0,0},{0,}}},
   { PAPI_TOT_CYC,       {0, {PNE_P3_CPU_CLK_UNHALTED,0,0,0},{0,}}},
   { PAPI_IPS,           {DERIVED_PS, {PNE_P3_INST_RETIRED,PNE_P3_CPU_CLK_UNHALTED,0,0},{0,}}},
   { PAPI_L1_DCH,        {DERIVED_SUB, {PNE_P3_DATA_MEM_REFS,PNE_P3_DCU_LINES_IN,0,0},{0,}}},
   { PAPI_L1_DCA,        {0, {PNE_P3_DATA_MEM_REFS,0,0,0},{0,}}},
   { PAPI_L2_DCA,        {DERIVED_ADD, {PNE_P3_L2_LD_TOT,PNE_P3_L2_ST_TOT,0,0},{0,}}},
   { PAPI_L2_DCR,        {0, {PNE_P3_L2_LD_TOT,0,0,0},{0,}}},
   { PAPI_L2_DCW,        {0, {PNE_P3_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_L1_ICH,        {DERIVED_SUB, {PNE_P3_IFU_IFETCH,PNE_P3_L2_IFETCH_TOT,0,0},{0,}}},
   { PAPI_L2_ICH,        {DERIVED_SUB, {PNE_P3_L2_IFETCH_TOT,PNE_P3_BUS_TRAN_IFETCH_SELF,0,0},{0,}}},
   { PAPI_L1_ICA,        {0, {PNE_P3_IFU_IFETCH,0,0,0},{0,}}},
   { PAPI_L2_ICA,        {0, {PNE_P3_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L1_ICR,        {0, {PNE_P3_IFU_IFETCH,0,0,0},{0,}}},
   { PAPI_L2_ICR,        {0, {PNE_P3_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCH,        {DERIVED_SUB, {PNE_P3_L2_RQSTS_TOT,PNE_P3_L2_LINES_IN,0,0},{0,}}},
   { PAPI_L1_TCA,        {DERIVED_ADD, {PNE_P3_DATA_MEM_REFS,PNE_P3_IFU_IFETCH,0,0},{0,}}},
   { PAPI_L2_TCA,        {0, {PNE_P3_L2_RQSTS_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCR,        {DERIVED_ADD, {PNE_P3_L2_LD_TOT,PNE_P3_L2_IFETCH_TOT,0,0},{0,}}},
   { PAPI_L2_TCW,        {0, {PNE_P3_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_FML_INS,       {0, {PNE_P3_MUL,0,0,0},{0,}}},
   { PAPI_FDV_INS,       {0, {PNE_P3_DIV,0,0,0},{0,}}},
   { 0,                  {0, {0,0,0,0},{0,}}}
};

const hwi_search_t _papi_hwd_p2_preset_map[] = {
   { PAPI_L1_DCM,        {0, { PNE_P2_DCU_LINES_IN,0,0,0},{0,}}},
   { PAPI_L1_ICM,        {0, { PNE_P2_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L2_DCM,        {DERIVED_SUB, { PNE_P2_L2_LINES_IN,PNE_P2_BUS_TRAN_IFETCH_SELF,0,0},{0,}}},
   { PAPI_L2_ICM,        {0, { PNE_P2_BUS_TRAN_IFETCH_SELF,0,0,0},{0,}}},
   { PAPI_L1_TCM,        {0, { PNE_P2_L2_RQSTS_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCM,        {0, { PNE_P2_L2_LINES_IN,0,0,0},{0,}}},
   { PAPI_CA_SHR,        {0, { PNE_P2_L2_RQSTS_SHD,0,0,0},{0,}}},
   { PAPI_CA_CLN,        {0, { PNE_P2_BUS_TRAN_RFO_SELF,0,0,0},{0,}}},
/*   { PAPI_CA_INV,        {0, { PNE_P2_BUS_HITM_DRV,0,0,0},{0,}}},   */
   { PAPI_CA_ITV,        {0, { PNE_P2_BUS_TRAN_INVAL_SELF,0,0,0},{0,}}},
   { PAPI_TLB_IM,        {0, { PNE_P2_ITLB_MISS,0,0,0},{0,}}},
   { PAPI_L1_LDM,        {0, { PNE_P2_L2_LD_TOT,0,0,0},{0,}}},
   { PAPI_L1_LDM,        {0, { PNE_P2_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_L2_LDM,        {DERIVED_SUB, { PNE_P2_L2_LINES_IN,PNE_P2_L2_M_LINES_INM,0,0},{0,}}},
   { PAPI_L2_STM,        {0, { PNE_P2_L2_M_LINES_INM,0,0,0},{0,}}},
   { PAPI_BTAC_M,        {0, { PNE_P2_BTB_MISSES,0,0,0},{0,}}},
   { PAPI_HW_INT,        {0, { PNE_P2_HW_INT_RX,0,0,0},{0,}}},
   { PAPI_BR_CN,         {0, { PNE_P2_BR_INST_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_TKN,        {0, { PNE_P2_BR_TAKEN_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_NTK,        {DERIVED_SUB, { PNE_P2_BR_INST_RETIRED,PNE_P2_BR_TAKEN_RETIRED,0,0},{0,}}},
   { PAPI_BR_MSP,        {0, { PNE_P2_BR_MISS_PRED_RETIRED,0,0,0},{0,}}},
   { PAPI_BR_PRC,        {DERIVED_SUB, { PNE_P2_BR_INST_RETIRED,PNE_P2_BR_MISS_PRED_RETIRED,0,0},{0,}}},
   { PAPI_TOT_IIS,       {0, { PNE_P2_INST_DECODED,0,0,0},{0,}}},
   { PAPI_TOT_INS,       {0, { PNE_P2_INST_RETIRED,0,0,0},{0,}}},
   { PAPI_FP_INS,        {0, { PNE_P2_FLOPS,0,0,0},{0,}}},
   { PAPI_BR_INS,        {0, { PNE_P2_BR_INST_RETIRED,0,0,0},{0,}}},
   { PAPI_VEC_INS,       {0, { PNE_P2_MMX_INSTR_EXEC,0,0,0},{0,}}},
   { PAPI_FLOPS,         {DERIVED_PS, { PNE_P2_FLOPS,PNE_P2_CPU_CLK_UNHALTED,0,0},{0,}}},
   { PAPI_RES_STL,       {0, { PNE_P2_RESOURCE_STALLS,0,0,0},{0,}}},
   { PAPI_TOT_CYC,       {0, { PNE_P2_CPU_CLK_UNHALTED,0,0,0},{0,}}},
   { PAPI_IPS,           {DERIVED_PS, { PNE_P2_INST_RETIRED,PNE_P2_CPU_CLK_UNHALTED,0,0},{0,}}},
   { PAPI_L1_DCH,        {DERIVED_SUB, { PNE_P2_DATA_MEM_REFS,PNE_P2_DCU_LINES_IN,0,0},{0,}}},
   { PAPI_L1_DCA,        {0, { PNE_P2_DATA_MEM_REFS,0,0,0},{0,}}},
   { PAPI_L2_DCA,        {DERIVED_ADD, { PNE_P2_L2_LD_TOT,PNE_P2_L2_ST_TOT,0,0},{0,}}},
   { PAPI_L2_DCR,        {0, { PNE_P2_L2_LD_TOT,0,0,0},{0,}}},
   { PAPI_L2_DCW,        {0, { PNE_P2_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_L1_ICH,        {DERIVED_SUB, { PNE_P2_IFU_IFETCH,PNE_P2_L2_IFETCH_TOT,0,0},{0,}}},
   { PAPI_L2_ICH,        {DERIVED_SUB, { PNE_P2_L2_IFETCH_TOT,PNE_P2_BUS_TRAN_IFETCH_SELF,0,0},{0,}}},
   { PAPI_L1_ICA,        {0, { PNE_P2_IFU_IFETCH,0,0,0},{0,}}},
   { PAPI_L2_ICA,        {0, { PNE_P2_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L1_ICR,        {0, { PNE_P2_IFU_IFETCH,0,0,0},{0,}}},
   { PAPI_L2_ICR,        {0, { PNE_P2_L2_IFETCH_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCH,        {DERIVED_SUB, { PNE_P2_L2_RQSTS_TOT,PNE_P2_L2_LINES_IN,0,0},{0,}}},
   { PAPI_L1_TCA,        {DERIVED_ADD, { PNE_P2_DATA_MEM_REFS,PNE_P2_IFU_IFETCH,0,0},{0,}}},
   { PAPI_L2_TCA,        {0, { PNE_P2_L2_RQSTS_TOT,0,0,0},{0,}}},
   { PAPI_L2_TCR,        {DERIVED_ADD, { PNE_P2_L2_LD_TOT,PNE_P2_L2_IFETCH_TOT,0,0},{0,}}},
   { PAPI_L2_TCW,        {0, { PNE_P2_L2_ST_TOT,0,0,0},{0,}}},
   { PAPI_FML_INS,       {0, { PNE_P2_MUL,0,0,0},{0,}}},
   { PAPI_FDV_INS,       {0, { PNE_P2_DIV,0,0,0},{0,}}},
   { 0,                  {0, { 0,0,0,0},{0,}}}
};

const hwi_search_t _papi_hwd_ath_preset_map[] = {
   { PAPI_L1_DCM,            {0, { PNE_ATH_DC_MISSES,0,0,0},{0,}}},
   { PAPI_L1_ICM,            {0, { PNE_ATH_IC_MISSES,0,0,0},{0,}}},
   { PAPI_L2_DCM,            {0, { PNE_ATH_SYS_DC_REFILLS_TOT,0,0,0},{0,}}},
   { PAPI_L2_ICM,            {0, { PNE_ATH_SYS_IC_REFILLS,0,0,0},{0,}}},
   { PAPI_L1_TCM,            {DERIVED_ADD, { PNE_ATH_DC_MISSES,PNE_ATH_IC_MISSES,0,0},{0,}}},
   { PAPI_L2_TCM,            {DERIVED_ADD, { PNE_ATH_SYS_DC_REFILLS_TOT,PNE_ATH_SYS_IC_REFILLS,0,0},{0,}}},
   { PAPI_TLB_DM,            {0, { PNE_ATH_L1_AND_L2_DTLB_MISSES,0,0,0},{0,}}},
   { PAPI_TLB_IM,            {0, { PNE_ATH_L2_ITLB_MISSES,0,0,0},{0,}}},
   { PAPI_TLB_TL,            {DERIVED_ADD, { PNE_ATH_L1_AND_L2_DTLB_MISSES,PNE_ATH_L2_ITLB_MISSES,0,0},{0,}}},
   { PAPI_L1_LDM,            {0, { PNE_ATH_L2_DC_REFILLS_MOD,0,0,0},{0,}}},
   { PAPI_L1_STM,            {0, { PNE_ATH_L2_DC_REFILLS_TOT,0,0,0},{0,}}},
   { PAPI_L2_LDM,            {0, { PNE_ATH_SYS_DC_REFILLS_MOD,0,0,0},{0,}}},
   { PAPI_L2_STM,            {0, { PNE_ATH_SYS_DC_REFILLS_TOT,0,0,0},{0,}}},
   { PAPI_HW_INT,            {0, { PNE_ATH_TAKEN_HARDWARE_INTS,0,0,0},{0,}}},
   { PAPI_BR_UCN,            {0, { PNE_ATH_RET_FAR_CONTROL_TRANSFERS,0,0,0},{0,}}},
   { PAPI_BR_CN,             {0, { PNE_ATH_RET_BR,0,0,0},{0,}}},
   { PAPI_BR_TKN,            {0, { PNE_ATH_RET_TAKEN_BR,0,0,0},{0,}}},
   { PAPI_BR_NTK,            {DERIVED_SUB, { PNE_ATH_RET_TAKEN_BR,PNE_ATH_RET_BR,0,0},{0,}}},
   { PAPI_BR_MSP,            {0, { PNE_ATH_RET_BR_MIS,0,0,0},{0,}}},
   { PAPI_BR_PRC,            {DERIVED_SUB, { PNE_ATH_RET_BR,PNE_ATH_RET_BR_MIS,0,0},{0,}}},
   { PAPI_TOT_INS,           {0, { PNE_ATH_RET_INSTRUCTIONS,0,0,0},{0,}}},
   { PAPI_BR_INS,            {0, { PNE_ATH_RET_TAKEN_BR,0,0,0},{0,}}},
//   { PAPI_VEC_INS,           {0, { PNE_ATH_DCU_LINES_IN,0,0,0},{0,}}},
   { PAPI_RES_STL,           {0, { PNE_ATH_ALL_QUIET_STALL,0,0,0},{0,}}},
   { PAPI_TOT_CYC,           {0, { PNE_ATH_TOT_CYC,0,0,0},{0,}}},
   { PAPI_IPS,               {DERIVED_PS, { PNE_ATH_RET_INSTRUCTIONS,PNE_ATH_TOT_CYC,0,0},{0,}}},
   { PAPI_L1_DCH,            {DERIVED_SUB, { PNE_ATH_DC_ACCESSES,PNE_ATH_DC_MISSES,0,0},{0,}}},
   { PAPI_L2_DCH,            {DERIVED_SUB, { PNE_ATH_DC_MISSES,PNE_ATH_SYS_DC_REFILLS_TOT,0,0},{0,}}},
   { PAPI_L1_DCA,            {0, { PNE_ATH_DC_ACCESSES,0,0,0},{0,}}},
   { PAPI_L2_DCA,            {0, { PNE_ATH_DC_MISSES,0,0,0},{0,}}},
   { PAPI_L2_DCR,            {DERIVED_ADD, { PNE_ATH_L2_DC_REFILLS_OWN,PNE_ATH_L2_DC_REFILLS_EXC,PNE_ATH_L2_DC_REFILLS_SHR,0},{0,}}},
   { PAPI_L2_DCW,            {DERIVED_ADD, { PNE_ATH_L2_DC_REFILLS_MOD,PNE_ATH_L2_DC_REFILLS_INV,0,0},{0,}}},
   { PAPI_L1_ICA,            {0, { PNE_ATH_IC_FETCHES,0,0,0},{0,}}},
   { PAPI_L2_ICA,            {0, { PNE_ATH_IC_MISSES,0,0,0},{0,}}},
   { PAPI_L1_ICR,            {0, { PNE_ATH_IC_FETCHES,0,0,0},{0,}}},
   { PAPI_L1_TCA,            {DERIVED_ADD, { PNE_ATH_DC_ACCESSES,PNE_ATH_IC_FETCHES,0,0},{0,}}},
   { 0,                      {0, { 0,0,0,0},{0,}}}
};

const hwi_search_t _papi_hwd_opt_preset_map[] = {
   { PAPI_L1_DCM,            {0, {0x0041,0,0,0},{0,}}},
   { PAPI_L1_ICM,            {0, {0x0081,0,0,0},{0,}}},
   { PAPI_L2_DCM,            {0, {0x027E,0,0,0},{0,}}},
   { PAPI_L2_ICM,            {0, {0x017E,0,0,0},{0,}}},
/* { PAPI_L1_TCM,            {DERIVED_ADD, {0x0041,0x0081,0,0},{0,}}},  */
   { PAPI_L2_TCM,            {0, {0x037E,0,00,},{0,}}},
  /* Need to think a lot about these events */
/* { PAPI_CA_SNP,            {0, {0,0,0,0},{0,}}}, */
/* { PAPI_CA_SHR,            {0, {0,0,0,0},{0,}}}, */
/* { PAPI_CA_CLN,            {0, {0,0,0,0},{0,}}}, */
/* { PAPI_CA_INV,            {0, {0,0,0,0},{0,}}}, */
/* { PAPI_CA_ITV,            {0, {0,0,0,0},{0,}}}, */
   { PAPI_FPU_IDL,           {0, {0x01,0,0,0},{0,}}},
   { PAPI_TLB_DM,            {0, {0x46,0,0,0},{0,}}},
   { PAPI_TLB_IM,            {0, {0x85,0,0,0},{0,}}},
/* { PAPI_TLB_TL,            {DERIVED_ADD, {0x46,0x85,0,0},{0,}}},
   { PAPI_MEM_SCY,           {0, {0xD8,0,0,0},{0,}}},
   { PAPI_STL_ICY,           {0, {0xD0,0,0,0},{0,}}},
   { PAPI_HW_INT,            {0, {0xCF,0,0,0},{0,}}},
   { PAPI_BR_TKN,            {0, {0xC4,0,0,0},{0,}}},
   { PAPI_BR_MSP,            {0, {0xC3,0,0,0},{0,}}},
   { PAPI_TOT_INS,           {0, {0xC0,0,0,0},{0,}}},
   { PAPI_FP_INS,            {0, {0x0300,0,0,0},{0,}}},
   { PAPI_BR_INS,            {0, {0xC2,0,0,0},{0,}}},
   { PAPI_VEC_INS,           {0, {0x0ECB,0,0,0},{0,}}},
   { PAPI_RES_STL,           {0, {0xD1,0,0,0},{0,}}},
   { PAPI_FP_STAL,           {0, {0x01,0,0,0},{0,}}},
   { PAPI_TOT_CYC,           {0, {0xC0,0,0,0},{0,}}},
/* { PAPI_L1_DCH,            {DERIVED_SUB, {0x40,0x41,0,0},{0,}}}, */
   { PAPI_L1_DCA,            {0, {0x0040,0,0,0},{0,}}},
   { PAPI_L2_DCH,            {0, {0x1F42,0,0,0},{0,}}},
   { PAPI_L2_DCA,            {0, {0x0041,0,0,0},{0,}}},
   { PAPI_FML_INS,           {0, {0x0100,0,0,0},{0,}}},
   { PAPI_FAD_INS,           {0, {0x0200,0,0,0},{0,}}},
   { 0,                      {0, { 0,0,0,0},{0,}}}
};
 
/* The notes/descriptions of these events have sometimes been truncated */
/* Please see the architecture's manual for any clarifications.         */

const native_event_entry_t _papi_hwd_pentium3_native_map[] = {
  { "DATA_MEM_REFS",
    "All loads/stores from/to any memory type.",
    { CNTR2|CNTR1, 0x43}},
  { "DCU_LINES_IN",
    "Total lines allocated in the DCU.",
    { CNTR2|CNTR1, 0x45}},
  { "DCU_M_LINES_IN",
    "Number of M state lines allocated in the DCU.",
    { CNTR2|CNTR1, 0x46}},
  { "DCU_M_LINES_OUT",
    "Number of M state lines evicted from the DCU.",
    { CNTR2|CNTR1, 0x47}},
  { "DCU_MISS_OUTSTANDING",
    "Weighted no. of cycles while a DCU miss is outstanding, incremented by the no. of outstanding cache misses at any particular time.",
    { CNTR2|CNTR1, 0x48}},
  { "IFU_IFETCH",
    "Number of instruction fetches, both cacheable and noncacheable, including UC fetches.",
    { CNTR2|CNTR1, 0x80}},
  { "IFU_IFETCH_MISS",
    "Number of instruction fetch misses including UC accesses.",
    { CNTR2|CNTR1, 0x81}},
  { "ITLB_MISS",
    "Number of ITLB misses.",
    { CNTR2|CNTR1, 0x85}},
  { "IFU_MEM_STALL",
    "Number of cycles instruction fetch is stalled, for any reason, including IFU cache misses, ITLB misses, ITLB faults, and other minor stalls.",
    { CNTR2|CNTR1, 0x86}},
  { "ILD_STALL",
    "Number of cycles the instruction length decoder is stalled.",
    { CNTR2|CNTR1, 0x87}},
  { "L2_IFETCH_MOD",
    "Number of fetches from a modified line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x828}},
  { "L2_IFETCH_EXC",
    "Number of fetches from a exclusive line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x428}},
  { "L2_IFETCH_SHD",
    "Number of fetches from a shared line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x228}},
  { "L2_IFETCH_INV",
    "Number of fetches from a invalid line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x128}},
  { "L2_IFETCH_TOT",
    "Total number of L2 instruction fetches.",
    { CNTR2|CNTR1, 0xf28}},
  { "L2_LD_MOD",
    "Number of loads from a modified line of the L2 data cache.",
    { CNTR2|CNTR1, 0x829}},
  { "L2_LD_EXC",
    "Number of loads from an exclusive line of the L2 data cache.",
    { CNTR2|CNTR1, 0x429}},
  { "L2_LD_SHD",
    "Number of loads from a shared line of the L2 data cache.",
    { CNTR2|CNTR1, 0x229}},
  { "L2_LD_INV",
    "Number of loads from an invalid line of the L2 data cache.",
    { CNTR2|CNTR1, 0x129}},
  { "L2_LD_TOT",
    "Total number of L2 data loads.",
    { CNTR2|CNTR1, 0xf29}},
  { "L2_ST_MOD",
    "Number of stores to a modified line of the L2 data cache.",
    { CNTR2|CNTR1, 0x82a}},
  { "L2_ST_EXC",
    "Number of stores to a exclusive line of the L2 data cache.",
    { CNTR2|CNTR1, 0x42a}},
  { "L2_ST_SHD",
    "Number of stores to a shared line of the L2 data cache.",
    { CNTR2|CNTR1, 0x22a}},
  { "L2_ST_INV",
    "Number of stores to a invalid line of the L2 data cache.",
    { CNTR2|CNTR1, 0x12a}},
  { "L2_ST_TOT",
    "Total number of L2 data stores.",
    { CNTR2|CNTR1, 0xf2a}},
  { "L2_LINES_IN",
    "Number of lines allocated in the L2.",
    { CNTR2|CNTR1, 0x24}},
  { "L2_LINES_OUT",
    "Number of lines removed fromo the L2 for any reason.",
    { CNTR2|CNTR1, 0x26}},
  { "L2_M_LINES_INM",
    "Number of modified lines allocated in the L2.",
    { CNTR2|CNTR1, 0x25}},
  { "L2_M_LINES_OUTM",
    "Number of modified lines removed from the L2 for any reason.",
    { CNTR2|CNTR1, 0x27}},
  { "L2_RQSTS_MOD",
    "Total number of L2 requests to a modified line.",
    { CNTR2|CNTR1, 0x82e}},
  { "L2_RQSTS_EXC",
    "Total number of L2 requests to an exclusive line.",
    { CNTR2|CNTR1, 0x42e}},
  { "L2_RQSTS_SHD",
    "Total number of L2 requests to a shared line.",
    { CNTR2|CNTR1, 0x22e}},
  { "L2_RQSTS_INV",
    "Total number of L2 requests to an invalid line.",
    { CNTR2|CNTR1, 0x12e}},
  { "L2_RQSTS_TOT",
    "Total number of L2 requests.",
    { CNTR2|CNTR1, 0xf2e}},
  { "L2_ADS",
    "Number of L2 address strobes.",
    { CNTR2|CNTR1, 0x21}},
  { "L2_DBS_BUSY",
    "Number of cycles the L2 cache data bus was busy.",
    { CNTR2|CNTR1, 0x22}},
  { "L2_DBS_BUSY_RD",
    "Number of cycles the data bus was busy transferring read data from the L2 to the processor.",
    { CNTR2|CNTR1, 0x23}},
  { "BUS_DRDY_CLOCKS_SELF",
    "Number of clock cycles during which the processor is driving DRDY#.",
    { CNTR2|CNTR1, 0x62}},
  { "BUS_DRDY_CLOCKS_ANY",
    "Number of clock cycles during which any agent is driving DRDY#.",
    { CNTR2|CNTR1, 0x2062}},
  { "BUS_LOCK_CLOCKS_SELF",
    "Number of clock cycles during which the processor is driving LOCK#.",
    { CNTR2|CNTR1, 0x63}},
  { "BUS_LOCK_CLOCKS_ANY",
    "Number of clock cycles during which any agent is driving LOCK#.",
    { CNTR2|CNTR1, 0x2063}},
  { "BUS_REQ_OUTSTANDING",
    "Number of bus outstanding bus requests.",
    { CNTR2|CNTR1, 0x60}},
  { "BUS_TRAN_BRD_SELF",
    "Number of burst read transactions by the processor.",
    { CNTR2|CNTR1, 0x65}},
  { "BUS_TRAN_BRD_ANY",
    "Number of burst read transactions by any agent.",
    { CNTR2|CNTR1, 0x2065}},
  { "BUS_TRAN_RFO_SELF",
    "Number of completed read for ownership transactions by the processor.",
    { CNTR2|CNTR1, 0x66}},
  { "BUS_TRAN_RFO_ANY",
    "Number of completed read for ownership transactions by any agent.",
    { CNTR2|CNTR1, 0x2066}},
  { "BUS_TRANS_WB_SELF",
    "Number of completed write back transactions by the processor.",
    { CNTR2|CNTR1, 0x67}},
  { "BUS_TRANS_WB_ANY",
    "Number of completed write back transactions by any agent.",
    { CNTR2|CNTR1, 0x2067}},
  { "BUS_TRAN_IFETCH_SELF",
    "Number of completed instruction fetch transactions by the processor.",
    { CNTR2|CNTR1, 0x68}},
  { "BUS_TRAN_IFETCH_ANY",
    "Number of completed instruction fetch transactions by any agent.",
    { CNTR2|CNTR1, 0x2068}},
  { "BUS_TRAN_INVAL_SELF",
    "Number of completed invalidate transactions by the processor.",
    { CNTR2|CNTR1, 0x69}},
  { "BUS_TRAN_INVAL_ANY",
    "Number of completed invalidate transactions by any agent.",
    { CNTR2|CNTR1, 0x2069}},
  { "BUS_TRAN_PWR_SELF",
    "Number of completed partial write transactions by the processor.",
    { CNTR2|CNTR1, 0x6a}},
  { "BUS_TRAN_PWR_ANY",
    "Number of completed partial write transactions by any agent.",
    { CNTR2|CNTR1, 0x206a}},
  { "BUS_TRANS_P_SELF",
    "Number of completed partial transactions by the processor.",
    { CNTR2|CNTR1, 0x6b}},
  { "BUS_TRANS_P_ANY",
    "Number of completed partial transactions by any agent.",
    { CNTR2|CNTR1, 0x206b}},
  { "BUS_TRANS_IO_SELF",
    "Number of completed I/O transactions by the processor.",
    { CNTR2|CNTR1, 0x6c}},
  { "BUS_TRANS_IO_ANY",
    "Number of completed I/O transactions by any agent.",
    { CNTR2|CNTR1, 0x206c}},
  { "BUS_TRAN_DEF_SELF",
    "Number of completed deferred transactions by the processor.",
    { CNTR2|CNTR1, 0x6d}},
  { "BUS_TRAN_DEF_ANY",
    "Number of completed deferred transactions by any agent.",
    { CNTR2|CNTR1, 0x206d}},
  { "BUS_TRAN_BURST_SELF",
    "Number of completed burst transactions by the processor.",
    { CNTR2|CNTR1, 0x6e}},
  { "BUS_TRAN_BURST_ANY",
    "Number of completed burst transactions by any agent.",
    { CNTR2|CNTR1, 0x206e}},
  { "BUS_TRAN_ANY_SELF",
    "Number of completed bus transactions by the processor.",
    { CNTR2|CNTR1, 0x70}},
  { "BUS_TRAN_ANY_ANY",
    "Number of completed bus transactions by any agent.",
    { CNTR2|CNTR1, 0x2070}},
  { "BUS_TRAN_MEM_SELF",
    "Number of completed memory transactions by the processor.",
    { CNTR2|CNTR1, 0x6f}},
  { "BUS_TRAN_MEM_ANY",
    "Number of completed memory transactions by any agent.",
    { CNTR2|CNTR1, 0x206f}},
  { "BUS_DATA_RCV",
    "Number of bus clock cycles during which this processor is receiving data.",
    { CNTR2|CNTR1, 0x64}},
  { "BUS_BNR_DRV",
    "Number of bus clock cycles during which this processor is driving the BNR# pin.",
    { CNTR2|CNTR1, 0x61}},
  { "BUS_HIT_DRV",
    "Number of bus clock cycles during which this processor is driving the HIT# pin.",
    { CNTR2|CNTR1, 0x7a}},
  { "BUS_HITM_DRV",
    "Number of bus clock cycles during which this processor is driving the HITM# pin.",
    { CNTR2|CNTR1, 0x7b}},
  { "BUS_SNOOP_STALL",
    "Number of clock cycles during which the bus is snoop stalled.",
    { CNTR2|CNTR1, 0x7e}},
  { "FLOPS",
    "Number of computational floating-point operations retired.",
    { CNTR1, 0xc1}},
  { "FP_COMP_OPS_EXE",
    "Number of computational floating-point operations executed.",
    { CNTR1, 0x10}},
  { "FP_ASSIST",
    "Number of floating-point exception cases handled by microcode.",
    { CNTR2, 0x11}},
  { "MUL",
    "Number of integer and floating point multiplies.",
    { CNTR2, 0x12}},
  { "DIV",
    "Number of integer and floating point divides.",
    { CNTR2, 0x13}},
  { "CYCLES_DIV_BUSY",
    "Number of cycles during which the divider is busy and cannot accept new divides.",
    { CNTR1, 0x14}},
  { "LD_BLOCKS",
    "Number of load operations delayed due to store buffer blocks.",
    { CNTR2|CNTR1, 0x3}},
  { "SB_DRAINS",
    "Number of store buffer drain cycles.",
    { CNTR2|CNTR1, 0x4}},
  { "MISALIGN_MEM_REF",
    "Number of misaligned data memory references.",
    { CNTR2|CNTR1, 0x5}},
  { "EMON_KNI_PREF_DISPATCHED_PREFETCHED_NTA",
    "Number of Streaming SIMD extensions prefetch NTA dispatched.",
    { CNTR2|CNTR1, 0x7}},
  { "EMON_KNI_PREF_DISPATCHED_PREFETCHED_T1",
    "Number of Streaming SIMD extensions prefetch T1 dispatched.",
    { CNTR2|CNTR1, 0x107}},
  { "EMON_KNI_PREF_DISPATCHED_PREFETCHED_T2",
    "Number of Streaming SIMD extensions prefetch T2 dispatched.",
    { CNTR2|CNTR1, 0x207}},
  { "EMON_KNI_PREF_DISPATCHED_WEAKLY_ORDERED_STORES",
    "Number of Streaming SIMD extensions prefetch weakly ordered stores dispatched.",
    { CNTR2|CNTR1, 0x307}},
  { "EMON_KNI_PREF_MISS_PREFETCHED_NTA",
    "Number of prefetch NTA instructions that miss all caches.",
    { CNTR2|CNTR1, 0x4b}},
  { "EMON_KNI_PREF_MISS_PREFETCHED_T1",
    "Number of prefetch T1instructions that miss all caches.",
    { CNTR2|CNTR1, 0x14b}},
  { "EMON_KNI_PREF_MISS_PREFETCHED_T2",
    "Number of prefetch T2 instructions that miss all caches.",
    { CNTR2|CNTR1, 0x24b}},
  { "EMON_KNI_PREF_MISS_WEAKLY_ORDERED_STORES",
    "Number of weakly-ordered instructions that miss all caches.",
    { CNTR2|CNTR1, 0x34b}},
  { "INST_RETIRED",
    "Number of instructions retired.",
    { CNTR2|CNTR1, 0xc0}},
  { "UOPS_RETIRED",
    "Number of uops retired.",
    { CNTR2|CNTR1, 0xc2}},
  { "INST_DECODED",
    "Number of instructions decoded.",
    { CNTR2|CNTR1, 0xd0}},
  { "EMON_KNI_INST_RETIRED_PACKED_AND_SCALAR",
    "Number of packed and scalar Straming SIMD extensions retired.",
    { CNTR2|CNTR1, 0xd8}},
  { "EMON_KNI_INST_RETIRED_SCALAR",
    "Number of scalar Straming SIMD extensions retired.",
    { CNTR2|CNTR1, 0x1d8}},
  { "EMON_KNI_COMP_INST_RET_PACKED_AND_SCALAR",
    "Number of packed and scalar Straming SIMD computation instructions retired.",
    { CNTR2|CNTR1, 0xd9}},
  { "EMON_KNI_COMP_INST_RET_SCALAR",
    "Number of scalar Straming SIMD computation instructions retired.",
    { CNTR2|CNTR1, 0x1d9}},
  { "HW_INT_RX",
    "Number of hardware interrupts received.",
    { CNTR2|CNTR1, 0xc8}},
  { "CYCLES_INT_MASKED",
    "Number of processor cycles to which interrupts are enabled.",
    { CNTR2|CNTR1, 0xc6}},
  { "CYCLES_INT_PENDING_AND_MASKED",
    "Number of processor cycles for which interrupts are disabled and interrupts are pending.",
    { CNTR2|CNTR1, 0xc7}},
  { "BR_INST_RETIRED",
    "Number of branch instructions retired.",
    { CNTR2|CNTR1, 0xc4}},
  { "BR_MISS_PRED_RETIRED",
    "Number of mispredicted branches retired.",
    { CNTR2|CNTR1, 0xc5}},
  { "BR_TAKEN_RETIRED",
    "Number of taken branches retired.",
    { CNTR2|CNTR1, 0xc9}},
  { "BR_MISS_PRED_TAKEN_RET",
    "Number of mispredictions branches retired.",
    { CNTR2|CNTR1, 0xca}},
  { "BR_INST_DECODED",
    "Number of branch instructions decoded.",
    { CNTR2|CNTR1, 0xe0}},
  { "BTB_MISSES",
    "Number of branches for which the BTB did not produce a prediction.",
    { CNTR2|CNTR1, 0xe2}},
  { "BR_BOGUS",
    "Number of bogus branches.",
    { CNTR2|CNTR1, 0xe4}},
  { "BACLEARS",
    "Number of times BACLEAR is asserted. This is the number of times that a static branch prediction was made, in which the branch decoder decided to make a branch prediction because the BTB did not.",
    { CNTR2|CNTR1, 0xe6}},
  { "RESOURCE_STALLS",
    "Incremented by 1 during every cycle for which there is a resource related stall.",
    { CNTR2|CNTR1, 0xa2}},
  { "PARTIAL_RAT_STALLS",
    "Number of cycles or events for partial stalls.  Includes flag partial stalls.",
    { CNTR2|CNTR1, 0xd2}},
  { "SEGMENT_REG_LOADS",
    "Number of segment register loads.",
    { CNTR2|CNTR1, 0x06}},
  { "CPU_CLK_UNHALTED",
    "Number of cycles during which the processor is not halted.",
    { CNTR2|CNTR1, 0x79}},
  { "MMX_SAT_INSTR_EXEC",
    "Number of MMX Saturating instructions executed.",
    { CNTR2|CNTR1, 0xb1}},
  { "MMX_UOPS_EXEC",
    "Number of MMX uops executed.",
    { CNTR2|CNTR1, 0xfb2}},
  { "MMX_INSTR_TYPE_EXEC_MUL",
    "Number of MMX packed multiply instructions executed.",
    { CNTR2|CNTR1, 0x1b3}},
  { "MMX_INSTR_TYPE_EXEC_SHIFT",
    "Number of MMX packed shift instructions executed.",
    { CNTR2|CNTR1, 0x2b3}},
  { "MMX_INSTR_TYPE_EXEC_PACK_OPS",
    "Number of MMX pack operation instructions executed.",
    { CNTR2|CNTR1, 0x4b3}},
  { "MMX_INSTR_TYPE_EXEC_UNPACK_OPS",
    "Number of MMX unpack operation instructions executed.",
    { CNTR2|CNTR1, 0x8b3}},
  { "MMX_INSTR_TYPE_EXEC_LOGICAL",
    "Number of MMX packed logical instructions executed.",
    { CNTR2|CNTR1, 0x10b3}},
  { "MMX_INSTR_TYPE_EXEC_ARITHMETIC",
    "Number of MMX packed arithmetic instructions executed.",
    { CNTR2|CNTR1, 0x20b3}},
  { "FP_MMX_TRANS_MMX_TO_FP",
    "Transitions from MMX instruction to floating-point instructions.",
    { CNTR2|CNTR1, 0xcc}},
  { "FP_MMX_TRANS_FP_TO_MMX",
    "Transitions from floating-point instructions to MMX instructions.",
    { CNTR2|CNTR1, 0x1cc}},
  { "MMX_ASSIST",
    "Number of MMX Assists, ie the number of EMMS instructions executed.",
    { CNTR2|CNTR1, 0xcd}},
  { "SEG_RENAME_STALLS_ES",
    "Number of Segment Register ES Renaming stalls.",
    { CNTR2|CNTR1, 0x1d4}},
  { "SEG_RENAME_STALLS_DS",
    "Number of Segment Register DS Renaming stalls.",
    { CNTR2|CNTR1, 0x2d4}},
  { "SEG_RENAME_STALLS_FS",
    "Number of Segment Register FS Renaming stalls.",
    { CNTR2|CNTR1, 0x4d4}},
  { "SEG_RENAME_STALLS_GS",
    "Number of Segment Register GS Renaming stalls.",
    { CNTR2|CNTR1, 0x8d4}},
  { "SEG_RENAME_STALLS_TOT",
    "Total Number of Segment Register Renaming stalls.",
    { CNTR2|CNTR1, 0xfd4}},
  { "SEG_REG_RENAMES_ES",
    "Number of Segment Register ES Renames.",
    { CNTR2|CNTR1, 0x1d5}},
  { "SEG_REG_RENAMES_DS",
    "Number of Segment Register DS Renames.",
    { CNTR2|CNTR1, 0x2d5}},
  { "SEG_REG_RENAMES_FS",
    "Number of Segment Register FS Renames.",
    { CNTR2|CNTR1, 0x4d5}},
  { "SEG_REG_RENAMES_GS",
    "Number of Segment Register GS Renames.",
    { CNTR2|CNTR1, 0x8d5}},
  { "SEG_REG_RENAMES_TOT",
    "Total number of Segment Register Renames.",
    { CNTR2|CNTR1, 0xfd5}},
  { "RET_SEG_RENAMES",
    "Number of segment register rename events retired.",
    { CNTR2|CNTR1, 0xd6}}
};

const native_event_entry_t _papi_hwd_p2_native_map[] = {
  { "DATA_MEM_REFS",
    "All loads/stores from/to any memory type.",
    { CNTR2|CNTR1, 0x43}},
  { "DCU_LINES_IN",
    "Total lines allocated in the DCU.",
    { CNTR2|CNTR1, 0x45}},
  { "DCU_M_LINES_IN",
    "Number of M state lines allocated in the DCU.",
    { CNTR2|CNTR1, 0x46}},
  { "DCU_M_LINES_OUT",
    "Number of M state lines evicted from the DCU.",
    { CNTR2|CNTR1, 0x47}},
  { "DCU_MISS_OUTSTANDING",
    "Weighted no. of cycles while a DCU miss is outstanding, incremented by the
no. of outstanding cache misses at any particular time.",
    { CNTR2|CNTR1, 0x48}},
  { "IFU_IFETCH",
    "Number of instruction fetches, both cacheable and noncacheable, including U
C fetches.",
    { CNTR2|CNTR1, 0x80}},
  { "IFU_IFETCH_MISS",
    "Number of instruction fetch misses including UC accesses.",
    { CNTR2|CNTR1, 0x81}},
  { "ITLB_MISS",
    "Number of ITLB misses.",
    { CNTR2|CNTR1, 0x85}},
  { "IFU_MEM_STALL",
    "Number of cycles instruction fetch is stalled, for any reason, including IF
U cache misses, ITLB misses, ITLB faults, and other minor stalls.",
    { CNTR2|CNTR1, 0x86}},
  { "ILD_STALL",
    "Number of cycles the instruction length decoder is stalled.",
    { CNTR2|CNTR1, 0x87}},
  { "L2_IFETCH_MOD",
    "Number of fetches from a modified line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x828}},
  { "L2_IFETCH_EXC",
    "Number of fetches from a exclusive line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x428}},
  { "L2_IFETCH_SHD",
    "Number of fetches from a shared line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x228}},
  { "L2_IFETCH_INV",
    "Number of fetches from a invalid line of L2 instruction cache.",
    { CNTR2|CNTR1, 0x128}},
  { "L2_IFETCH_TOT",
    "Total number of L2 instruction fetches.",
    { CNTR2|CNTR1, 0xf28}},
  { "L2_LD_MOD",
    "Number of loads from a modified line of the L2 data cache.",
    { CNTR2|CNTR1, 0x829}},
  { "L2_LD_EXC",
    "Number of loads from an exclusive line of the L2 data cache.",
    { CNTR2|CNTR1, 0x429}},
  { "L2_LD_SHD",
    "Number of loads from a shared line of the L2 data cache.",
    { CNTR2|CNTR1, 0x229}},
  { "L2_LD_INV",
    "Number of loads from an invalid line of the L2 data cache.",
    { CNTR2|CNTR1, 0x129}},
  { "L2_LD_TOT",
    "Total number of L2 data loads.",
    { CNTR2|CNTR1, 0xf29}},
  { "L2_ST_MOD",
    "Number of stores to a modified line of the L2 data cache.",
    { CNTR2|CNTR1, 0x82a}},
  { "L2_ST_EXC",
    "Number of stores to a exclusive line of the L2 data cache.",
    { CNTR2|CNTR1, 0x42a}},
  { "L2_ST_SHD",
    "Number of stores to a shared line of the L2 data cache.",
    { CNTR2|CNTR1, 0x22a}},
  { "L2_ST_INV",
    "Number of stores to a invalid line of the L2 data cache.",
    { CNTR2|CNTR1, 0x12a}},
  { "L2_ST_TOT",
    "Total number of L2 data stores.",
    { CNTR2|CNTR1, 0xf2a}},
  { "L2_LINES_IN",
    "Number of lines allocated in the L2.",
    { CNTR2|CNTR1, 0x24}},
  { "L2_LINES_OUT",
    "Number of lines removed fromo the L2 for any reason.",
    { CNTR2|CNTR1, 0x26}},
  { "L2_M_LINES_INM",
    "Number of modified lines allocated in the L2.",
    { CNTR2|CNTR1, 0x25}},
  { "L2_M_LINES_OUTM",
    "Number of modified lines removed from the L2 for any reason.",
    { CNTR2|CNTR1, 0x27}},
  { "L2_RQSTS_MOD",
    "Total number of L2 requests to a modified line.",
    { CNTR2|CNTR1, 0x82e}},
  { "L2_RQSTS_EXC",
    "Total number of L2 requests to an exclusive line.",
    { CNTR2|CNTR1, 0x42e}},
  { "L2_RQSTS_SHD",
    "Total number of L2 requests to a shared line.",
    { CNTR2|CNTR1, 0x22e}},
  { "L2_RQSTS_INV",
    "Total number of L2 requests to an invalid line.",
    { CNTR2|CNTR1, 0x12e}},
  { "L2_RQSTS_TOT",
    "Total number of L2 requests.",
    { CNTR2|CNTR1, 0xf2e}},
  { "L2_ADS",
    "Number of L2 address strobes.",
    { CNTR2|CNTR1, 0x21}},
  { "L2_DBS_BUSY",
    "Number of cycles the L2 cache data bus was busy.",
    { CNTR2|CNTR1, 0x22}},
  { "L2_DBS_BUSY_RD",
    "Number of cycles the data bus was busy transferring read data from the L2 t
o the processor.",
    { CNTR2|CNTR1, 0x23}},
  { "BUS_DRDY_CLOCKS_SELF",
    "Number of clock cycles during which the processor is driving DRDY#.",
    { CNTR2|CNTR1, 0x62}},
  { "BUS_DRDY_CLOCKS_ANY",
    "Number of clock cycles during which any agent is driving DRDY#.",
    { CNTR2|CNTR1, 0x2062}},
  { "BUS_LOCK_CLOCKS_SELF",
    "Number of clock cycles during which the processor is driving LOCK#.",
    { CNTR2|CNTR1, 0x63}},
  { "BUS_LOCK_CLOCKS_ANY",
    "Number of clock cycles during which any agent is driving LOCK#.",
    { CNTR2|CNTR1, 0x2063}},
  { "BUS_REQ_OUTSTANDING",
    "Number of bus outstanding bus requests.",
    { CNTR2|CNTR1, 0x60}},
  { "BUS_TRAN_BRD_SELF",
    "Number of burst read transactions by the processor.",
    { CNTR2|CNTR1, 0x65}},
  { "BUS_TRAN_BRD_ANY",
    "Number of burst read transactions by any agent.",
    { CNTR2|CNTR1, 0x2065}},
  { "BUS_TRAN_RFO_SELF",
    "Number of completed read for ownership transactions by the processor.",
    { CNTR2|CNTR1, 0x66}},
  { "BUS_TRAN_RFO_ANY",
    "Number of completed read for ownership transactions by any agent.",
    { CNTR2|CNTR1, 0x2066}},
  { "BUS_TRANS_WB_SELF",
    "Number of completed write back transactions by the processor.",
    { CNTR2|CNTR1, 0x67}},
  { "BUS_TRANS_WB_ANY",
    "Number of completed write back transactions by any agent.",
    { CNTR2|CNTR1, 0x2067}},
  { "BUS_TRAN_IFETCH_SELF",
    "Number of completed instruction fetch transactions by the processor.",
    { CNTR2|CNTR1, 0x68}},
  { "BUS_TRAN_IFETCH_ANY",
    "Number of completed instruction fetch transactions by any agent.",
    { CNTR2|CNTR1, 0x2068}},
  { "BUS_TRAN_INVAL_SELF",
    "Number of completed invalidate transactions by the processor.",
    { CNTR2|CNTR1, 0x69}},
  { "BUS_TRAN_INVAL_ANY",
    "Number of completed invalidate transactions by any agent.",
    { CNTR2|CNTR1, 0x2069}},
  { "BUS_TRAN_PWR_SELF",
    "Number of completed partial write transactions by the processor.",
    { CNTR2|CNTR1, 0x6a}},
  { "BUS_TRAN_PWR_ANY",
    "Number of completed partial write transactions by any agent.",
    { CNTR2|CNTR1, 0x206a}},
  { "BUS_TRANS_P_SELF",
    "Number of completed partial transactions by the processor.",
    { CNTR2|CNTR1, 0x6b}},
  { "BUS_TRANS_P_ANY",
    "Number of completed partial transactions by any agent.",
    { CNTR2|CNTR1, 0x206b}},
  { "BUS_TRANS_IO_SELF",
    "Number of completed I/O transactions by the processor.",
    { CNTR2|CNTR1, 0x6c}},
  { "BUS_TRANS_IO_ANY",
    "Number of completed I/O transactions by any agent.",
    { CNTR2|CNTR1, 0x206c}},
  { "BUS_TRAN_DEF_SELF",
    "Number of completed deferred transactions by the processor.",
    { CNTR2|CNTR1, 0x6d}},
  { "BUS_TRAN_DEF_ANY",
    "Number of completed deferred transactions by any agent.",
    { CNTR2|CNTR1, 0x206d}},
  { "BUS_TRAN_BURST_SELF",
    "Number of completed burst transactions by the processor.",
    { CNTR2|CNTR1, 0x6e}},
  { "BUS_TRAN_BURST_ANY",
    "Number of completed burst transactions by any agent.",
    { CNTR2|CNTR1, 0x206e}},
  { "BUS_TRAN_ANY_SELF",
    "Number of completed bus transactions by the processor.",
    { CNTR2|CNTR1, 0x70}},
  { "BUS_TRAN_ANY_ANY",
    "Number of completed bus transactions by any agent.",
    { CNTR2|CNTR1, 0x2070}},
  { "BUS_TRAN_MEM_SELF",
    "Number of completed memory transactions by the processor.",
    { CNTR2|CNTR1, 0x6f}},
  { "BUS_TRAN_MEM_ANY",
    "Number of completed memory transactions by any agent.",
    { CNTR2|CNTR1, 0x206f}},
  { "BUS_DATA_RCV",
    "Number of bus clock cycles during which this processor is receiving data.",
    { CNTR2|CNTR1, 0x64}},
  { "BUS_BNR_DRV",
    "Number of bus clock cycles during which this processor is driving the BNR# pin.",
    { CNTR2|CNTR1, 0x61}},
  { "BUS_HIT_DRV",
    "Number of bus clock cycles during which this processor is driving the HIT# pin.",
    { CNTR2|CNTR1, 0x7a}},
  { "BUS_HITM_DRV",
    "Number of bus clock cycles during which this processor is driving the HITM# pin.",
    { CNTR2|CNTR1, 0x7b}},
  { "BUS_SNOOP_STALL",
    "Number of clock cycles during which the bus is snoop stalled.",
    { CNTR2|CNTR1, 0x7e}},
  { "FLOPS",
    "Number of computational floating-point operations retired.",
    { CNTR1, 0xc1}},
  { "FP_COMP_OPS_EXE",
    "Number of computational floating-point operations executed.",
    { CNTR1, 0x10}},
  { "FP_ASSIST",
    "Number of floating-point exception cases handled by microcode.",
    { CNTR2, 0x11}},
  { "MUL",
    "Number of integer and floating point multiplies.",
    { CNTR2, 0x12}},
  { "DIV",
    "Number of integer and floating point divides.",
    { CNTR2, 0x13}},
  { "CYCLES_DIV_BUSY",
    "Number of cycles during which the divider is busy and cannot accept new divides.",
    { CNTR1, 0x14}},
  { "LD_BLOCKS",
    "Number of load operations delayed due to store buffer blocks.",
    { CNTR2|CNTR1, 0x3}},
  { "SB_DRAINS",
    "Number of store buffer drain cycles.",
    { CNTR2|CNTR1, 0x4}},
  { "MISALIGN_MEM_REF",
    "Number of misaligned data memory references.",
    { CNTR2|CNTR1, 0x5}},
  { "INST_RETIRED",
    "Number of instructions retired.",
    { CNTR2|CNTR1, 0xc0}},
  { "UOPS_RETIRED",
    "Number of uops retired.",
    { CNTR2|CNTR1, 0xc2}},
  { "INST_DECODED",
    "Number of instructions decoded.",
    { CNTR2|CNTR1, 0xd0}},
  { "HW_INT_RX",
    "Number of hardware interrupts received.",
    { CNTR2|CNTR1, 0xc8}},
  { "CYCLES_INT_MASKED",
    "Number of processor cycles to which interrupts are enabled.",
    { CNTR2|CNTR1, 0xc6}},
  { "CYCLES_INT_PENDING_AND_MASKED",
    "Number of processor cycles for which interrupts are disabled and interrupts are pending.",
    { CNTR2|CNTR1, 0xc7}},
  { "BR_INST_RETIRED",
    "Number of branch instructions retired.",
    { CNTR2|CNTR1, 0xc4}},
  { "BR_MISS_PRED_RETIRED",
    "Number of mispredicted branches retired.",
    { CNTR2|CNTR1, 0xc5}},
  { "BR_TAKEN_RETIRED",
    "Number of taken branches retired.",
    { CNTR2|CNTR1, 0xc9}},
  { "BR_MISS_PRED_TAKEN_RET",
    "Number of mispredictions branches retired.",
    { CNTR2|CNTR1, 0xca}},
  { "BR_INST_DECODED",
    "Number of branch instructions decoded.",
    { CNTR2|CNTR1, 0xe0}},
  { "BTB_MISSES",
    "Number of branches for which the BTB did not produce a prediction.",
    { CNTR2|CNTR1, 0xe2}},
  { "BR_BOGUS",
    "Number of bogus branches.",
    { CNTR2|CNTR1, 0xe4}},
  { "BACLEARS",
    "Number of times BACLEAR is asserted. This is the number of times that a static branch prediction was made, in which the branch decoder decided to make a branch prediction because the BTB did not.",
    { CNTR2|CNTR1, 0xe6}},
  { "RESOURCE_STALLS",
    "Incremented by 1 during every cycle for which there is a resource related stall.",
    { CNTR2|CNTR1, 0xa2}},
  { "PARTIAL_RAT_STALLS",
    "Number of cycles or events for partial stalls.  Includes flag partial stalls.",
    { CNTR2|CNTR1, 0xd2}},
  { "SEGMENT_REG_LOADS",
    "Number of segment register loads.",
    { CNTR2|CNTR1, 0x06}},
  { "CPU_CLK_UNHALTED",
    "Number of cycles during which the processor is not halted.",
    { CNTR2|CNTR1, 0x79}},
  { "MMX_INSTR_EXEC",
    "Number of MMX instructions executed.",
    { CNTR2|CNTR1, 0xb0}},
  { "MMX_SAT_INSTR_EXEC",
    "Number of MMX Saturating instructions executed.",
    { CNTR2|CNTR1, 0xb1}},
  { "MMX_UOPS_EXEC",
    "Number of MMX uops executed.",
    { CNTR2|CNTR1, 0xfb2}},
  { "MMX_INSTR_TYPE_EXEC_MUL",
    "Number of MMX packed multiply instructions executed.",
    { CNTR2|CNTR1, 0x1b3}},
  { "MMX_INSTR_TYPE_EXEC_SHIFT",
    "Number of MMX packed shift instructions executed.",
    { CNTR2|CNTR1, 0x2b3}},
  { "MMX_INSTR_TYPE_EXEC_PACK_OPS",
    "Number of MMX pack operation instructions executed.",
    { CNTR2|CNTR1, 0x4b3}},
  { "MMX_INSTR_TYPE_EXEC_UNPACK_OPS",
    "Number of MMX unpack operation instructions executed.",
    { CNTR2|CNTR1, 0x8b3}},
  { "MMX_INSTR_TYPE_EXEC_LOGICAL",
    "Number of MMX packed logical instructions executed.",
    { CNTR2|CNTR1, 0x10b3}},
  { "MMX_INSTR_TYPE_EXEC_ARITHMETIC",
    "Number of MMX packed arithmetic instructions executed.",
    { CNTR2|CNTR1, 0x20b3}},
  { "FP_MMX_TRANS_MMX_TO_FP",
    "Transitions from MMX instruction to floating-point instructions.",
    { CNTR2|CNTR1, 0xcc}},
  { "FP_MMX_TRANS_FP_TO_MMX",
    "Transitions from floating-point instructions to MMX instructions.",
    { CNTR2|CNTR1, 0x1cc}},
  { "MMX_ASSIST",
    "Number of MMX Assists, ie the number of EMMS instructions executed.",
    { CNTR2|CNTR1, 0xcd}},
  { "MMX_INSTR_RET",
    "Number of MMX instructions retired.",
    { CNTR2|CNTR1, 0xce}},
  { "SEG_RENAME_STALLS_ES",
    "Number of Segment Register ES Renaming stalls.",
    { CNTR2|CNTR1, 0x1d4}},
  { "SEG_RENAME_STALLS_DS",
    "Number of Segment Register DS Renaming stalls.",
    { CNTR2|CNTR1, 0x2d4}},
  { "SEG_RENAME_STALLS_FS",
    "Number of Segment Register FS Renaming stalls.",
    { CNTR2|CNTR1, 0x4d4}},
  { "SEG_RENAME_STALLS_GS",
    "Number of Segment Register GS Renaming stalls.",
    { CNTR2|CNTR1, 0x8d4}},
  { "SEG_RENAME_STALLS_TOT",
    "Total Number of Segment Register Renaming stalls.",
    { CNTR2|CNTR1, 0xfd4}},
  { "SEG_REG_RENAMES_ES",
    "Number of Segment Register ES Renames.",
    { CNTR2|CNTR1, 0x1d5}},
  { "SEG_REG_RENAMES_DS",
    "Number of Segment Register DS Renames.",
    { CNTR2|CNTR1, 0x2d5}},
  { "SEG_REG_RENAMES_FS",
    "Number of Segment Register FS Renames.",
    { CNTR2|CNTR1, 0x4d5}},
  { "SEG_REG_RENAMES_GS",
    "Number of Segment Register GS Renames.",
    { CNTR2|CNTR1, 0x8d5}},
  { "SEG_REG_RENAMES_TOT",
    "Total number of Segment Register Renames.",
    { CNTR2|CNTR1, 0xfd5}},
  { "RET_SEG_RENAMES",
    "Number of segment register rename events retired.",
    { CNTR2|CNTR1, 0xd6}}
};

const native_event_entry_t _papi_hwd_ath_native_map[] = {
  { "SEG_REG_LOADS",
    "Number of segment register loads.",
    { ALLCNTRS, 0x20}},
  { "ST_ACTIVE_IS",
    "Number of stores to active instruction stream (self-modifying code occurences).",
    { ALLCNTRS, 0x21}},
  { "DC_ACCESSES",
    "Number of data cache accesses.",
    { ALLCNTRS, 0x40}},
  { "DC_MISSES",
    "Number of data cache misses.",
    { ALLCNTRS, 0x41}},
  { "L2_DC_REFILLS_MOD",
    "Number of modified data cache lines refilled from L2.",
    { ALLCNTRS, 0x1042}},
  { "L2_DC_REFILLS_OWN",
    "Number of owner data cache lines refilled from L2.",
    { ALLCNTRS, 0x842}},
  { "L2_DC_REFILLS_EXC",
    "Number of exclusive data cache lines refilled from L2.",
    { ALLCNTRS, 0x442}},
  { "L2_DC_REFILLS_SHR",
    "Number of shared data cache lines refilled from L2.",
    { ALLCNTRS, 0x242}},
  { "L2_DC_REFILLS_INV",
    "Number of invalid data cache lines refilled from L2.",
    { ALLCNTRS, 0x142}},
  { "L2_DC_REFILLS_TOT",
    "Total number of data cache lines refilled from L2.",
    { ALLCNTRS, 0x1f41}},
  { "SYS_DC_REFILLS_MOD",
    "Number of modified data cache lines refilled from system.",
    { ALLCNTRS, 0x1043}},
  { "SYS_DC_REFILLS_OWN",
    "Number of owner data cache lines refilled from system.",
    { ALLCNTRS, 0x843}},
  { "SYS_DC_REFILLS_EXC",
    "Number of exclusive data cache lines refilled from system.",
    { ALLCNTRS, 0x443}},
  { "SYS_DC_REFILLS_SHR",
    "Number of shared data cache lines refilled from system.",
    { ALLCNTRS, 0x243}},
  { "SYS_DC_REFILLS_INV",
    "Number of invalid data cache lines refilled from system.",
    { ALLCNTRS, 0x143}},
  { "SYS_DC_REFILLS_TOT",
    "Total number of data cache lines refilled from system.",
    { ALLCNTRS, 0x1f43}},
  { "DC_WB_MOD",
    "Number of writebacks involving modified data cache lines.",
    { ALLCNTRS, 0x1044}},
  { "DC_WB_OWN",
    "Number of writebacks involving owner data cache lines.",
    { ALLCNTRS, 0x844}},
  { "DC_WB_EXC",
    "Number of writebacks involving exclusive data cache lines.",
    { ALLCNTRS, 0x444}},
  { "DC_WB_SHR",
    "Number of writebacks involving shared data cache lines.",
    { ALLCNTRS, 0x244}},
  { "DC_WB_INV",
    "Number of writebacks involving invalid data cache lines.",
    { ALLCNTRS, 0x144}},
  { "DC_WB_TOT",
    "Total number of data cache writebacks.",
    { ALLCNTRS, 0x1f44}},
  { "L1_DTLB_MISSES ANDL2_DTLB_HITS",
    "L1 DTLB misses and L2 DLTB hits.",
    { ALLCNTRS, 0x45}},
  { "L1_AND_L2_DTLB_MISSES",
    "L1 and L2 DTLB misses.",
    { ALLCNTRS, 0x46}},
  { "MISALIGNED_DATA_REFERENCES",
    "Misaligned data references.",
    { ALLCNTRS, 0x47}},
  { "DRAM_SYS_REQS",
    "Number of DRAM system requests.",
    { ALLCNTRS, 0x64}},
  { "SYS_REQS_SEL_TYPE",
    "Number of system request with the selected type.",   /* ??? */
    { ALLCNTRS, 0x65}},
  { "SNOOP_HITS",
    "Number of snoop hits.",
    { ALLCNTRS, 0x73}},
  { "ECC_ERR",
    "Number of single bit ecc errors detected or corrected.",
    { ALLCNTRS, 0x74}},
  { "INTERNAL_CACHE_INV",
    "Number of internal cache line invalidates.",
    { ALLCNTRS, 0x75}},
  { "TOT_CYC",
    "Number of cycles processor is running.",
    { ALLCNTRS, 0x76}},
  { "L2_REQ",
    "Number of L2 requests.",
    { ALLCNTRS, 0x79}},
  { "FILL_REQ_STALLS",
    "Number of cycles that at least one fill request waited to use the L2.",
    { ALLCNTRS, 0x7a}},
  { "IC_FETCHES",
    "Number of instruction cache fetches.",
    { ALLCNTRS, 0x80}},
  { "IC_MISSES",
    "Number of instruction cache misses.",
    { ALLCNTRS, 0x81}},
  { "L2_IC_REFILLS",
    "Number of instruction cache refills from L2.",
    { ALLCNTRS, 0x82}},
  { "SYS_IC_REFILLS",
    "Number of instruction cache refills from system.",
    { ALLCNTRS, 0x83}},
  { "L1_ITLB_MISSES",
    "Number of L1 ITLB misses (and L2 ITLB hits.)",
    { ALLCNTRS, 0x84}},
  { "L2_ITLB_MISSES",
    "Number of (L1 and) L2 ITLB misses.",
    { ALLCNTRS, 0x85}},
  { "SNOOP_RESYNCS",
    "Number of snoop resyncs.",
    { ALLCNTRS, 0x86}},
  { "IFETCH_STALLS",
    "Number of instruction fetch stall cycles.",
    { ALLCNTRS, 0x87}},
  { "RET_STACK_HITS",
    "Number of return stack hits.",
    { ALLCNTRS, 0x88}},
  { "RET_STACK_OVERFLOW",
    "Return stack overflow.",
    { ALLCNTRS, 0x89}},
  { "RET_INSTRUCTIONS",
    "Retired instructions (includes exceptions, interrupts, resyncs.)",
    { ALLCNTRS, 0xc0}},
  { "RET_OPS",
    "Retired ops.",
    { ALLCNTRS, 0xc1}},
  { "RET_BR",
    "Retired branches (conditional, unconditional, exceptions, interrupts.)",
    { ALLCNTRS, 0xc2}},
  { "RET_BR_MIS",
    "Retired branches mispredicted.",
    { ALLCNTRS, 0xc3}},
  { "RET_TAKEN_BR",
    "Retired taken branches.",
    { ALLCNTRS, 0xc4}},
  { "RET_TAKEN_BR_MIS",
    "Retired taken branches mispredicted.",
    { ALLCNTRS, 0xc5}},
  { "RET_FAR_CONTROL_TRANSFERS",
    "Retired far control transfers.",
    { ALLCNTRS, 0xc6}},
  { "RET_RESYNC_BR",
    "Retired resync branches - only non-control transfer branches counted.",
    { ALLCNTRS, 0xc7}},
  { "RET_NEAR_RETURNS",
    "Retired near returns.",
    { ALLCNTRS, 0xc8}},
  { "RET_NEAR_RETURNS_MIS",
    "Retired near returns mispredicted.",
    { ALLCNTRS, 0xc9}},
  { "RET_INDIRECT_BR_MIS",
    "Retired indirect branches with target mispredicted.",
    { ALLCNTRS, 0xca}},
  { "INTS_MASKED_CYC",
    "Interrupts masked cycles (IF=0).",
    { ALLCNTRS, 0xcd}},
  { "INTS_MASKED_WHILE_PENDING_CYC",
    "Interrupts masked while pending cycles (INTR while IF=0).",
    { ALLCNTRS, 0xce}},
  { "TAKEN_HARDWARE_INTS",
    "Number of taken hardware interrupts.",
    { ALLCNTRS, 0xcf}},
  { "INS_DECODER_EMPTY",
    "Number of cycles in whih the instruction decoder is empty.",
    { ALLCNTRS, 0xd0}},
  { "DISPATCH_STALLS",
    "Number of dispatch stalls.",
    { ALLCNTRS, 0xd1}},
  { "BRANCH_ABORTS",
    "Number of branch aborts to retire.",
    { ALLCNTRS, 0xd2}},
  { "SERIALIZE",
    "Serialize.",
    { ALLCNTRS, 0xd3}},
  { "SEG_LOAD_STALLS",
    "Number of segment load stalls.",
    { ALLCNTRS, 0xd4}},
  { "ICU_FULL",
    "Number of cycles in which the ICU is full.",
    { ALLCNTRS, 0xd5}},
  { "RES_STATIONS_FULL",
    "Number of cycles in which the reservation station is full.",
    { ALLCNTRS, 0xd6}},
  { "FPU_FULL",
    "Number of cycles in which the FPU is full.",
    { ALLCNTRS, 0xd7}},
  { "LS_FULL",
    "Number of cycles in which the LS is full.",
    { ALLCNTRS, 0xd8}},
  { "ALL_QUIET_STALL",
    "Number of all quiet stalls.",
    { ALLCNTRS, 0xd9}},
  { "TRANS_OR_BRANCH_PENDING",
    "Far transfer or resync branch pending.",
    { ALLCNTRS, 0xda}},
  { "BP_DR0",
    "Number of breakpoint matches for DR0.",
    { ALLCNTRS, 0xdc}},
  { "BP_DR1",
    "Number of breakpoint matches for DR1.",
    { ALLCNTRS, 0xdd}},
  { "BP_DR2",
    "Number of breakpoint matches for DR2.",
    { ALLCNTRS, 0xde}},
  { "BP_DR3",
    "Number of breakpoint matches for DR3.",
    { ALLCNTRS, 0xdf}}
};

/* The first two letters in each entry indicate to which unit
   the event refers. */

const native_event_entry_t _papi_hwd_opt_native_map[] = {
  { "FP_ADD_PIPE",
    "Dispatched FPU ops - Revision B and later revisions - Add pipe ops excluding junk ops.",
    { ALLCNTRS, 0x00}},
  { "FP_MULT_PIPE",
    "Dispatched FPU ops - Revision B and later revisions - Multiply pipe ops excluding junk ops.",
    { ALLCNTRS, 0x0100}},
  { "FP_ST_PIPE",
    "Dispatched FPU ops - Revision B and later revisions - Store pipe ops excluding junk ops.",
    { ALLCNTRS, 0x0200}},
  { "FP_ADD_PIPE_JUNK",
    "Dispatched FPU ops - Revision B and later revisions - Add pipe junk ops.",
    { ALLCNTRS, 0x0300}},
  { "FP_MULT_PIPE_JUNK",
    "Dispatched FPU ops - Revision B and later revisions - Multiply pipe junk ops.",
    { ALLCNTRS, 0x0400}},
  { "FP_ST_PIPE_JUNK",
    "Dispatched FPU ops - Revision B and later revisions - Store pipe junk ops.",
    { ALLCNTRS, 0x0500}},
  { "FP_NONE_RET",
    "Cycles with no FPU ops retired - Revision B and later revisions.",
    { ALLCNTRS, 0x01}},
  { "FP_FAST_FLAG",
    "Dispatched FPU ops that use the fast flag interface - Revision B and later revisions.",
    { ALLCNTRS, 0x02}},
  { "LS_SEG_REG_LOADS_ES",
    "Number of segment register loads - ES.",
    { ALLCNTRS, 0x0020}},
  { "LS_SEG_REG_LOADS_CS",
    "Number of segment register loads - CS.",
    { ALLCNTRS, 0x120}},
  { "LS_SEG_REG_LOADS_SS",
    "Number of segment register loads - SS.",
    { ALLCNTRS, 0x220}},
  { "LS_SEG_REG_LOADS_DS",
    "Number of segment register loads - DS.",
    { ALLCNTRS, 0x320}},
  { "LS_SEG_REG_LOADS_FS",
    "Number of segment register loads - FS.",
    { ALLCNTRS, 0x420}},
  { "LS_SEG_REG_LOADS_GS",
    "Number of segment register loads - GS.",
    { ALLCNTRS, 0x520}},
  { "LS_SEG_REG_LOADS_HS",
    "Number of segment register loads - HS.",
    { ALLCNTRS, 0x620}},
  { "LS_SELF_MODIFYING_RESYNC",
    "Microarchitectural resync caused by self-modifying code.",
    { ALLCNTRS, 0x21}},
  { "LS_SNOOP_RESYNC",
    "Microarchitectural resync caused by snoop.",
    { ALLCNTRS, 0x22}},
  { "LS_BUF_2_FULL",
    "LS buffer 2 full.",
    { ALLCNTRS, 0x23}},
  { "LS_LOCK_INS",
    "Locked operation - Revision B and earlier versions - Number of lock instructions executed - Revision C and later revisions.",
    { ALLCNTRS, 0x24}},
  { "LS_LOCK_REQ",
    "Locked operation - Revision B and earlier versions - Number of cycles spent in the lock request or grant stage - Revision C and later revisions.",
    { ALLCNTRS, 0x124}},
  { "LS_LOCK_COMP",
    "Locked operation - Revision B and earlier versions - Number of cycles a lock takes to complete once it is non-speculative and is the oldest load or store operation - non-speculative cycles in Ls2 entry 0- Revision C and later revisions.",
    { ALLCNTRS, 0x224}},
  { "LS_LATE_CANCEL",
    "Microarchitectural late cancel of an operation.",
    { ALLCNTRS, 0x25}},
  { "LS_CFLUSH",
    "Retired CFLUSH instructions.",
    { ALLCNTRS, 0x26}},
  { "LS_CPUID",
    "Retired CPUID instructions.",
    { ALLCNTRS, 0x27}},
  { "DC_ACCESS",
    "Access - includes microcode scratchpad accesses.",
    { ALLCNTRS, 0x40}},
  { "DC_MISS",
    "Miss.",
    { ALLCNTRS, 0x41}},
  { "DC_L2_REFILL_INV",
    "Refill from L2 - Invalid.",
    { ALLCNTRS, 0x42}},
  { "DC_L2_REFILL_SHR",
    "Refill from L2 - Shared.",
    { ALLCNTRS, 0x142}},
  { "DC_L2_REFILL_EXC",
    "Refill from L2 - Exclusive.",
    { ALLCNTRS, 0x242}},
  { "DC_L2_REFILL_OWN",
    "Refill from L2 - Owner.",
    { ALLCNTRS, 0x342}},
  { "DC_L2_REFILL_MOD",
    "Refill from L2 - Modified.",
    { ALLCNTRS, 0x442}},
  { "DC_L2_REFILL_TOT",
    "Refill from L2 - Total.",
    { ALLCNTRS, 0xa42}},
  { "DC_SYS_REFILL_INV",
    "Refill from system - Invalid.",
    { ALLCNTRS, 0x43}},
  { "DC_SYS_REFILL_SHR",
    "Refill from system - Shared.",
    { ALLCNTRS, 0x143}},
  { "DC_SYS_REFILL_EXC",
    "Refill from system - Exclusive.",
    { ALLCNTRS, 0x243}},
  { "DC_SYS_REFILL_OWN",
    "Refill from system - Owner.",
    { ALLCNTRS, 0x343}},
  { "DC_SYS_REFILL_MOD",
    "Refill from system - Modified.",
    { ALLCNTRS, 0x443}},
  { "DC_SYS_REFILL_TOT",
    "Refill from system - Total.",
    { ALLCNTRS, 0xa43}},
  { "DC_COPYBACK_INV",
    "Copyback - Invalid.",
    { ALLCNTRS, 0x44}},
  { "DC_COPYBACK_SHR",
    "Copyback - Shared.",
    { ALLCNTRS, 0x144}},
  { "DC_COPYBACK_EXC",
    "Copyback - Exclusive.",
    { ALLCNTRS, 0x244}},
  { "DC_COPYBACK_OWN",
    "Copyback - Owner.",
    { ALLCNTRS, 0x344}},
  { "DC_COPYBACK_MOD",
    "Copyback - Modified.",
    { ALLCNTRS, 0x444}},
  { "DC_COPYBACK_TOT",
    "Copyback - Total.",
    { ALLCNTRS, 0xa44}},
  { "DC_L1_DTLB_MISS_AND_L2_DTLB_HIT",
    "L1 DTLB miss and L2 DTLB hit.",
    { ALLCNTRS, 0x45}},
  { "DC_L1_DTLB_MISS_AND_L2_DTLB_MISS",
    "L1 DTLB miss and L2 DTLB miss.",
    { ALLCNTRS, 0x46}},
  { "DC_MISALIGNED_DATA_REF",
    "Misaligned data reference.",
    { ALLCNTRS, 0x47}},
  { "DC_LATE_CANCEL",
    "Microarchitectural late cancel of an access.",
    { ALLCNTRS, 0x48}},
  { "DC_EARLY_CANCEL",
    "Microarchitectural early cancel of an access.",
    { ALLCNTRS, 0x49}},
  { "DC_ECC_SCRUBBER_ERR",
    "One bit ECC error recorded found by scrubber - Scrubber error.",
    { ALLCNTRS, 0x4a}},
  { "DC_ECC_PIGGY_SCRUBBER_ERR",
    "One bit ECC error recorded found by scrubber - Piggyback scrubber errors.",
    { ALLCNTRS, 0x14a}},
  { "DC_DISPATCHED_PREFETCH_LOAD",
    "Dispatched prefetch instructions - Load.",
    { ALLCNTRS, 0x4b}},
  { "DC_DISPATCHED_PREFETCH_STORE",
    "Dispatched prefetch instructions - Store.",
    { ALLCNTRS, 0x14b}},
  { "DC_DISPATCHED_PREFETCH_NTA",
    "Dispatched prefetch instructions - NTA.",
    { ALLCNTRS, 0x24b}},
  { "DC_ACCESSES_BY_LOCK",
    "DCACHE accesses by locks - Revision C and later revisions - Number of dcache accesses by lock instructions.",
    { ALLCNTRS, 0x4c}},
  { "DC_MISSES_BY_LOCK",
    "DCACHE accesses by locks - Revision C and later revisions - Number of dcache misses by lock instructions.",
    { ALLCNTRS, 0x14c}},
  { "BU_L2_REQ_IC",
    "Internal L2 request - IC fill.",
    { ALLCNTRS, 0x7d}},
  { "BU_L2_REQ_DC",
    "Internal L2 request - DC fill.",
    { ALLCNTRS, 0x17d}},
  { "BU_L2_REQ_TLB_RELOAD",
    "Internal L2 request - TLB reload.",
    { ALLCNTRS, 0x27d}},
  { "BU_L2_REQ_TAG_SNOOP_REQ",
    "Internal L2 request - Tag snoop request.",
    { ALLCNTRS, 0x37d}},
  { "BU_L2_REQ_CANC_REQ",
    "Internal L2 request - Cancelled request.",
    { ALLCNTRS, 0x47d}},
  { "BU_L2_FILL_MISS_IC",
    "Fill request that missed in L2 - IC fill.",
    { ALLCNTRS, 0x7e}},
  { "BU_L2_FILL_MISS_DC",
    "Fill request that missed in L2 - DC fill.",
    { ALLCNTRS, 0x17e}},
  { "BU_L2_FILL_MISS_TLB_RELOAD",
    "Fill request that missed in L2 - TLB reload.",
    { ALLCNTRS, 0x27e}},
  { "BU_L2_FILL_DIRTY",
    "Fill into L2 - Dirty L2 victim.",
    { ALLCNTRS, 0x7f}},
  { "BU_L2_FILL_FROM_L1",
    "Fill into L2 - Victim from L1.",
    { ALLCNTRS, 0x17f}},
  { "IC_FETCH",
    "Fetch.",
    { ALLCNTRS, 0x80}},
  { "IC_MISS",
    "Miss.",
    { ALLCNTRS, 0x81}},
  { "IC_L2_REFILL",
    "Refill from L2.",
    { ALLCNTRS, 0x82}},
  { "IC_SYS_REFILL",
    "Refill from system.",
    { ALLCNTRS, 0x83}},
  { "IC_L1ITLB_MISS_AND_L2ITLB_HIT",
    "L1ITLB miss and L2ITLB hit.",
    { ALLCNTRS, 0x84}},
  { "IC_L1ITLB_MISS_AND_L2ITLB_MISS",
    "L1ITLB miss and L2ITLB miss.",
    { ALLCNTRS, 0x85}},
  { "IC_RESYNC",
    "Microarchitectural resync caused by snoop.",
    { ALLCNTRS, 0x86}},
  { "IC_FETCH_STALL",
    "Instruction fetch stall.",
    { ALLCNTRS, 0x87}},
  { "IC_STACK_HIT",
    "Return stack hit.",
    { ALLCNTRS, 0x88}},
  { "IC_STACK_OVERFLOW",
    "Return stack overflow.",
    { ALLCNTRS, 0x89}},
  { "FR_X86_INS",
    "Retired x86 instructions including exceptions and interrupts.",
    { ALLCNTRS, 0xC0}},
  { "FR_RET_UOPS",
    "Retired uops.",
    { ALLCNTRS, 0xC1}},
  { "FR_BR",
    "Retired branches including exceptions and interrupts.",
    { ALLCNTRS, 0xC2}},
  { "FR_BR_MIS",
    "Retired branches mispredicted.",
    { ALLCNTRS, 0xC3}},
  { "FR_BR_TAKEN",
    "Retired taken branches.",
    { ALLCNTRS, 0xC4}},
  { "FR_BR_TAKEN_MIS",
    "Retired taken branches mispredicted.",
    { ALLCNTRS, 0xC5}},
  { "FR_FAR_CONTROL_TRANSFERS",
    "Retired far control transfers - always mispredicted.",
    { ALLCNTRS, 0xC6}},
  { "FR_RESYNCS",
    "Retired resyncs - non control transfer branches.",
    { ALLCNTRS, 0xC7}},
  { "FR_NEAR_RETURNS",
    "Retired near returns.",
    { ALLCNTRS, 0xC8}},
  { "FR_NEAR_RETURNS_MIS",
    "Retired near returns mispredicted.",
    { ALLCNTRS, 0xC9}},
  { "FR_BR_MISCOMPARE",
    "Retired taken branches mispredicted only due to address miscompare.",
    { ALLCNTRS, 0xCa}},
  { "FR_FPU_X87",
    "Retired FPU instructions - Revision B and later revisions - x87 instructions.",
    { ALLCNTRS, 0xCb}},
  { "FR_FPU_MMX_3D",
    "Retired FPU instructions - Revision B and later revisions - Combined MMX and 3DNow! instructions.",
    { ALLCNTRS, 0x1Cb}},
  { "FR_FPU_SSE_SSE2_PACKED",
    "Retired FPU instructions - Revision B and later revisions - Combined packed SSE and SSE2 instructions.",
    { ALLCNTRS, 0x2Cb}},
  { "FR_FPU_SSE_SSE2_SCALAR",
    "Retired FPU instructions - Revision B and later revisions - Combined scalar SSE and SSE2 instructions.",
    { ALLCNTRS, 0x3Cb}},
  { "FR_FASTPATH_POS0",
    "Retired fastpath double op instructions - Revision B and later revisions - With low op in position 0.",
    { ALLCNTRS, 0xCc}},
  { "FR_FASTPATH_POS1",
    "Retired fastpath double op instructions - Revision B and later revisions - With low op in position 1.",
    { ALLCNTRS, 0x1Cc}},
  { "FR_FASTPATH_POS2",
    "Retired fastpath double op instructions - Revision B and later revisions - With low op in position 2.",
    { ALLCNTRS, 0x2Cc}},
  { "FR_INTS_MASKED",
    "Interrupts masked cycles - IF=0.",
    { ALLCNTRS, 0xCd}},
  { "FR_INTS_MASKED_PENDING",
    "Interrupts masked while pending cycles - INTR while IF=0.",
    { ALLCNTRS, 0xCe}},
  { "FR_HW_INTS",
    "Taken hardware interrupts.",
    { ALLCNTRS, 0xCf}},
  { "FR_DECODER_EMPTY",
    "Nothing to dispatch - decoder empty.",
    { ALLCNTRS, 0xD0}},
  { "FR_DISPATCH_STALLS",
    "Dispatch stalls - D2h or DAh combined.",
    { ALLCNTRS, 0xD1}},
  { "FR_DISPATCH_STALLS_BR",
    "Dispatch stall from branch abort to retire.",
    { ALLCNTRS, 0xD2}},
  { "FR_DISPATCH_STALLS_SER",
    "Dispatch stall for serialization.",
    { ALLCNTRS, 0xD3}},
  { "FR_DISPATCH_STALLS_SEG",
    "Dispatch stall for segment load.",
    { ALLCNTRS, 0xD4}},
  { "FR_DISPATCH_STALLS_FULL_REORDER",
    "Dispatch stall when reorder buffer is full.",
    { ALLCNTRS, 0xD5}},
  { "FR_DISPATCH_STALLS_FULL_RESERVATION",
    "Dispatch stall when reservation stations are full.",
    { ALLCNTRS, 0xD6}},
  { "FR_DISPATCH_STALLS_FULL_FPU",
    "Dispatch stall when FPU is full.",
    { ALLCNTRS, 0xD7}},
  { "FR_DISPATCH_STALLS_FULL_LS",
    "Dispatch stall when LS is full.",
    { ALLCNTRS, 0xD8}},
  { "FR_DISPATCH_STALLS_QUIET",
    "Dispatch stall when waiting for all to be quiet.",
    { ALLCNTRS, 0xD9}},
  { "FR_DISPATCH_STALLS_FAR",
    "Dispatch stall when far control transfer or resync branch is pending.",
    { ALLCNTRS, 0xDa}},
  { "FR_FPU_EXCEPTIONS_X87",
    "FPU exceptions - Revision B and later revisions - x87 reclass microfaults.",
    { ALLCNTRS, 0xDb}},
  { "FR_FPU_EXCEPTIONS_SSE_RETYPE",
    "FPU exceptions - Revision B and later revisions - SSE retype microfaults.",
    { ALLCNTRS, 0x1Db}},
  { "FR_FPU_EXCEPTIONS_SSE_RECLASS",
    "FPU exceptions - Revision B and later revisions - SSE reclass microfaults.",
    { ALLCNTRS, 0x2Db}},
  { "FR_FPU_EXCEPTIONS_SSE_MICROTRAPS",
    "FPU exceptions - Revision B and later revisions - SSE and x87 microtraps.",
    { ALLCNTRS, 0x3Db}},
  { "FR_BP_DR0",
    "Number of breakpoints for DR0.",
    { ALLCNTRS, 0xDc}},
  { "FR_BP_DR1",
    "Number of breakpoints for DR1.",
    { ALLCNTRS, 0xDd}},
  { "FR_BP_DR2",
    "Number of breakpoints for DR2.",
    { ALLCNTRS, 0xDe}},
  { "FR_BP_DR3",
    "Number of breakpoints for DR3.",
    { ALLCNTRS, 0xDf}},
  { "NB_MC_PAGE_HIT",
    "Memory controller page access event - Page hit.",
    { ALLCNTRS, 0xE0}},
  { "NB_MC_PAGE_MISS",
    "Memory controller page access event - Page miss.",
    { ALLCNTRS, 0x1E0}},
  { "NB_MC_PAGE_CONFLICT",
    "Memory controller page access event - Page conflict.",
    { ALLCNTRS, 0x2E0}},
  { "NB_MC_PAGE_TBL_OVERFLOW",
    "Memory controller page table overflow.",
    { ALLCNTRS, 0xE1}},
  { "NB_MC_DRAM",
    "Memory controller DRAM command slots missed - in MemClks.",
    { ALLCNTRS, 0xE2}},
  { "NB_MC_TURNAROUND_DIMM",
    "Memory controller turnaround - DIMM turnaround.",
    { ALLCNTRS, 0xE3}},
  { "NB_MC_TURNAROUND_RTW",
    "Memory controller turnaround - Read to write turnaround.",
    { ALLCNTRS, 0x1E3}},
  { "NB_MC_TURNAROUND_WTR",
    "Memory controller turnaround - Write to read turnaround.",
    { ALLCNTRS, 0x2E3}},
  { "NB_MC_BYPASS_HP",
    "Memory controller bypass counter saturation - high priority.",
    { ALLCNTRS, 0xE4}},
  { "NB_MC_BYPASS_LP",
    "Memory controller bypass counter saturation - low priority.",
    { ALLCNTRS, 0x1E4}},
  { "NB_MC_BYPASS_INTERFACE",
    "Memory controller bypass counter saturation - DRAM controller interface bypass.",
    { ALLCNTRS, 0x2E4}},
  { "NB_MC_BYPASS_QUEUE",
    "Memory controller bypass counter saturation - DRAM controller queue bypass.",
    { ALLCNTRS, 0x3E4}},
  { "NB_SIZED_NONPOSTWRSZBYTE",
    "Sized commands - NonPostWrSzByte.",
    { ALLCNTRS, 0xEb}},
  { "NB_SIZED_NONPOSTWRSZDWORD",
    "Sized commands - NonPostWrSzDword.",
    { ALLCNTRS, 0x1Eb}},
  { "NB_SIZED_POSTWRSZBYTE",
    "Sized commands - PostWrSzByte.",
    { ALLCNTRS, 0x2Eb}},
  { "NB_SIZED_POSTWRSZDWORD",
    "Sized commands - PostWrSzDword.",
    { ALLCNTRS, 0x3Eb}},
  { "NB_SIZED_RDSZBYTE",
    "Sized commands - RdSzByte.",
    { ALLCNTRS, 0x4Eb}},
  { "NB_SIZED_RDSZDWORD",
    "Sized commands - RdSzDword.",
    { ALLCNTRS, 0x5Eb}},
  { "NB_SIZED_RDMODWR",
    "Sized commands - RdModWr.",
    { ALLCNTRS, 0x6Eb}},
  { "NB_PROBE_MISS",
    "Probe result - Probe miss.",
    { ALLCNTRS, 0xEc}},
  { "NB_PROBE_HIT",
    "Probe result - Probe Hit.",
    { ALLCNTRS, 0x1Ec}},
  { "NB_PROBE_HIT_DIRTY_NO_MEM_CANCEL",
    "Probe result - Probe hit dirty without memory cancel.",
    { ALLCNTRS, 0x2Ec}},
  { "NB_PROBE_HIT_DIRTY_MEM_CANCEL",
    "Probe result - Probe hit dirty with memory cancel.",
    { ALLCNTRS, 0x3Ec}},
  { "NB_HT_BUS0_COMMAND",
    "HyperTransport bus 0 bandwidth - Command sent.",
    { ALLCNTRS, 0xF6}},
  { "NB_HT_BUS0_DATA",
    "HyperTransport bus 0 bandwidth - Data sent.",
    { ALLCNTRS, 0x1F6}},
  { "NB_HT_BUS0_BUFF",
    "HyperTransport bus 0 bandwidth - Buffer release sent.",
    { ALLCNTRS, 0x2F6}},
  { "NB_HT_BUS0_NOP",
    "HyperTransport bus 0 bandwidth - Nop sent.",
    { ALLCNTRS, 0x3F6}},
  { "NB_HT_BUS1_COMMAND",
    "HyperTransport bus 1 bandwidth - Command sent.",
    { ALLCNTRS, 0xF7}},
  { "NB_HT_BUS1_DATA",
    "HyperTransport bus 1 bandwidth - Data sent.",
    { ALLCNTRS, 0x1F7}},
  { "NB_HT_BUS1_BUFF",
    "HyperTransport bus 1 bandwidth - Buffer release sent.",
    { ALLCNTRS, 0x2F7}},
  { "NB_HT_BUS1_NOP",
    "HyperTransport bus 1 bandwidth - Nop sent.",
    { ALLCNTRS, 0x3F7}},
  { "NB_HT_BUS2_COMMAND",
    "HyperTransport bus 2 bandwidth - Command sent.",
    { ALLCNTRS, 0xF8}},
  { "NB_HT_BUS2_DATA",
    "HyperTransport bus 2 bandwidth - Data sent.",
    { ALLCNTRS, 0x1F8}},
  { "NB_HT_BUS2_BUFF",
    "HyperTransport bus 2 bandwidth - Buffer release sent.",
    { ALLCNTRS, 0x2F8}},
  { "NB_HT_BUS2_NOP",
    "HyperTransport bus 2 bandwidth - Nop sent.",
    { ALLCNTRS, 0x3F8}}
};

/*************************************/
/* CODE TO SUPPORT OPAQUE NATIVE MAP */
/*************************************/

char *_papi_hwd_ntv_code_to_name(unsigned int EventCode) {
   return(native_table[EventCode & NATIVE_AND_MASK].name);
}

char *_papi_hwd_ntv_code_to_descr(unsigned int EventCode) {
   return(native_table[EventCode & NATIVE_AND_MASK].description);
}

int _papi_hwd_ntv_code_to_bits(unsigned int EventCode, hwd_register_t *bits) {
   if(EventCode > sizeof(*native_table)) return(PAPI_ENOEVNT);
   bits = &native_table[EventCode & NATIVE_AND_MASK].resources;
   return(PAPI_OK);
}

int _papi_hwd_ntv_enum_events(unsigned int *EventCode, int modifier) {
   if(native_table[*EventCode & NATIVE_AND_MASK].resources.selector) {
      *EventCode = *EventCode + 1;
      return(PAPI_OK);
   }
   else {
      return(PAPI_ENOEVNT);
   }
}
