#ifndef PAPI_NO_VECTOR
/* Redfine the calls to vector table lookups */
#define _papi_hwd_read _papi_vector_table._vec_papi_hwd_read
#ifdef _WIN32
#define _papi_hwd_timer_callback _papi_vector_table._vec_papi_hwd_timer_callback
#else
#define _papi_hwd_dispatch_timer  _papi_vector_table._vec_papi_hwd_dispatch_timer 
#endif
#define _papi_hwd_get_overflow_address _papi_vector_table._vec_papi_hwd_get_overflow_address
#define _papi_hwd_start  _papi_vector_table._vec_papi_hwd_start 
#define _papi_hwd_stop _papi_vector_table._vec_papi_hwd_stop
#define _papi_hwd_get_real_cycles _papi_vector_table._vec_papi_hwd_get_real_cycles
#define _papi_hwd_get_real_usec _papi_vector_table._vec_papi_hwd_get_real_usec
#define _papi_hwd_get_virt_cycles  _papi_vector_table._vec_papi_hwd_get_virt_cycles 
#define _papi_hwd_get_virt_usec _papi_vector_table._vec_papi_hwd_get_virt_usec
#define _papi_hwd_reset _papi_vector_table._vec_papi_hwd_reset
#define _papi_hwd_write _papi_vector_table._vec_papi_hwd_write
#define _papi_hwd_stop_profiling _papi_vector_table._vec_papi_hwd_stop_profiling
#define _papi_hwd_init _papi_vector_table._vec_papi_hwd_init
#define _papi_hwd_init_control_state _papi_vector_table._vec_papi_hwd_init_control_state
#define _papi_hwd_update_shlib_info _papi_vector_table._vec_papi_hwd_update_shlib_info
#define _papi_hwd_get_system_info _papi_vector_table._vec_papi_hwd_get_system_info
#define _papi_hwd_get_memory_info _papi_vector_table._vec_papi_hwd_get_memory_info
#define _papi_hwd_update_control_state _papi_vector_table._vec_papi_hwd_update_control_state
#define _papi_hwd_ctl _papi_vector_table._vec_papi_hwd_ctl
#define _papi_hwd_set_overflow _papi_vector_table._vec_papi_hwd_set_overflow
#define _papi_hwd_set_profile _papi_vector_table._vec_papi_hwd_set_profile
#define _papi_hwd_add_prog_event _papi_vector_table._vec_papi_hwd_add_prog_event
#define _papi_hwd_set_domain _papi_vector_table._vec_papi_hwd_set_domain
#define _papi_hwd_ntv_enum_events _papi_vector_table._vec_papi_hwd_ntv_enum_events
#define _papi_hwd_ntv_code_to_name _papi_vector_table._vec_papi_hwd_ntv_code_to_name
#define _papi_hwd_ntv_code_to_descr _papi_vector_table._vec_papi_hwd_ntv_code_to_descr
#define _papi_hwd_ntv_code_to_bits _papi_vector_table._vec_papi_hwd_ntv_code_to_bits
#define _papi_hwd_ntv_bits_to_info _papi_vector_table._vec_papi_hwd_ntv_bits_to_info
#define _papi_hwd_allocate_registers _papi_vector_table._vec_papi_hwd_allocate_registers
#define _papi_hwd_bpt_map_avail _papi_vector_table._vec_papi_hwd_bpt_map_avail
#define _papi_hwd_bpt_map_set _papi_vector_table._vec_papi_hwd_bpt_map_set
#define _papi_hwd_bpt_map_exclusive _papi_vector_table._vec_papi_hwd_bpt_map_exclusive
#define _papi_hwd_bpt_map_shared _papi_vector_table._vec_papi_hwd_bpt_map_shared
#define _papi_hwd_bpt_map_preempt _papi_vector_table._vec_papi_hwd_bpt_map_preempt
#define _papi_hwd_bpt_map_update _papi_vector_table._vec_papi_hwd_bpt_map_update
#define _papi_hwd_get_dmem_info _papi_vector_table._vec_papi_hwd_get_dmem_info
#define _papi_hwd_shutdown _papi_vector_table._vec_papi_hwd_shutdown
#define _papi_hwd_shutdown_global _papi_vector_table._vec_papi_hwd_shutdown_global
#endif
