/* Redfine the calls to vector table lookups */
extern void _vectors_error();
#define VECERROR _vectors_error()
#define CHECKVEC(a) ((a)!=0?(a): VECERROR)
#define _papi_hwd_context_size		    CHECKVEC(_PAPI_VECTOR->context_size)
#define _papi_hwd_control_state_size	CHECKVEC(_PAPI_VECTOR->control_state_size)
#define _papi_hwd_register_size		    CHECKVEC(_PAPI_VECTOR->register_size)
#define _papi_hwd_reg_alloc_size	    CHECKVEC(_PAPI_VECTOR->reg_alloc_size)

#ifdef _WIN32
#define _papi_hwd_timer_callback	    CHECKVEC(_PAPI_VECTOR->timer_callback)
#else
#define _papi_hwd_dispatch_timer	    CHECKVEC(_PAPI_VECTOR->dispatch_timer) 
#endif
#define _papi_hwd_get_overflow_address	CHECKVEC(_PAPI_VECTOR->get_overflow_address)
#define _papi_hwd_start			CHECKVEC(_PAPI_VECTOR->start )
#define _papi_hwd_stop			CHECKVEC(_PAPI_VECTOR->stop)
#define _papi_hwd_read			CHECKVEC(_PAPI_VECTOR->read)
#define _papi_hwd_reset			CHECKVEC(_PAPI_VECTOR->reset)
#define _papi_hwd_write			CHECKVEC(_PAPI_VECTOR->write)
#define _papi_hwd_get_real_cycles	CHECKVEC(_PAPI_VECTOR->get_real_cycles)
#define _papi_hwd_get_real_usec		CHECKVEC(_PAPI_VECTOR->get_real_usec)
#define _papi_hwd_get_virt_cycles	CHECKVEC(_PAPI_VECTOR->get_virt_cycles)
#define _papi_hwd_get_virt_usec		CHECKVEC(_PAPI_VECTOR->get_virt_usec)
#define _papi_hwd_stop_profiling	CHECKVEC(_PAPI_VECTOR->stop_profiling)
#define _papi_hwd_init			CHECKVEC(_PAPI_VECTOR->init)
#define _papi_hwd_init_control_state	CHECKVEC(_PAPI_VECTOR->init_control_state)
#define _papi_hwd_update_shlib_info	CHECKVEC(_PAPI_VECTOR->update_shlib_info)
#define _papi_hwd_get_system_info	CHECKVEC(_PAPI_VECTOR->get_system_info)
#define _papi_hwd_get_memory_info	CHECKVEC(_PAPI_VECTOR->get_memory_info)
#define _papi_hwd_update_control_state	CHECKVEC(_PAPI_VECTOR->update_control_state)
#define _papi_hwd_ctl			CHECKVEC(_PAPI_VECTOR->ctl)
#define _papi_hwd_set_overflow		CHECKVEC(_PAPI_VECTOR->set_overflow)
#define _papi_hwd_set_profile		CHECKVEC(_PAPI_VECTOR->set_profile)
#define _papi_hwd_add_prog_event	CHECKVEC(_PAPI_VECTOR->add_prog_event)
#define _papi_hwd_set_domain		CHECKVEC(_PAPI_VECTOR->set_domain)
#define _papi_hwd_ntv_enum_events	CHECKVEC(_PAPI_VECTOR->ntv_enum_events)
#define _papi_hwd_ntv_code_to_name	CHECKVEC(_PAPI_VECTOR->ntv_code_to_name)
#define _papi_hwd_ntv_code_to_descr	CHECKVEC(_PAPI_VECTOR->ntv_code_to_descr)
#define _papi_hwd_ntv_code_to_bits	CHECKVEC(_PAPI_VECTOR->ntv_code_to_bits)
#define _papi_hwd_ntv_bits_to_info	CHECKVEC(_PAPI_VECTOR->ntv_bits_to_info)
#define _papi_hwd_allocate_registers	CHECKVEC(_PAPI_VECTOR->allocate_registers)
#define _papi_hwd_bpt_map_avail		CHECKVEC(_PAPI_VECTOR->bpt_map_avail)
#define _papi_hwd_bpt_map_set		CHECKVEC(_PAPI_VECTOR->bpt_map_set)
#define _papi_hwd_bpt_map_exclusive	CHECKVEC(_PAPI_VECTOR->bpt_map_exclusive)
#define _papi_hwd_bpt_map_shared	CHECKVEC(_PAPI_VECTOR->bpt_map_shared)
#define _papi_hwd_bpt_map_preempt	CHECKVEC(_PAPI_VECTOR->bpt_map_preempt)
#define _papi_hwd_bpt_map_update	CHECKVEC(_PAPI_VECTOR->bpt_map_update)
#define _papi_hwd_get_dmem_info		CHECKVEC(_PAPI_VECTOR->get_dmem_info)
#define _papi_hwd_shutdown		CHECKVEC(_PAPI_VECTOR->shutdown)
#define _papi_hwd_shutdown_global	CHECKVEC(_PAPI_VECTOR->shutdown_global)
