/* Redfine the calls to vector table lookups */
#define _papi_hwd_context_size		_papi_frm_vector.context_size
#define _papi_hwd_control_state_size	_papi_frm_vector.control_state_size
#define _papi_hwd_register_size		_papi_frm_vector.register_size
#define _papi_hwd_reg_alloc_size	_papi_frm_vector.reg_alloc_size

#ifdef _WIN32
#define _papi_hwd_timer_callback	_papi_frm_vector.timer_callback
#else
#define _papi_hwd_dispatch_timer	_papi_frm_vector.dispatch_timer 
#endif
#define _papi_hwd_get_overflow_address	_papi_frm_vector.get_overflow_address
#define _papi_hwd_start			_papi_frm_vector.start 
#define _papi_hwd_stop			_papi_frm_vector.stop
#define _papi_hwd_read			_papi_frm_vector.read
#define _papi_hwd_reset			_papi_frm_vector.reset
#define _papi_hwd_write			_papi_frm_vector.write
#define _papi_hwd_get_real_cycles	_papi_frm_vector.get_real_cycles
#define _papi_hwd_get_real_usec		_papi_frm_vector.get_real_usec
#define _papi_hwd_get_virt_cycles	_papi_frm_vector.get_virt_cycles 
#define _papi_hwd_get_virt_usec		_papi_frm_vector.get_virt_usec
#define _papi_hwd_stop_profiling	_papi_frm_vector.stop_profiling
#define _papi_hwd_init			_papi_frm_vector.init
#define _papi_hwd_init_control_state	_papi_frm_vector.init_control_state
#define _papi_hwd_update_shlib_info	_papi_frm_vector.update_shlib_info
#define _papi_hwd_get_system_info	_papi_frm_vector.get_system_info
#define _papi_hwd_get_memory_info	_papi_frm_vector.get_memory_info
#define _papi_hwd_update_control_state	_papi_frm_vector.update_control_state
#define _papi_hwd_ctl			_papi_frm_vector.ctl
#define _papi_hwd_set_overflow		_papi_frm_vector.set_overflow
#define _papi_hwd_set_profile		_papi_frm_vector.set_profile
#define _papi_hwd_add_prog_event	_papi_frm_vector.add_prog_event
#define _papi_hwd_set_domain		_papi_frm_vector.set_domain
#define _papi_hwd_ntv_enum_events	_papi_frm_vector.ntv_enum_events
#define _papi_hwd_ntv_code_to_name	_papi_frm_vector.ntv_code_to_name
#define _papi_hwd_ntv_code_to_descr	_papi_frm_vector.ntv_code_to_descr
#define _papi_hwd_ntv_code_to_bits	_papi_frm_vector.ntv_code_to_bits
#define _papi_hwd_ntv_bits_to_info	_papi_frm_vector.ntv_bits_to_info
#define _papi_hwd_allocate_registers	_papi_frm_vector.allocate_registers
#define _papi_hwd_bpt_map_avail		_papi_frm_vector.bpt_map_avail
#define _papi_hwd_bpt_map_set		_papi_frm_vector.bpt_map_set
#define _papi_hwd_bpt_map_exclusive	_papi_frm_vector.bpt_map_exclusive
#define _papi_hwd_bpt_map_shared	_papi_frm_vector.bpt_map_shared
#define _papi_hwd_bpt_map_preempt	_papi_frm_vector.bpt_map_preempt
#define _papi_hwd_bpt_map_update	_papi_frm_vector.bpt_map_update
#define _papi_hwd_get_dmem_info		_papi_frm_vector.get_dmem_info
#define _papi_hwd_shutdown		_papi_frm_vector.shutdown
#define _papi_hwd_shutdown_global	_papi_frm_vector.shutdown_global
