
/* file: papiStrings_US.h

This file contains the majority of strings that are presented to a user.
Since they are all collected in one place, these strings can readily be
translated into another language and the appropriate header conditionally
included to allow internationalization of the PAPI messages.

To create a version of PAPI in your native language, do the following:
- copy this file into a new file named "papiStrings_XX.h".
	("XX" is the two letter WWW domain code for the target country.)
- Translate the strings in the new file to the target language.
- Modify "papiStrings.h" to support the new file.
- Please forward the new "papiStrings.h" and "papiStrings_XX.h" to:
	perfapi-devel@nacse.org

This file should be modified to stay synchronized with the events defined
in "papiStdEventDefs.h" and the return codes defined in "papi.h".
*/

/************************************************************/
/* This block provides long descriptions of each PAPI event */
/* It should be synchronized with "papiStdEventDefs.h"      */
/************************************************************/
#define PAPI_L1_DCM_dsc  "Level 1 data cache misses"
#define PAPI_L1_ICM_dsc  "Level 1 instruction cache misses"
#define PAPI_L2_DCM_dsc  "Level 2 data cache misses"
#define PAPI_L2_ICM_dsc  "Level 2 instruction cache misses"
#define PAPI_L3_DCM_dsc  "Level 3 data cache misses"
#define PAPI_L3_ICM_dsc  "Level 3 instruction cache misses"
#define PAPI_L1_TCM_dsc  "Level 1 cache misses"
#define PAPI_L2_TCM_dsc  "Level 2 cache misses"
#define PAPI_L3_TCM_dsc  "Level 3 cache misses"
#define PAPI_CA_SNP_dsc  "Requests for a snoop"
#define PAPI_CA_SHR_dsc  "Requests for exclusive access to shared cache line"
#define PAPI_CA_CLN_dsc  "Requests for exclusive access to clean cache line"
#define PAPI_CA_INV_dsc  "Requests for cache line invalidation"
#define PAPI_CA_ITV_dsc  "Requests for cache line intervention"
#define PAPI_L3_LDM_dsc  "Level 3 load misses"
#define PAPI_L3_STM_dsc  "Level 3 store misses"
#define PAPI_BRU_IDL_dsc "Cycles branch units are idle"
#define PAPI_FXU_IDL_dsc "Cycles integer units are idle"
#define PAPI_FPU_IDL_dsc "Cycles floating point units are idle"
#define PAPI_LSU_IDL_dsc "Cycles load/store units are idle"
#define PAPI_TLB_DM_dsc  "Data translation lookaside buffer misses"
#define PAPI_TLB_IM_dsc  "Instruction translation lookaside buffer misses"
#define PAPI_TLB_TL_dsc  "Total translation lookaside buffer misses"
#define PAPI_L1_LDM_dsc  "Level 1 load misses"
#define PAPI_L1_STM_dsc  "Level 1 store misses"
#define PAPI_L2_LDM_dsc  "Level 2 load misses"
#define PAPI_L2_STM_dsc  "Level 2 store misses"
#define PAPI_BTAC_M_dsc  "Branch target address cache misses"
#define PAPI_PRF_DM_dsc  "Data prefetch cache misses"
#define PAPI_L3_DCH_dsc  "Level 3 data cache hits"
#define PAPI_TLB_SD_dsc  "Translation lookaside buffer shootdowns"
#define PAPI_CSR_FAL_dsc "Failed store conditional instructions"
#define PAPI_CSR_SUC_dsc "Successful store conditional instructions"
#define PAPI_CSR_TOT_dsc "Total store conditional instructions"
#define PAPI_MEM_SCY_dsc "Cycles Stalled Waiting for memory accesses"
#define PAPI_MEM_RCY_dsc "Cycles Stalled Waiting for memory Reads"
#define PAPI_MEM_WCY_dsc "Cycles Stalled Waiting for memory writes"
#define PAPI_STL_ICY_dsc "Cycles with no instruction issue"
#define PAPI_FUL_ICY_dsc "Cycles with maximum instruction issue"
#define PAPI_STL_CCY_dsc "Cycles with no instructions completed"
#define PAPI_FUL_CCY_dsc "Cycles with maximum instructions completed"
#define PAPI_HW_INT_dsc  "Hardware interrupts"
#define PAPI_BR_UCN_dsc  "Unconditional branch instructions"
#define PAPI_BR_CN_dsc   "Conditional branch instructions"
#define PAPI_BR_TKN_dsc  "Conditional branch instructions taken" 
#define PAPI_BR_NTK_dsc  "Conditional branch instructions not taken" 
#define PAPI_BR_MSP_dsc  "Conditional branch instructions mispredicted"
#define PAPI_BR_PRC_dsc  "Conditional branch instructions correctly predicted"
#define PAPI_FMA_INS_dsc "FMA instructions completed"
#define PAPI_TOT_IIS_dsc "Instructions issued"
#define PAPI_TOT_INS_dsc "Instructions completed"
#define PAPI_INT_INS_dsc "Integer instructions"
#define PAPI_FP_INS_dsc  "Floating point instructions"
#define PAPI_LD_INS_dsc  "Load instructions"
#define PAPI_SR_INS_dsc  "Store instructions"
#define PAPI_BR_INS_dsc  "Branch instructions"
#define PAPI_VEC_INS_dsc "Vector/SIMD instructions"
#define PAPI_FLOPS_dsc   "Floating point instructions per second"
#define PAPI_RES_STL_dsc "Cycles stalled on any resource"
#define PAPI_FP_STAL_dsc "Cycles the FP unit(s) are stalled"
#define PAPI_TOT_CYC_dsc "Total cycles"
#define PAPI_IPS_dsc     "Instructions per second"
#define PAPI_LST_INS_dsc "Load/store instructions completed"
#define PAPI_SYC_INS_dsc "Synchronization instructions completed"
#define PAPI_L1_DCH_dsc  "Level 1 data cache hits"
#define PAPI_L2_DCH_dsc  "Level 2 data cache hits"
#define PAPI_L1_DCA_dsc  "Level 1 data cache accesses"
#define PAPI_L2_DCA_dsc  "Level 2 data cache accesses"
#define PAPI_L3_DCA_dsc  "Level 3 data cache accesses"
#define PAPI_L1_DCR_dsc  "Level 1 data cache reads"
#define PAPI_L2_DCR_dsc  "Level 2 data cache reads"
#define PAPI_L3_DCR_dsc  "Level 3 data cache reads"
#define PAPI_L1_DCW_dsc  "Level 1 data cache writes"
#define PAPI_L2_DCW_dsc  "Level 2 data cache writes"
#define PAPI_L3_DCW_dsc  "Level 3 data cache writes"
#define PAPI_L1_ICH_dsc  "Level 1 instruction cache hits"
#define PAPI_L2_ICH_dsc  "Level 2 instruction cache hits"
#define PAPI_L3_ICH_dsc  "Level 3 instruction cache hits"
#define PAPI_L1_ICA_dsc  "Level 1 instruction cache accesses"
#define PAPI_L2_ICA_dsc  "Level 2 instruction cache accesses"
#define PAPI_L3_ICA_dsc  "Level 3 instruction cache accesses"
#define PAPI_L1_ICR_dsc  "Level 1 instruction cache reads"
#define PAPI_L2_ICR_dsc  "Level 2 instruction cache reads"
#define PAPI_L3_ICR_dsc  "Level 3 instruction cache reads"
#define PAPI_L1_ICW_dsc  "Level 1 instruction cache writes"
#define PAPI_L2_ICW_dsc  "Level 2 instruction cache writes"
#define PAPI_L3_ICW_dsc  "Level 3 instruction cache writes"
#define PAPI_L1_TCH_dsc  "Level 1 total cache hits"
#define PAPI_L2_TCH_dsc  "Level 2 total cache hits"
#define PAPI_L3_TCH_dsc  "Level 3 total cache hits"
#define PAPI_L1_TCA_dsc  "Level 1 total cache accesses"
#define PAPI_L2_TCA_dsc  "Level 2 total cache accesses"
#define PAPI_L3_TCA_dsc  "Level 3 total cache accesses"
#define PAPI_L1_TCR_dsc  "Level 1 total cache reads"
#define PAPI_L2_TCR_dsc  "Level 2 total cache reads"
#define PAPI_L3_TCR_dsc  "Level 3 total cache reads"
#define PAPI_L1_TCW_dsc  "Level 1 total cache writes"
#define PAPI_L2_TCW_dsc  "Level 2 total cache writes"
#define PAPI_L3_TCW_dsc  "Level 3 total cache writes"
#define PAPI_FML_INS_dsc "Floating point multiply instructions"
#define PAPI_FAD_INS_dsc "Floating point add instructions"
#define PAPI_FDV_INS_dsc "Floating point divide instructions"
#define PAPI_FSQ_INS_dsc "Floating point square root instructions"
#define PAPI_FNV_INS_dsc "Floating point inverse instructions"

/*************************************************************/
/* This block provides short descriptions of each PAPI event */
/* These should be 18 characters or less, and can be used as */
/* labels for GUI-based performance monitoring tools         */
/* It should be synchronized with "papiStdEventDefs.h"       */
/*************************************************************/
/*                        1234567890123456789                */ 
#define PAPI_L1_DCM_lbl  "L1D cache misses"
#define PAPI_L1_ICM_lbl  "L1I cache misses"
#define PAPI_L2_DCM_lbl  "L2D cache misses"
#define PAPI_L2_ICM_lbl  "L2I cache misses"
#define PAPI_L3_DCM_lbl  "L3D cache misses"
#define PAPI_L3_ICM_lbl  "L3I cache misses"
#define PAPI_L1_TCM_lbl  "L1 cache misses"
#define PAPI_L2_TCM_lbl  "L2 cache misses"
#define PAPI_L3_TCM_lbl  "L3 cache misses"
#define PAPI_CA_SNP_lbl  "Snoop Requests"
#define PAPI_CA_SHR_lbl  "Ex Acces shared CL"
#define PAPI_CA_CLN_lbl  "Ex Access clean CL"
#define PAPI_CA_INV_lbl  "Cache ln invalid"
#define PAPI_CA_ITV_lbl  "Cache ln intervene"
#define PAPI_L3_LDM_lbl  "L3 load misses"
#define PAPI_L3_STM_lbl  "L3 store misses"
#define PAPI_BRU_IDL_lbl "Branch idle cycles"
#define PAPI_FXU_IDL_lbl "IU idle cycles"
#define PAPI_FPU_IDL_lbl "FPU idle cycles"
#define PAPI_LSU_IDL_lbl "L/SU idle cycles"
#define PAPI_TLB_DM_lbl  "Data TLB misses"
#define PAPI_TLB_IM_lbl  "Instr TLB misses"
#define PAPI_TLB_TL_lbl  "Total TLB misses"
#define PAPI_L1_LDM_lbl  "L1 load misses"
#define PAPI_L1_STM_lbl  "L1 store misses"
#define PAPI_L2_LDM_lbl  "L2 load misses"
#define PAPI_L2_STM_lbl  "L2 store misses"
#define PAPI_BTAC_M_lbl  "Br targt addr miss"
#define PAPI_PRF_DM_lbl  "Data prefetch miss"
#define PAPI_L3_DCH_lbl  "L3D cache hits"
#define PAPI_TLB_SD_lbl  "TLB shootdowns"
#define PAPI_CSR_FAL_lbl "Failed store cond"
#define PAPI_CSR_SUC_lbl "Good store cond"
#define PAPI_CSR_TOT_lbl "Total store cond"
#define PAPI_MEM_SCY_lbl "Stalled mem cycles"
#define PAPI_MEM_RCY_lbl "Stalled rd cycles"
#define PAPI_MEM_WCY_lbl "Stalled wr cycles"
#define PAPI_STL_ICY_lbl "No instr issue"
#define PAPI_FUL_ICY_lbl "Max instr issue"
#define PAPI_STL_CCY_lbl "No instr done"
#define PAPI_FUL_CCY_lbl "Max instr done"
#define PAPI_HW_INT_lbl  "Hdw interrupts"
#define PAPI_BR_UCN_lbl  "Uncond branch"
#define PAPI_BR_CN_lbl   "Cond branch"
#define PAPI_BR_TKN_lbl  "Cond branch taken" 
#define PAPI_BR_NTK_lbl  "Cond br not taken" 
#define PAPI_BR_MSP_lbl  "Cond br mspredictd"
#define PAPI_BR_PRC_lbl  "Cond br predicted"
#define PAPI_FMA_INS_lbl "FMAs completed"
#define PAPI_TOT_IIS_lbl "Instr issued"
#define PAPI_TOT_INS_lbl "Instr completed"
#define PAPI_INT_INS_lbl "Int instructions"
#define PAPI_FP_INS_lbl  "FP instructions"
#define PAPI_LD_INS_lbl  "Loads"
#define PAPI_SR_INS_lbl  "Stores"
#define PAPI_BR_INS_lbl  "Branches"
#define PAPI_VEC_INS_lbl "Vector/SIMD instr"
#define PAPI_FLOPS_lbl   "FP instr / second"
#define PAPI_RES_STL_lbl "Stalled res cycles"
#define PAPI_FP_STAL_lbl "Stalled FPU cycles"
#define PAPI_TOT_CYC_lbl "Total cycles"
#define PAPI_IPS_lbl     "Instr / second"
#define PAPI_LST_INS_lbl "L/S completed"
#define PAPI_SYC_INS_lbl "Syncs completed"
#define PAPI_L1_DCH_lbl  "L1D cache hits"
#define PAPI_L2_DCH_lbl  "L2D cache hits"
#define PAPI_L1_DCA_lbl  "L1D cache accesses"
#define PAPI_L2_DCA_lbl  "L2D cache accesses"
#define PAPI_L3_DCA_lbl  "L3D cache accesses"
#define PAPI_L1_DCR_lbl  "L1D cache reads"
#define PAPI_L2_DCR_lbl  "L2D cache reads"
#define PAPI_L3_DCR_lbl  "L3D cache reads"
#define PAPI_L1_DCW_lbl  "L1D cache writes"
#define PAPI_L2_DCW_lbl  "L2D cache writes"
#define PAPI_L3_DCW_lbl  "L3D cache writes"
#define PAPI_L1_ICH_lbl  "L1I cache hits"
#define PAPI_L2_ICH_lbl  "L2I cache hits"
#define PAPI_L3_ICH_lbl  "L3I cache hits"
#define PAPI_L1_ICA_lbl  "L1I cache accesses"
#define PAPI_L2_ICA_lbl  "L2I cache accesses"
#define PAPI_L3_ICA_lbl  "L3I cache accesses"
#define PAPI_L1_ICR_lbl  "L1I cache reads"
#define PAPI_L2_ICR_lbl  "L2I cache reads"
#define PAPI_L3_ICR_lbl  "L3I cache reads"
#define PAPI_L1_ICW_lbl  "L1I cache writes"
#define PAPI_L2_ICW_lbl  "L2I cache writes"
#define PAPI_L3_ICW_lbl  "L3I cache writes"
#define PAPI_L1_TCH_lbl  "L1 cache hits"
#define PAPI_L2_TCH_lbl  "L2 cache hits"
#define PAPI_L3_TCH_lbl  "L3 cache hits"
#define PAPI_L1_TCA_lbl  "L1 cache accesses"
#define PAPI_L2_TCA_lbl  "L2 cache accesses"
#define PAPI_L3_TCA_lbl  "L3 cache accesses"
#define PAPI_L1_TCR_lbl  "L1 cache reads"
#define PAPI_L2_TCR_lbl  "L2 cache reads"
#define PAPI_L3_TCR_lbl  "L3 cache reads"
#define PAPI_L1_TCW_lbl  "L1 cache writes"
#define PAPI_L2_TCW_lbl  "L2 cache writes"
#define PAPI_L3_TCW_lbl  "L3 cache writes"
#define PAPI_FML_INS_lbl "FPU multiply"
#define PAPI_FAD_INS_lbl "FPU add"
#define PAPI_FDV_INS_lbl "FPU divide"
#define PAPI_FSQ_INS_lbl "FPU square root"
#define PAPI_FNV_INS_lbl "FPU inverse"

/********************************************************/
/* This block provides descriptions of each PAPI return */
/* It should be synchronized with return codes          */
/* found in "papi.h"                                    */
/********************************************************/
#define PAPI_OK_dsc         "No error"
#define PAPI_EINVAL_dsc     "Invalid argument"
#define PAPI_ENOMEM_dsc     "Insufficient memory"
#define PAPI_ESYS_dsc       "A System/C library call failed"
#define PAPI_ESBSTR_dsc     "Not supported by substrate" 
#define PAPI_ECLOST_dsc     "Access to the counters was lost or interrupted"
#define PAPI_EBUG_dsc       "Internal error, please send mail to the developers"
#define PAPI_ENOEVNT_dsc    "Event does not exist"
#define PAPI_ECNFLCT_dsc    "Event exists, but cannot be counted due to hardware resource limits" 
#define PAPI_ENOTRUN_dsc    "EventSet is currently not running"
#define PAPI_EISRUN_dsc     "EventSet is currently counting"
#define PAPI_ENOEVST_dsc    "No such EventSet available"
#define PAPI_ENOTPRESET_dsc "Event in argument is not a valid preset"
#define PAPI_ENOCNTR_dsc    "Hardware does not support performance counters"
#define PAPI_EMISC_dsc      "Unknown error code"

/********************************************************/
/* This block provides general strings used in PAPI     */
/* If a new string is needed for PAPI prompts           */
/* it should be placed in this file and referenced by   */
/* label. In that way it can be translated as needed.   */
/********************************************************/
#define PAPI_ERROR_CODE_str      "PAPI Error Code"
#define PAPI_THREAD_INIT_str     "PAPI_thread_init: This should only be called once\n"
#define PAPI_SHUTDOWN_str	 "PAPI_shutdown error: PAPI currently not initialized\n"
#define PAPI_NO_RESTORE_str	 "PAPI_restore is currently not implemented\n"
#define PAPI_NO_SAVE_str	 "PAPI_save is currently not implemented\n"
#define PAPI_SHUTDOWN_SYNC_str	 "PAPI_shutdown error: Other threads still have running EventSets\n"
