
/* file: papiStrings_IT.h

This file contains the majority of strings that are presented to a user.
Since they are all collected in one place, these strings can easily be
translated into another language and the appropriate header conditionally
included to allow internationalization of the PAPI messages.

To create a version of PAPI in your native language, do the following:
- copy this file into a new file named "papiStrings_XX.h".
	("XX" is the two letter WWW domain code for the target country.)
- Translate the strings in the new file to the target language.
- Modify "papiStrings.h" to support the new file.
- Please forward the new "papiStrings.h" and "papiStrings_XX.h" to:
	perfapi-devel@nacse.org

This file should be modified to stay synchronized with the events defined
in "papiStdEventDefs.h" and the return codes defined in "papi.h".
*/

/* NOTE: Please pardon the atrocious Italian in this file. It was generated
	automatically from Alta Vista's BabelFish translator. Also, I removed
	all diacritical marks. These should be replaced when the translation
	is polished...
*/

/************************************************************/
/* This block provides long descriptions of each PAPI event */
/* It should be synchronized with "papiStdEventDefs.h"      */
/************************************************************/
#define PAPI_L1_DCM_dsc  "1 mancanza di nascondiglio Livella di dati"
#define PAPI_L1_ICM_dsc  "1 mancanza di nascondiglio Livella di istruzione"
#define PAPI_L2_DCM_dsc  "mancanza di nascondiglio Livella di 2 dati"
#define PAPI_L2_ICM_dsc  "mancanza di nascondiglio Livella di 2 istruzioni"
#define PAPI_L3_DCM_dsc  "mancanza di nascondiglio Livella di 3 dati"
#define PAPI_L3_ICM_dsc  "mancanza di nascondiglio Livella di 3 istruzioni"
#define PAPI_L1_TCM_dsc  "1 mancanza di nascondiglio Livella"
#define PAPI_L2_TCM_dsc  "mancanza di nascondiglio Livella 2"
#define PAPI_L3_TCM_dsc  "mancanza di nascondiglio Livella 3"
#define PAPI_CA_SNP_dsc  "richieste per uno snoop"
#define PAPI_CA_SHR_dsc  "richieste per accesso esclusivo alla riga comune del nascondiglio"
#define PAPI_CA_CLN_dsc  "le richieste per accesso esclusivo al nascondiglio pulito si allineano"
#define PAPI_CA_INV_dsc  "le richieste per il nascondiglio allineano il invalidation"
#define PAPI_CA_ITV_dsc  "le richieste per il nascondiglio allineano l' intervento"
#define PAPI_L3_LDM_dsc  "una mancanza Livella dei 3 carichi"
#define PAPI_L3_STM_dsc  "una mancanza Livella dei 3 depositi"
#define PAPI_BRU_IDL_dsc "le unita del ramo dei cicli sono al minimo"
#define PAPI_FXU_IDL_dsc "le unita di numero intero dei cicli sono al minimo"
#define PAPI_FPU_IDL_dsc "le unita della virgola mobile dei cicli sono al minimo"
#define PAPI_LSU_IDL_dsc "i cicli caricano / unita del deposito sono al minimo"
#define PAPI_TLB_DM_dsc  "mancanza dell' amplificatore di lookaside di traduzione di dati"
#define PAPI_TLB_IM_dsc  "mancanza dell' amplificatore di lookaside di traduzione di istruzione"
#define PAPI_TLB_TL_dsc  "mancanza totale dell' amplificatore di lookaside di traduzione"
#define PAPI_L1_LDM_dsc  "il 1 carico Livello manca"
#define PAPI_L1_STM_dsc  "il 1 deposito Livello manca"
#define PAPI_L2_LDM_dsc  "una mancanza Livella dei 2 carichi"
#define PAPI_L2_STM_dsc  "una mancanza Livella dei 2 depositi"
#define PAPI_BTAC_M_dsc  "mancanza di nascondiglio di indirizzo dell' obiettivo del ramo"
#define PAPI_PRF_DM_dsc  "mancanza di nascondiglio del prefetch di dati"
#define PAPI_L3_DCH_dsc  "3 colpi di nascondiglio Livelli di dati"
#define PAPI_TLB_SD_dsc  "shootdowns dell' amplificatore di lookaside di traduzione"
#define PAPI_CSR_FAL_dsc "istruzioni condizionali guastate del deposito"
#define PAPI_CSR_SUC_dsc "istruzioni condizionali del deposito riuscito"
#define PAPI_CSR_TOT_dsc "istruzioni condizionali del deposito totale"
#define PAPI_MEM_SCY_dsc "cicla gli accessi di memoria attendenti arrestati"
#define PAPI_MEM_RCY_dsc "cicla la memoria attendente arrestata legge"
#define PAPI_MEM_WCY_dsc "cicla la memoria attendente arrestata scrive"
#define PAPI_STL_ICY_dsc "cicli senza l' edizione di istruzione"
#define PAPI_FUL_ICY_dsc "cicli con l' edizione massima di istruzione"
#define PAPI_STL_CCY_dsc "cicli senza le istruzioni completate"
#define PAPI_FUL_CCY_dsc "cicli con le istruzioni massime completate"
#define PAPI_HW_INT_dsc  "il hardware interrompe"
#define PAPI_BR_UCN_dsc  "istruzioni di ramo incondizionate"
#define PAPI_BR_CN_dsc   "istruzioni di ramo condizionali"
#define PAPI_BR_TKN_dsc  "le istruzioni di ramo condizionali prese"
#define PAPI_BR_NTK_dsc  "istruzioni di ramo condizionali non prese"
#define PAPI_BR_MSP_dsc  "istruzioni di ramo condizionali previste in modo errato"
#define PAPI_BR_PRC_dsc  "istruzioni di ramo condizionali previste correttamente"
#define PAPI_FMA_INS_dsc "istruzioni di FMA completate"
#define PAPI_TOT_IIS_dsc "istruzioni pubblicate"
#define PAPI_TOT_INS_dsc "istruzioni completate"
#define PAPI_INT_INS_dsc "istruzioni di numero intero"
#define PAPI_FP_INS_dsc  "istruzioni della virgola mobile"
#define PAPI_LD_INS_dsc  "istruzioni del carico"
#define PAPI_SR_INS_dsc  "memorizzare le istruzioni"
#define PAPI_BR_INS_dsc  "istruzioni di ramo"
#define PAPI_VEC_INS_dsc "istruzioni di Vector/SIMD"
#define PAPI_FLOPS_dsc   "istruzioni della virgola mobile al secondo"
#define PAPI_RES_STL_dsc "cicli arrestati su qualsiasi risorsa"
#define PAPI_FP_STAL_dsc "cicla il unit(s) della virgola mobile si arrestano"
#define PAPI_TOT_CYC_dsc "cicli totali"
#define PAPI_IPS_dsc     "istruzioni al secondo"
#define PAPI_LST_INS_dsc "istruzioni deposito / del carico completate"
#define PAPI_SYC_INS_dsc "istruzioni di sincronizzazione completate"
#define PAPI_L1_DCH_dsc  "i colpi di 1 nascondiglio Livelli di dati"
#define PAPI_L2_DCH_dsc  "2 colpi di nascondiglio Livelli di dati"
#define PAPI_L1_DCA_dsc  "gli accessi Livelli del 1 nascondiglio di dati"
#define PAPI_L2_DCA_dsc  "2 accessi Livelli del nascondiglio di dati"
#define PAPI_L3_DCA_dsc  "3 accessi Livelli del nascondiglio di dati"
#define PAPI_L1_DCR_dsc  "il 1 nascondiglio Livello di dati legge"
#define PAPI_L2_DCR_dsc  "un nascondiglio Livello di 2 dati legge"
#define PAPI_L3_DCR_dsc  "un nascondiglio Livello di 3 dati legge"
#define PAPI_L1_DCW_dsc  "il 1 nascondiglio Livello di dati scrive"
#define PAPI_L2_DCW_dsc  "un nascondiglio Livello di 2 dati scrive"
#define PAPI_L3_DCW_dsc  "un nascondiglio Livello di 3 dati scrive"
#define PAPI_L1_ICH_dsc  "i colpi di 1 nascondiglio Livelli di istruzione"
#define PAPI_L2_ICH_dsc  "2 colpi di nascondiglio Livelli di istruzione"
#define PAPI_L3_ICH_dsc  "3 colpi di nascondiglio Livelli di istruzione"
#define PAPI_L1_ICA_dsc  "gli accessi Livelli del 1 nascondiglio di istruzione"
#define PAPI_L2_ICA_dsc  "2 accessi Livelli del nascondiglio di istruzione"
#define PAPI_L3_ICA_dsc  "3 accessi Livelli del nascondiglio di istruzione"
#define PAPI_L1_ICR_dsc  "il 1 nascondiglio Livello di istruzione legge"
#define PAPI_L2_ICR_dsc  "un nascondiglio Livello di 2 istruzioni legge"
#define PAPI_L3_ICR_dsc  "un nascondiglio Livello di 3 istruzioni legge"
#define PAPI_L1_ICW_dsc  "il 1 nascondiglio Livello di istruzione scrive"
#define PAPI_L2_ICW_dsc  "un nascondiglio Livello di 2 istruzioni scrive"
#define PAPI_L3_ICW_dsc  "un nascondiglio Livello di 3 istruzioni scrive" 
#define PAPI_L1_TCH_dsc  "i colpi di 1 nascondiglio totali Livelli"
#define PAPI_L2_TCH_dsc  "2 colpi di nascondiglio totali Livelli"
#define PAPI_L3_TCH_dsc  "3 colpi di nascondiglio totali Livelli"
#define PAPI_L1_TCA_dsc  "il 1 nascondiglio totale Livello accede a"
#define PAPI_L2_TCA_dsc  "2 accessi totali Livelli del nascondiglio"
#define PAPI_L3_TCA_dsc  "3 accessi totali Livelli del nascondiglio"
#define PAPI_L1_TCR_dsc  "il 1 nascondiglio totale Livello legge"
#define PAPI_L2_TCR_dsc  "il nascondiglio totale 2 Livelli legge"
#define PAPI_L3_TCR_dsc  "il nascondiglio totale 3 Livelli legge"
#define PAPI_L1_TCW_dsc  "il 1 nascondiglio totale Livello scrive"
#define PAPI_L2_TCW_dsc  "il nascondiglio totale 2 Livelli scrive"
#define PAPI_L3_TCW_dsc  "il nascondiglio totale 3 Livelli scrive"
#define PAPI_FML_INS_dsc "la virgola mobile moltiplica le istruzioni"
#define PAPI_FAD_INS_dsc "la virgola mobile aggiunge le istruzioni"
#define PAPI_FDV_INS_dsc "la virgola mobile divide le istruzioni"
#define PAPI_FSQ_INS_dsc "istruzioni della radice quadrata della virgola mobile"
#define PAPI_FNV_INS_dsc "istruzioni inverse della virgola mobile"

/*************************************************************/
/* This block provides short descriptions of each PAPI event */
/* These should be 18 characters or less, and can be used as */
/* labels for GUI-based performance monitoring tools         */
/* It should be synchronized with "papiStdEventDefs.h"       */
/*************************************************************/
/*                        1234567890123456789                */ 
#define PAPI_L1_DCM_lbl  "L1D cache misses"
#define PAPI_L1_ICM_lbl  "L1I cache misses"
#define PAPI_L2_DCM_lbl  "L2D cache misses"
#define PAPI_L2_ICM_lbl  "L2I cache misses"
#define PAPI_L3_DCM_lbl  "L3D cache misses"
#define PAPI_L3_ICM_lbl  "L3I cache misses"
#define PAPI_L1_TCM_lbl  "L1 cache misses"
#define PAPI_L2_TCM_lbl  "L2 cache misses"
#define PAPI_L3_TCM_lbl  "L3 cache misses"
#define PAPI_CA_SNP_lbl  "Snoop Requests"
#define PAPI_CA_SHR_lbl  "Ex Acces shared CL"
#define PAPI_CA_CLN_lbl  "Ex Access clean CL"
#define PAPI_CA_INV_lbl  "Cache ln invalid"
#define PAPI_CA_ITV_lbl  "Cache ln intervene"
#define PAPI_L3_LDM_lbl  "L3 load misses"
#define PAPI_L3_STM_lbl  "L3 store misses"
#define PAPI_BRU_IDL_lbl "Branch idle cycles"
#define PAPI_FXU_IDL_lbl "IU idle cycles"
#define PAPI_FPU_IDL_lbl "FPU idle cycles"
#define PAPI_LSU_IDL_lbl "L/SU idle cycles"
#define PAPI_TLB_DM_lbl  "Data TLB misses"
#define PAPI_TLB_IM_lbl  "Instr TLB misses"
#define PAPI_TLB_TL_lbl  "Total TLB misses"
#define PAPI_L1_LDM_lbl  "L1 load misses"
#define PAPI_L1_STM_lbl  "L1 store misses"
#define PAPI_L2_LDM_lbl  "L2 load misses"
#define PAPI_L2_STM_lbl  "L2 store misses"
#define PAPI_BTAC_M_lbl  "Br targt addr miss"
#define PAPI_PRF_DM_lbl  "Data prefetch miss"
#define PAPI_L3_DCH_lbl  "L3D cache hits"
#define PAPI_TLB_SD_lbl  "TLB shootdowns"
#define PAPI_CSR_FAL_lbl "Failed store cond"
#define PAPI_CSR_SUC_lbl "Good store cond"
#define PAPI_CSR_TOT_lbl "Total store cond"
#define PAPI_MEM_SCY_lbl "Stalled mem cycles"
#define PAPI_MEM_RCY_lbl "Stalled rd cycles"
#define PAPI_MEM_WCY_lbl "Stalled wr cycles"
#define PAPI_STL_ICY_lbl "No instr issue"
#define PAPI_FUL_ICY_lbl "Max instr issue"
#define PAPI_STL_CCY_lbl "No instr done"
#define PAPI_FUL_CCY_lbl "Max instr done"
#define PAPI_HW_INT_lbl  "Hdw interrupts"
#define PAPI_BR_UCN_lbl  "Uncond branch"
#define PAPI_BR_CN_lbl   "Cond branch"
#define PAPI_BR_TKN_lbl  "Cond branch taken" 
#define PAPI_BR_NTK_lbl  "Cond br not taken" 
#define PAPI_BR_MSP_lbl  "Cond br mspredictd"
#define PAPI_BR_PRC_lbl  "Cond br predicted"
#define PAPI_FMA_INS_lbl "FMAs completed"
#define PAPI_TOT_IIS_lbl "Instr issued"
#define PAPI_TOT_INS_lbl "Instr completed"
#define PAPI_INT_INS_lbl "Int instructions"
#define PAPI_FP_INS_lbl  "FP instructions"
#define PAPI_LD_INS_lbl  "Loads"
#define PAPI_SR_INS_lbl  "Stores"
#define PAPI_BR_INS_lbl  "Branches"
#define PAPI_VEC_INS_lbl "Vector/SIMD instr"
#define PAPI_FLOPS_lbl   "FP instr / second"
#define PAPI_RES_STL_lbl "Stalled res cycles"
#define PAPI_FP_STAL_lbl "Stalled FPU cycles"
#define PAPI_TOT_CYC_lbl "Total cycles"
#define PAPI_IPS_lbl     "Instr / second"
#define PAPI_LST_INS_lbl "L/S completed"
#define PAPI_SYC_INS_lbl "Syncs completed"
#define PAPI_L1_DCH_lbl  "L1D cache hits"
#define PAPI_L2_DCH_lbl  "L2D cache hits"
#define PAPI_L1_DCA_lbl  "L1D cache accesses"
#define PAPI_L2_DCA_lbl  "L2D cache accesses"
#define PAPI_L3_DCA_lbl  "L3D cache accesses"
#define PAPI_L1_DCR_lbl  "L1D cache reads"
#define PAPI_L2_DCR_lbl  "L2D cache reads"
#define PAPI_L3_DCR_lbl  "L3D cache reads"
#define PAPI_L1_DCW_lbl  "L1D cache writes"
#define PAPI_L2_DCW_lbl  "L2D cache writes"
#define PAPI_L3_DCW_lbl  "L3D cache writes"
#define PAPI_L1_ICH_lbl  "L1I cache hits"
#define PAPI_L2_ICH_lbl  "L2I cache hits"
#define PAPI_L3_ICH_lbl  "L3I cache hits"
#define PAPI_L1_ICA_lbl  "L1I cache accesses"
#define PAPI_L2_ICA_lbl  "L2I cache accesses"
#define PAPI_L3_ICA_lbl  "L3I cache accesses"
#define PAPI_L1_ICR_lbl  "L1I cache reads"
#define PAPI_L2_ICR_lbl  "L2I cache reads"
#define PAPI_L3_ICR_lbl  "L3I cache reads"
#define PAPI_L1_ICW_lbl  "L1I cache writes"
#define PAPI_L2_ICW_lbl  "L2I cache writes"
#define PAPI_L3_ICW_lbl  "L3I cache writes"
#define PAPI_L1_TCH_lbl  "L1 cache hits"
#define PAPI_L2_TCH_lbl  "L2 cache hits"
#define PAPI_L3_TCH_lbl  "L3 cache hits"
#define PAPI_L1_TCA_lbl  "L1 cache accesses"
#define PAPI_L2_TCA_lbl  "L2 cache accesses"
#define PAPI_L3_TCA_lbl  "L3 cache accesses"
#define PAPI_L1_TCR_lbl  "L1 cache reads"
#define PAPI_L2_TCR_lbl  "L2 cache reads"
#define PAPI_L3_TCR_lbl  "L3 cache reads"
#define PAPI_L1_TCW_lbl  "L1 cache writes"
#define PAPI_L2_TCW_lbl  "L2 cache writes"
#define PAPI_L3_TCW_lbl  "L3 cache writes"
#define PAPI_FML_INS_lbl "FPU multiply"
#define PAPI_FAD_INS_lbl "FPU add"
#define PAPI_FDV_INS_lbl "FPU divide"
#define PAPI_FSQ_INS_lbl "FPU square root"
#define PAPI_FNV_INS_lbl "FPU inverse"

/********************************************************/
/* This block provides descriptions of each PAPI return */
/* It should be synchronized with return codes          */
/* found in "papi.h"                                    */
/********************************************************/
#define PAPI_OK_dsc         "nessun errore"
#define PAPI_EINVAL_dsc     "argomento non valido"
#define PAPI_ENOMEM_dsc     "memoria insufficiente"
#define PAPI_ESYS_dsc       "una chiamata della libreria del sistema / C e venuto a mancare"
#define PAPI_ESBSTR_dsc     "non sostenuto dal substrato"
#define PAPI_ECLOST_dsc     "l' accesso ai contatori e stato perso o interrotto"
#define PAPI_EBUG_dsc       "l' errore interno, trasmette prego la posta agli sviluppatori"
#define PAPI_ENOEVNT_dsc    "l' evento non esiste"
#define PAPI_ECNFLCT_dsc    "l' evento esiste, ma non puo essere contato dovuto i limiti delle risorse di hardware"
#define PAPI_ENOTRUN_dsc    "EventSet attualmente non sta funzionando"
#define PAPI_EISRUN_dsc     "EventSet attualmente sta contando"
#define PAPI_ENOEVST_dsc    "nessun tali EventSet disponibile"
#define PAPI_ENOTPRESET_dsc "l' evento nell' argomento non e un valido ha prestabilito"
#define PAPI_ENOCNTR_dsc    "il hardware non sostiene i contatori di prestazioni"
#define PAPI_EMISC_dsc      "codice di errore sconosciuto"


/********************************************************/
/* This block provides general strings used in PAPI     */
/* If a new string is needed for PAPI prompts           */
/* it should be placed in this file and referenced by   */
/* label. In that way it can be translated as needed.   */
/********************************************************/
#define PAPI_ERROR_CODE_str  "Codice Di Errore Di PAPI"
#define PAPI_THREAD_INIT_str "PAPI_thread_init: dovrebbe soltanto essere chiamato once\n" 
#define PAPI_SHUTDOWN_str	 "Errore di PAPI_shutdown: PAPI attualmente non inizializzato\n"
#define PAPI_NO_RESTORE_str	 "PAPI_restore attualmente non è effettuato\n"
#define PAPI_NO_SAVE_str	 "PAPI_save attualmente non è effettuato\n"
#define PAPI_SHUTDOWN_SYNC_str	 "Errore di PAPI_shutdown: Other threads still have running EventSets\n"


