#ifndef __PAPI_ROCM_STD_EVENT_DEFS_H__
#define __PAPI_ROCM_STD_EVENT_DEFS_H__

#define PAPI_MAX_rocm_PRESETS 128

enum
{
    PAPI_ROCM_FP16_FMA_idx = PAPI_rocm_PRESET_OFFSET,
    PAPI_ROCM_BF16_FMA_idx,
    PAPI_ROCM_FP32_FMA_idx,
    PAPI_ROCM_FP64_FMA_idx,
    PAPI_ROCM_FP_FMA_idx,
    PAPI_ROCM_FP8_OPS_idx
};

#define PAPI_ROCM_FP16_FMA  (PAPI_ROCM_FP16_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_ROCM_BF16_FMA  (PAPI_ROCM_BF16_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_ROCM_FP32_FMA  (PAPI_ROCM_FP32_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_ROCM_FP64_FMA  (PAPI_ROCM_FP64_FMA_idx | PAPI_PRESET_MASK)
#define PAPI_ROCM_FP_FMA    (PAPI_ROCM_FP_FMA_idx   | PAPI_PRESET_MASK)
#define PAPI_ROCM_FP8_OPS   (PAPI_ROCM_FP8_OPS_idx  | PAPI_PRESET_MASK)

#endif /* __PAPI_ROCM_STD_EVENT_DEFS_H__ */
