name: cuda

on:
  pull_request:
    # run CI only if cuda directory or cuda sub-directories receive updates
    paths:
      - 'src/components/cuda/**'
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  component_tests:
    strategy:
      matrix:
        component: [cuda]
        debug: [yes, no] 
        shlib: [with, without]
      fail-fast: false
    runs-on: [self-hosted, gpu_nvidia]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: cuda component tests
        run: .github/workflows/ci_individual_component.sh ${{matrix.component}} ${{matrix.debug}} ${{matrix.shlib}}
