name: intel_gpu

on:
  pull_request:
    # run CI only if intel_gpu directory or intel_gpu sub-directories receive updates
    paths:
      - 'src/components/intel_gpu/**'
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  component_tests:
    strategy:
      matrix:
        component: [intel_gpu]
        debug: [yes, no] 
        shlib: [with, without]
      fail-fast: false
    runs-on: [self-hosted, gpu_intel]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: intel_gpu component tests
        run: .github/workflows/ci_individual_component.sh ${{matrix.component}} ${{matrix.debug}} ${{matrix.shlib}}
