name: rocm_smi

on:
  pull_request:
    # run CI only if rocm_smi directory or rocm_smi sub-directories receive updates
    paths:
      - 'src/components/rocm_smi/**'
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  component_tests:
    strategy:
      matrix:
        component: [rocm_smi]
        debug: [yes, no] 
        shlib: [with, without]
      fail-fast: false
    runs-on: [self-hosted, gpu_amd]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: rocm_smi component tests
        run: .github/workflows_scripts/ci_individual_component.sh ${{matrix.component}} ${{matrix.debug}} ${{matrix.shlib}}
